/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jbehave.core.io.AbsolutePathCalculator;


public class AbsolutePathCalculatorEvoSuiteTest {

}
