/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.BufferedWriter;
import java.io.CharArrayWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.io.Writer;
import java.net.InetAddress;
import java.net.InterfaceAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLClassLoader;
import java.net.UnknownHostException;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;
import org.jbehave.core.io.StoryResourceNotFound;


public class StoryResourceNotFoundEvoSuiteTest {


  //Test case number: 1  @Test
  public void test1()  throws Throwable  {
      String string0 = "'9{N4I8x@0";
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte)0;
      byteArray0[1] = (byte)124;
      byteArray0[0] = (byte)124;
      byteArray0[1] = (byte)124;
      byteArray0[2] = (byte)0;
      byteArray0[3] = (byte)124;
      byteArray0[4] = (byte)0;
      byteArray0[2] = (byte)0;
      byteArray0[3] = (byte)29;
      byteArray0[4] = (byte)0;
      try {
        InetAddress.getByAddress(byteArray0);
      }catch(UnknownHostException e) {
        /*
         * addr is of illegal length
         */
        /*
      %%%<ex><className val="UnknownHostException"/><stackDepth val="15"/><causeDepth val="0"/><source val="java.net.InetAddress.getByAddress(InetAddress.java:1008)"/></ex>%%%
         */
      }
  }
}
