/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.io;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.Locale;
import org.jbehave.core.Embeddable;
import org.jbehave.core.io.UnderscoredCamelCaseResolver;


public class UnderscoredCamelCaseResolverEvoSuiteTest {


  //Test case number: 2
  /*
   * 6 covered goals:
   * 1 org.jbehave.core.io.UnderscoredCamelCaseResolver.<init>(Ljava/lang/String;)V: root-Branch
   * 2 org.jbehave.core.io.UnderscoredCamelCaseResolver.<init>(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * 3 org.jbehave.core.io.UnderscoredCamelCaseResolver.removeFromClassName(Ljava/lang/String;)Lorg/jbehave/core/io/StoryPathResolver;: root-Branch
   * 4 org.jbehave.core.io.UnderscoredCamelCaseResolver.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/Locale;)V: root-Branch
   * 5 org.jbehave.core.io.UnderscoredCamelCaseResolver.<init>()V: root-Branch
   * 6 org.jbehave.core.io.UnderscoredCamelCaseResolver.resolveName(Ljava/lang/Class;)Ljava/lang/String;: I62 Branch 1 IFNE L66 - true
   */
  @Test
  public void test2()  throws Throwable  {
      UnderscoredCamelCaseResolver underscoredCamelCaseResolver0 = new UnderscoredCamelCaseResolver("", "");
      UnderscoredCamelCaseResolver underscoredCamelCaseResolver1 = (UnderscoredCamelCaseResolver)underscoredCamelCaseResolver0.removeFromClassName("");
      UnderscoredCamelCaseResolver underscoredCamelCaseResolver2 = (UnderscoredCamelCaseResolver)underscoredCamelCaseResolver0.removeFromClassName("");
      UnderscoredCamelCaseResolver underscoredCamelCaseResolver3 = new UnderscoredCamelCaseResolver("", "");
      UnderscoredCamelCaseResolver underscoredCamelCaseResolver4 = new UnderscoredCamelCaseResolver();
      UnderscoredCamelCaseResolver underscoredCamelCaseResolver5 = new UnderscoredCamelCaseResolver("");
      UnderscoredCamelCaseResolver underscoredCamelCaseResolver6 = new UnderscoredCamelCaseResolver("", "", (Locale) null);
      Class<? extends Embeddable> class0 = Embeddable.class;
      // Undeclared exception!
      try {
        underscoredCamelCaseResolver6.resolve(class0);
      }catch(IndexOutOfBoundsException e) {
        /*
         * No group 1
         */
        /*
      %%%<ex><className val="IndexOutOfBoundsException"/><stackDepth val="16"/><causeDepth val="0"/><source val="java.util.regex.Matcher.group(Matcher.java:487)"/></ex>%%%
         */
      }
  }
}
