/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.junit;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;


public class JUnitStoriesEvoSuiteTest {

}
