/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.map;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.HashMap;
import org.apache.commons.collections4.keyvalue.MultiKey;
import org.apache.commons.collections4.map.AbstractHashedMap;
import org.apache.commons.collections4.map.MultiKeyMap;
import org.junit.BeforeClass;

public class MultiKeyMapEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 10 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.put(Lorg/apache/commons/collections4/keyvalue/MultiKey;Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * 2 org.apache.commons.collections4.map.MultiKeyMap.<init>(Lorg/apache/commons/collections4/map/AbstractHashedMap;)V: root-Branch
   * 3 org.apache.commons.collections4.map.MultiKeyMap.<init>()V: root-Branch
   * 4 org.apache.commons.collections4.map.MultiKeyMap.decorated()Lorg/apache/commons/collections4/map/AbstractHashedMap;: root-Branch
   * 5 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I27 Branch 49 IFNULL L407 - true
   * 6 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 61 IFNULL L501 - false
   * 7 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 62 IFNULL L504 - false
   * 8 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 63 IFNULL L507 - false
   * 9 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I40 Branch 64 IFNULL L510 - false
   * 10 org.apache.commons.collections4.map.MultiKeyMap.checkKey(Lorg/apache/commons/collections4/keyvalue/MultiKey;)V: I3 Branch 149 IFNONNULL L812 - false
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(165,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test0");
      MultiKeyMap<Object, String> multiKeyMap0 = new MultiKeyMap<Object, String>();
      Object object0 = new Object();
      multiKeyMap0.get(object0, object0, object0, object0);
      // Undeclared exception!
      try {
        multiKeyMap0.put((MultiKey<?>) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Key must not be null
         //
      }
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.containsKey(Ljava/lang/Object;Ljava/lang/Object;)Z: I25 Branch 6 IFNULL L159 - true
   * 2 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 15 IFNULL L225 - false
   * 3 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 16 IFNULL L228 - false
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(166,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test1");
      MultiKeyMap<Integer, AbstractHashedMap<String, HashMap<Integer, String>>> multiKeyMap0 = new MultiKeyMap<Integer, AbstractHashedMap<String, HashMap<Integer, String>>>();
      MultiKeyMap<String, MultiKey<Integer>> multiKeyMap1 = new MultiKeyMap<String, MultiKey<Integer>>();
      MultiKeyMap<MultiKeyMap<String, MultiKey<Integer>>, AbstractHashedMap<Integer, String>> multiKeyMap2 = new MultiKeyMap<MultiKeyMap<String, MultiKey<Integer>>, AbstractHashedMap<Integer, String>>();
      boolean boolean0 = multiKeyMap0.containsKey((Object) multiKeyMap1, (Object) multiKeyMap2);
      assertEquals(false, boolean0);
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.remove(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I33 Branch 12 IFNULL L204 - true
   * 2 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 15 IFNULL L225 - false
   * 3 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 16 IFNULL L228 - false
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(174,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test2");
      Object object0 = new Object();
      MultiKeyMap<MultiKey<MultiKey<Integer>>, AbstractHashedMap<Object, Object>> multiKeyMap0 = new MultiKeyMap<MultiKey<MultiKey<Integer>>, AbstractHashedMap<Object, Object>>();
      AbstractHashedMap<Object, Object> abstractHashedMap0 = multiKeyMap0.remove(object0, object0);
      assertNull(abstractHashedMap0);
  }

  //Test case number: 3
  /*
   * 6 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I26 Branch 24 IFNULL L268 - true
   * 2 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 36 IFNULL L358 - false
   * 3 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 37 IFNULL L361 - false
   * 4 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 38 IFNULL L364 - false
   * 5 org.apache.commons.collections4.map.MultiKeyMap.removeAll(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I13 Branch 135 IFEQ L791 - true
   * 6 org.apache.commons.collections4.map.MultiKeyMap.mapIterator()Lorg/apache/commons/collections4/MapIterator;: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(175,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test3");
      MultiKeyMap<MultiKey<Integer>, MultiKeyMap<String, Integer>> multiKeyMap0 = new MultiKeyMap<MultiKey<Integer>, MultiKeyMap<String, Integer>>();
      MultiKeyMap<Integer, Integer> multiKeyMap1 = new MultiKeyMap<Integer, Integer>();
      MultiKeyMap<String, MultiKey<Integer>> multiKeyMap2 = new MultiKeyMap<String, MultiKey<Integer>>();
      MultiKey<MultiKeyMap<String, MultiKey<Integer>>> multiKey0 = new MultiKey<MultiKeyMap<String, MultiKey<Integer>>>(multiKeyMap2, multiKeyMap2);
      MultiKeyMap<MultiKeyMap<Integer, MultiKeyMap<String, MultiKey<Integer>>>, String> multiKeyMap3 = new MultiKeyMap<MultiKeyMap<Integer, MultiKeyMap<String, MultiKey<Integer>>>, String>();
      multiKeyMap0.removeAll((Object) multiKeyMap1, (Object) multiKey0, (Object) multiKey0, (Object) multiKeyMap3);
      MultiKeyMap<MultiKey<String>, MultiKey<MultiKey<Integer>>> multiKeyMap4 = new MultiKeyMap<MultiKey<String>, MultiKey<MultiKey<Integer>>>();
      MultiKey<MultiKey<Integer>> multiKey1 = multiKeyMap4.get((Object) false, (Object) false, (Object) false);
      assertNull(multiKey1);
  }

  //Test case number: 4
  /*
   * 6 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I43 Branch 32 IFEQ L312 - true
   * 2 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I11 Branch 39 IF_ICMPNE L386 - true
   * 3 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I31 Branch 55 IFNULL L452 - true
   * 4 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I30 Branch 30 IFNULL L311 - true
   * 5 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I30 Branch 30 IFNULL L311 - false
   * 6 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I36 Branch 31 IF_ICMPNE L312 - false
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(176,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test4");
      MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>> multiKeyMap0 = new MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>>();
      MultiKeyMap<String, String> multiKeyMap1 = new MultiKeyMap<String, String>();
      multiKeyMap0.put(multiKeyMap1, multiKeyMap1, multiKeyMap1, multiKeyMap1, multiKeyMap1);
      multiKeyMap0.put(multiKeyMap1, multiKeyMap1, multiKeyMap1, multiKeyMap1);
      assertEquals(2, multiKeyMap0.size());
      assertEquals("{MultiKey[{}, {}, {}]={}, MultiKey[{}, {}, {}, {}]={}}", multiKeyMap0.toString());
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 36 IFNULL L358 - true
   * 2 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 37 IFNULL L361 - true
   * 3 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 38 IFNULL L364 - true
   */

  @Test
  public void test5()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(177,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test5");
      MultiKeyMap<Integer, Integer> multiKeyMap0 = new MultiKeyMap<Integer, Integer>();
      MultiKeyMap<Object, MultiKeyMap<Integer, Integer>> multiKeyMap1 = new MultiKeyMap<Object, MultiKeyMap<Integer, Integer>>();
      multiKeyMap1.put((Object) null, (Object) null, (Object) null, multiKeyMap0);
      assertEquals(1, multiKeyMap1.size());
      assertEquals("{MultiKey[null, null, null]={}}", multiKeyMap1.toString());
  }

  //Test case number: 6
  /*
   * 18 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I46 Branch 47 IFNULL L386 - false
   * 2 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I52 Branch 48 IFEQ L386 - false
   * 3 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 36 IFNULL L358 - false
   * 4 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 37 IFNULL L361 - false
   * 5 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 38 IFNULL L364 - false
   * 6 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I11 Branch 39 IF_ICMPNE L386 - false
   * 7 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I16 Branch 40 IF_ACMPEQ L386 - true
   * 8 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I18 Branch 41 IFNULL L386 - false
   * 9 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I24 Branch 42 IFEQ L386 - false
   * 10 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I30 Branch 43 IF_ACMPEQ L386 - true
   * 11 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I32 Branch 44 IFNULL L386 - false
   * 12 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I38 Branch 45 IFEQ L386 - false
   * 13 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 46 IF_ACMPEQ L386 - true
   * 14 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I30 Branch 30 IFNULL L311 - true
   * 15 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I30 Branch 30 IFNULL L311 - false
   * 16 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I36 Branch 31 IF_ICMPNE L312 - false
   * 17 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I43 Branch 32 IFEQ L312 - false
   * 18 org.apache.commons.collections4.map.MultiKeyMap.clone()Lorg/apache/commons/collections4/map/MultiKeyMap;: root-Branch
   */

  @Test
  public void test6()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(178,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test6");
      MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>> multiKeyMap0 = new MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>>();
      MultiKeyMap<String, String> multiKeyMap1 = new MultiKeyMap<String, String>();
      MultiKeyMap<String, String> multiKeyMap2 = multiKeyMap1.clone();
      multiKeyMap0.put(multiKeyMap1, multiKeyMap1, multiKeyMap2, multiKeyMap1);
      multiKeyMap0.put(multiKeyMap2, multiKeyMap2, multiKeyMap1, multiKeyMap2);
      assertEquals(false, multiKeyMap0.isEmpty());
      assertEquals("{MultiKey[{}, {}, {}]={}}", multiKeyMap0.toString());
  }

  //Test case number: 7
  /*
   * 11 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.containsKey(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I27 Branch 52 IFNULL L429 - false
   * 2 org.apache.commons.collections4.map.MultiKeyMap.containsKey(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I33 Branch 53 IF_ICMPNE L430 - false
   * 3 org.apache.commons.collections4.map.MultiKeyMap.containsKey(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I41 Branch 54 IFEQ L430 - true
   * 4 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I11 Branch 65 IF_ICMPNE L533 - true
   * 5 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I32 Branch 84 IFNULL L604 - true
   * 6 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 90 IFNULL L655 - false
   * 7 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 91 IFNULL L658 - false
   * 8 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 92 IFNULL L661 - false
   * 9 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I40 Branch 93 IFNULL L664 - false
   * 10 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I51 Branch 94 IFNULL L667 - false
   * 11 org.apache.commons.collections4.map.MultiKeyMap.containsKey(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I27 Branch 52 IFNULL L429 - true
   */

  @Test
  public void test7()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(179,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test7");
      MultiKeyMap<MultiKeyMap<String, MultiKey<Integer>>, HashMap<MultiKey<Integer>, HashMap<Integer, String>>> multiKeyMap0 = new MultiKeyMap<MultiKeyMap<String, MultiKey<Integer>>, HashMap<MultiKey<Integer>, HashMap<Integer, String>>>();
      MultiKeyMap<Integer, Integer> multiKeyMap1 = new MultiKeyMap<Integer, Integer>();
      MultiKeyMap<Object, MultiKeyMap<Integer, Integer>> multiKeyMap2 = new MultiKeyMap<Object, MultiKeyMap<Integer, Integer>>();
      multiKeyMap2.put((Object) multiKeyMap2, (Object) multiKeyMap2, (Object) multiKeyMap2, (Object) multiKeyMap2, (Object) multiKeyMap2, multiKeyMap1);
      assertEquals(false, multiKeyMap2.isEmpty());
      
      boolean boolean0 = multiKeyMap2.containsKey((Object) multiKeyMap0, (Object) multiKeyMap0, (Object) multiKeyMap0, (Object) multiKeyMap0);
      assertEquals(false, boolean0);
  }

  //Test case number: 8
  /*
   * 7 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I31 Branch 55 IFNULL L452 - false
   * 2 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I37 Branch 56 IF_ICMPNE L453 - false
   * 3 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I45 Branch 57 IFEQ L453 - true
   * 4 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 61 IFNULL L501 - true
   * 5 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I11 Branch 65 IF_ICMPNE L533 - false
   * 6 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I16 Branch 66 IF_ACMPEQ L533 - false
   * 7 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I18 Branch 67 IFNULL L533 - true
   */

  @Test
  public void test8()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(180,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test8");
      MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>> multiKeyMap0 = new MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>>();
      MultiKeyMap<String, String> multiKeyMap1 = new MultiKeyMap<String, String>();
      multiKeyMap0.put(multiKeyMap1, multiKeyMap1, multiKeyMap1, multiKeyMap1, multiKeyMap1);
      multiKeyMap0.put((MultiKeyMap<String, String>) null, multiKeyMap1, multiKeyMap1, multiKeyMap1, (MultiKeyMap<String, String>) null);
      assertEquals(false, multiKeyMap0.isEmpty());
      assertEquals("{MultiKey[null, {}, {}, {}]=null, MultiKey[{}, {}, {}, {}]={}}", multiKeyMap0.toString());
  }

  //Test case number: 9
  /*
   * 5 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 62 IFNULL L504 - true
   * 2 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 63 IFNULL L507 - true
   * 3 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I40 Branch 64 IFNULL L510 - true
   * 4 org.apache.commons.collections4.map.MultiKeyMap.containsKey(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I27 Branch 52 IFNULL L429 - true
   * 5 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 61 IFNULL L501 - true
   */

  @Test
  public void test9()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(181,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test9");
      MultiKeyMap<Object, MultiKeyMap<Integer, Integer>> multiKeyMap0 = new MultiKeyMap<Object, MultiKeyMap<Integer, Integer>>();
      boolean boolean0 = multiKeyMap0.containsKey((Object) null, (Object) null, (Object) null, (Object) null);
      assertEquals(false, boolean0);
  }

  //Test case number: 10
  /*
   * 11 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I18 Branch 67 IFNULL L533 - false
   * 2 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I24 Branch 68 IFEQ L533 - false
   * 3 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I32 Branch 70 IFNULL L533 - false
   * 4 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I38 Branch 71 IFEQ L533 - false
   * 5 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I46 Branch 73 IFNULL L533 - false
   * 6 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I52 Branch 74 IFEQ L533 - false
   * 7 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I16 Branch 66 IF_ACMPEQ L533 - true
   * 8 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I30 Branch 69 IF_ACMPEQ L533 - true
   * 9 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 72 IF_ACMPEQ L533 - true
   * 10 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I58 Branch 75 IF_ACMPEQ L533 - true
   * 11 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I45 Branch 57 IFEQ L453 - false
   */

  @Test
  public void test10()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(167,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test10");
      MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>> multiKeyMap0 = new MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>>();
      MultiKeyMap<String, String> multiKeyMap1 = new MultiKeyMap<String, String>();
      MultiKeyMap<String, String> multiKeyMap2 = multiKeyMap1.clone();
      multiKeyMap0.put(multiKeyMap1, multiKeyMap1, multiKeyMap1, multiKeyMap2, multiKeyMap1);
      multiKeyMap0.put(multiKeyMap2, multiKeyMap2, multiKeyMap2, multiKeyMap2, multiKeyMap2);
      assertEquals(1, multiKeyMap0.size());
      assertEquals("{MultiKey[{}, {}, {}, {}]={}}", multiKeyMap0.toString());
  }

  //Test case number: 11
  /*
   * 18 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I60 Branch 76 IFNULL L533 - false
   * 2 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I66 Branch 77 IFEQ L533 - false
   * 3 org.apache.commons.collections4.map.MultiKeyMap.clone()Lorg/apache/commons/collections4/map/MultiKeyMap;: root-Branch
   * 4 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I11 Branch 65 IF_ICMPNE L533 - false
   * 5 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I16 Branch 66 IF_ACMPEQ L533 - true
   * 6 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I30 Branch 69 IF_ACMPEQ L533 - true
   * 7 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 72 IF_ACMPEQ L533 - true
   * 8 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I46 Branch 73 IFNULL L533 - false
   * 9 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I52 Branch 74 IFEQ L533 - false
   * 10 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I58 Branch 75 IF_ACMPEQ L533 - true
   * 11 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 61 IFNULL L501 - false
   * 12 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 62 IFNULL L504 - false
   * 13 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 63 IFNULL L507 - false
   * 14 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I40 Branch 64 IFNULL L510 - false
   * 15 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I31 Branch 55 IFNULL L452 - true
   * 16 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I31 Branch 55 IFNULL L452 - false
   * 17 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I37 Branch 56 IF_ICMPNE L453 - false
   * 18 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I45 Branch 57 IFEQ L453 - false
   */

  @Test
  public void test11()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(168,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test11");
      MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>> multiKeyMap0 = new MultiKeyMap<MultiKeyMap<String, String>, MultiKeyMap<String, String>>();
      MultiKeyMap<String, String> multiKeyMap1 = new MultiKeyMap<String, String>();
      MultiKeyMap<String, String> multiKeyMap2 = multiKeyMap1.clone();
      multiKeyMap0.put(multiKeyMap2, multiKeyMap1, multiKeyMap2, multiKeyMap2, multiKeyMap2);
      multiKeyMap0.put(multiKeyMap2, multiKeyMap1, multiKeyMap1, multiKeyMap1, multiKeyMap2);
      assertEquals(1, multiKeyMap0.size());
      assertEquals("{MultiKey[{}, {}, {}, {}]={}}", multiKeyMap0.toString());
  }

  //Test case number: 12
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I28 Branch 78 IFNULL L556 - false
   * 2 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I28 Branch 78 IFNULL L556 - true
   * 3 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I34 Branch 79 IF_ICMPNE L557 - true
   * 4 org.apache.commons.collections4.map.MultiKeyMap.removeAll(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I13 Branch 135 IFEQ L791 - true
   */

  @Test
  public void test12()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(169,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test12");
      MultiKeyMap<MultiKey<Integer>, MultiKeyMap<String, Integer>> multiKeyMap0 = new MultiKeyMap<MultiKey<Integer>, MultiKeyMap<String, Integer>>();
      MultiKeyMap<Integer, Integer> multiKeyMap1 = new MultiKeyMap<Integer, Integer>();
      MultiKeyMap<String, MultiKey<Integer>> multiKeyMap2 = new MultiKeyMap<String, MultiKey<Integer>>();
      MultiKey<MultiKeyMap<String, MultiKey<Integer>>> multiKey0 = new MultiKey<MultiKeyMap<String, MultiKey<Integer>>>(multiKeyMap2, multiKeyMap2);
      MultiKeyMap<MultiKeyMap<Integer, MultiKeyMap<String, MultiKey<Integer>>>, String> multiKeyMap3 = new MultiKeyMap<MultiKeyMap<Integer, MultiKeyMap<String, MultiKey<Integer>>>, String>();
      multiKeyMap0.removeAll((Object) multiKeyMap1, (Object) multiKey0, (Object) multiKey0, (Object) multiKeyMap3);
      MultiKeyMap<Object, MultiKeyMap<Integer, Integer>> multiKeyMap4 = new MultiKeyMap<Object, MultiKeyMap<Integer, Integer>>();
      multiKeyMap4.put((Object) false, (Object) false, (Object) false, (Object) false, (Object) false, multiKeyMap1);
      multiKeyMap4.get((Object) multiKeyMap0, (Object) multiKeyMap0, (Object) multiKeyMap0, (Object) multiKeyMap0, (Object) multiKeyMap0);
      assertEquals(1, multiKeyMap4.size());
      assertEquals(false, multiKeyMap4.isEmpty());
  }

  //Test case number: 13
  /*
   * 7 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I34 Branch 79 IF_ICMPNE L557 - false
   * 2 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I43 Branch 80 IFEQ L557 - true
   * 3 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I11 Branch 95 IF_ICMPNE L691 - false
   * 4 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I16 Branch 96 IF_ACMPEQ L691 - false
   * 5 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I18 Branch 97 IFNULL L691 - false
   * 6 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I24 Branch 98 IFEQ L691 - true
   * 7 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I28 Branch 78 IFNULL L556 - true
   */

  @Test
  public void test13()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(170,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test13");
      MultiKeyMap<Integer, Integer> multiKeyMap0 = new MultiKeyMap<Integer, Integer>();
      MultiKeyMap<String, MultiKey<Integer>> multiKeyMap1 = new MultiKeyMap<String, MultiKey<Integer>>();
      MultiKey<MultiKeyMap<String, MultiKey<Integer>>> multiKey0 = new MultiKey<MultiKeyMap<String, MultiKey<Integer>>>(multiKeyMap1, multiKeyMap1);
      MultiKeyMap<Object, MultiKeyMap<Integer, Integer>> multiKeyMap2 = new MultiKeyMap<Object, MultiKeyMap<Integer, Integer>>();
      multiKeyMap2.put((Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1, multiKeyMap0);
      multiKeyMap2.get((Object) multiKey0, (Object) multiKey0, (Object) multiKey0, (Object) multiKey0, (Object) multiKey0);
      assertEquals("{MultiKey[{}, {}, {}, {}, {}]={}}", multiKeyMap2.toString());
      assertEquals(1, multiKeyMap2.size());
  }

  //Test case number: 14
  /*
   * 14 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I43 Branch 80 IFEQ L557 - false
   * 2 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I16 Branch 96 IF_ACMPEQ L691 - true
   * 3 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I30 Branch 99 IF_ACMPEQ L691 - true
   * 4 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 102 IF_ACMPEQ L691 - true
   * 5 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I58 Branch 105 IF_ACMPEQ L691 - true
   * 6 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I72 Branch 108 IF_ACMPEQ L691 - true
   * 7 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I28 Branch 78 IFNULL L556 - false
   * 8 org.apache.commons.collections4.map.MultiKeyMap.get(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I34 Branch 79 IF_ICMPNE L557 - false
   * 9 org.apache.commons.collections4.map.MultiKeyMap.isEqualKey(Lorg/apache/commons/collections4/map/AbstractHashedMap$HashEntry;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Z: I11 Branch 95 IF_ICMPNE L691 - false
   * 10 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 90 IFNULL L655 - false
   * 11 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 91 IFNULL L658 - false
   * 12 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 92 IFNULL L661 - false
   * 13 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I40 Branch 93 IFNULL L664 - false
   * 14 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I51 Branch 94 IFNULL L667 - false
   */

  @Test
  public void test14()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(171,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test14");
      MultiKeyMap<Integer, Integer> multiKeyMap0 = new MultiKeyMap<Integer, Integer>();
      MultiKeyMap<String, MultiKey<Integer>> multiKeyMap1 = new MultiKeyMap<String, MultiKey<Integer>>();
      MultiKeyMap<Object, MultiKeyMap<Integer, Integer>> multiKeyMap2 = new MultiKeyMap<Object, MultiKeyMap<Integer, Integer>>();
      multiKeyMap2.put((Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1, multiKeyMap0);
      assertEquals("{MultiKey[{}, {}, {}, {}, {}]={}}", multiKeyMap2.toString());
      
      MultiKeyMap<Integer, Integer> multiKeyMap3 = multiKeyMap2.get((Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1, (Object) multiKeyMap1);
      assertSame(multiKeyMap3, multiKeyMap0);
  }

  //Test case number: 15
  /*
   * 6 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 90 IFNULL L655 - true
   * 2 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I18 Branch 91 IFNULL L658 - true
   * 3 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I29 Branch 92 IFNULL L661 - true
   * 4 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I40 Branch 93 IFNULL L664 - true
   * 5 org.apache.commons.collections4.map.MultiKeyMap.hash(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I: I51 Branch 94 IFNULL L667 - true
   * 6 org.apache.commons.collections4.map.MultiKeyMap.put(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: I32 Branch 84 IFNULL L604 - true
   */

  @Test
  public void test15()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(172,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test15");
      MultiKeyMap<Integer, Integer> multiKeyMap0 = new MultiKeyMap<Integer, Integer>();
      MultiKeyMap<Object, MultiKeyMap<Integer, Integer>> multiKeyMap1 = new MultiKeyMap<Object, MultiKeyMap<Integer, Integer>>();
      multiKeyMap1.put((Object) null, (Object) null, (Object) null, (Object) null, (Object) null, multiKeyMap0);
      assertEquals(1, multiKeyMap1.size());
      assertEquals("{MultiKey[null, null, null, null, null]={}}", multiKeyMap1.toString());
  }

  //Test case number: 16
  /*
   * 5 covered goals:
   * 1 org.apache.commons.collections4.map.MultiKeyMap.removeAll(Ljava/lang/Object;)Z: I13 Branch 111 IFEQ L713 - true
   * 2 org.apache.commons.collections4.map.MultiKeyMap.mapIterator()Lorg/apache/commons/collections4/MapIterator;: root-Branch
   * 3 org.apache.commons.collections4.map.MultiKeyMap.<init>(Lorg/apache/commons/collections4/map/AbstractHashedMap;)V: root-Branch
   * 4 org.apache.commons.collections4.map.MultiKeyMap.<init>()V: root-Branch
   * 5 org.apache.commons.collections4.map.MultiKeyMap.decorated()Lorg/apache/commons/collections4/map/AbstractHashedMap;: root-Branch
   */

  @Test
  public void test16()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(173,"org.apache.commons.collections4.map.MultiKeyMapEvoSuiteTest.test16");
      MultiKeyMap<String, Integer> multiKeyMap0 = new MultiKeyMap<String, Integer>();
      MultiKeyMap<MultiKey<MultiKey<Integer>>, MultiKeyMap<String, MultiKey<Integer>>> multiKeyMap1 = new MultiKeyMap<MultiKey<MultiKey<Integer>>, MultiKeyMap<String, MultiKey<Integer>>>();
      boolean boolean0 = multiKeyMap0.removeAll((Object) multiKeyMap1);
      assertEquals(false, boolean0);
  }
}
