/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.map;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Array;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.Map;
import org.apache.commons.collections4.MapIterator;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.functors.EqualPredicate;
import org.apache.commons.collections4.functors.Equator;
import org.apache.commons.collections4.functors.FalsePredicate;
import org.apache.commons.collections4.functors.InstanceofPredicate;
import org.apache.commons.collections4.functors.NonePredicate;
import org.apache.commons.collections4.map.PredicatedMap;
import org.junit.BeforeClass;

public class PredicatedMapEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 6 covered goals:
   * 1 org.apache.commons.collections4.map.PredicatedMap.validate(Ljava/lang/Object;Ljava/lang/Object;)V: I4 Branch 2 IFNULL L142 - true
   * 2 org.apache.commons.collections4.map.PredicatedMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * 3 org.apache.commons.collections4.map.PredicatedMap.validate(Ljava/lang/Object;Ljava/lang/Object;)V: I21 Branch 4 IFNULL L145 - false
   * 4 org.apache.commons.collections4.map.PredicatedMap.validate(Ljava/lang/Object;Ljava/lang/Object;)V: I26 Branch 5 IFNE L145 - false
   * 5 org.apache.commons.collections4.map.PredicatedMap.predicatedMap(Ljava/util/Map;Lorg/apache/commons/collections4/Predicate;Lorg/apache/commons/collections4/Predicate;)Lorg/apache/commons/collections4/map/PredicatedMap;: root-Branch
   * 6 org.apache.commons.collections4.map.PredicatedMap.<init>(Ljava/util/Map;Lorg/apache/commons/collections4/Predicate;Lorg/apache/commons/collections4/Predicate;)V: I25 Branch 1 IFEQ L100 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(199,"org.apache.commons.collections4.map.PredicatedMapEvoSuiteTest.test0");
      HashMap<Integer, String> hashMap0 = new HashMap<Integer, String>();
      Class<Integer> class0 = Integer.class;
      InstanceofPredicate instanceofPredicate0 = new InstanceofPredicate(class0);
      HashMap<Integer, Integer> hashMap1 = new HashMap<Integer, Integer>();
      HashMap<HashMap<String, String>, Integer> hashMap2 = new HashMap<HashMap<String, String>, Integer>();
      PredicatedMap<HashMap<String, String>, Integer> predicatedMap0 = PredicatedMap.predicatedMap((Map<HashMap<String, String>, Integer>) hashMap2, (Predicate<? super HashMap<String, String>>) instanceofPredicate0, (Predicate<? super Integer>) instanceofPredicate0);
      assertNotNull(predicatedMap0);
      
      PredicatedMap<Integer, String> predicatedMap1 = PredicatedMap.predicatedMap((Map<Integer, String>) hashMap0, (Predicate<? super Integer>) null, (Predicate<? super String>) instanceofPredicate0);
      AbstractMap.SimpleEntry<String, HashMap<Integer, Integer>> abstractMap_SimpleEntry0 = new AbstractMap.SimpleEntry<String, HashMap<Integer, Integer>>("b-&o~z(qSAY'e>AAsN", hashMap1);
      abstractMap_SimpleEntry0.hashCode();
      predicatedMap1.remove((Object) predicatedMap0);
      // Undeclared exception!
      try {
        predicatedMap1.put((Integer) 1463475753, (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value - Predicate rejected it
         //
      }
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.map.PredicatedMap.validate(Ljava/lang/Object;Ljava/lang/Object;)V: I21 Branch 4 IFNULL L145 - true
   * 2 org.apache.commons.collections4.map.PredicatedMap.validate(Ljava/lang/Object;Ljava/lang/Object;)V: I9 Branch 3 IFNE L142 - true
   * 3 org.apache.commons.collections4.map.PredicatedMap.<init>(Ljava/util/Map;Lorg/apache/commons/collections4/Predicate;Lorg/apache/commons/collections4/Predicate;)V: I25 Branch 1 IFEQ L100 - false
   * 4 org.apache.commons.collections4.map.PredicatedMap.validate(Ljava/lang/Object;Ljava/lang/Object;)V: I4 Branch 2 IFNULL L142 - false
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(200,"org.apache.commons.collections4.map.PredicatedMapEvoSuiteTest.test1");
      HashMap<String, HashMap<Integer, Integer>> hashMap0 = new HashMap<String, HashMap<Integer, Integer>>();
      HashMap<Integer, Integer> hashMap1 = new HashMap<Integer, Integer>();
      HashMap<Object, Object> hashMap2 = new HashMap<Object, Object>();
      hashMap2.toString();
      hashMap0.put("{}", hashMap1);
      EqualPredicate<Object> equalPredicate0 = new EqualPredicate<Object>((Object) "{}", (Equator<Object>) null);
      PredicatedMap<String, HashMap<Integer, Integer>> predicatedMap0 = PredicatedMap.predicatedMap((Map<String, HashMap<Integer, Integer>>) hashMap0, (Predicate<? super String>) equalPredicate0, (Predicate<? super HashMap<Integer, Integer>>) null);
      assertEquals(false, predicatedMap0.isEmpty());
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.map.PredicatedMap.isSetValueChecking()Z: I4 Branch 7 IFNULL L174 - false
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(201,"org.apache.commons.collections4.map.PredicatedMapEvoSuiteTest.test2");
      Predicate<Object> predicate0 = FalsePredicate.INSTANCE;
      HashMap<Integer, Integer> hashMap0 = new HashMap<Integer, Integer>();
      PredicatedMap<Integer, Integer> predicatedMap0 = PredicatedMap.predicatedMap((Map<Integer, Integer>) hashMap0, (Predicate<? super Integer>) predicate0, (Predicate<? super Integer>) predicate0);
      MapIterator<Integer, Integer> mapIterator0 = predicatedMap0.mapIterator();
      assertEquals(false, mapIterator0.hasNext());
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.map.PredicatedMap.putAll(Ljava/util/Map;)V: I9 Branch 8 IFEQ L186 - true
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(202,"org.apache.commons.collections4.map.PredicatedMapEvoSuiteTest.test3");
      Predicate<Object>[] predicateArray0 = (Predicate<Object>[]) Array.newInstance(Predicate.class, 1);
      NonePredicate<Object> nonePredicate0 = new NonePredicate<Object>(predicateArray0);
      HashMap<Object, HashMap<Integer, Integer>> hashMap0 = new HashMap<Object, HashMap<Integer, Integer>>();
      PredicatedMap<Object, HashMap<Integer, Integer>> predicatedMap0 = PredicatedMap.predicatedMap((Map<Object, HashMap<Integer, Integer>>) hashMap0, (Predicate<? super Object>) nonePredicate0, (Predicate<? super HashMap<Integer, Integer>>) nonePredicate0);
      predicatedMap0.putAll((Map<?, ? extends HashMap<Integer, Integer>>) hashMap0);
      assertEquals("{}", hashMap0.toString());
  }

  //Test case number: 4
  /*
   * 5 covered goals:
   * 1 org.apache.commons.collections4.map.PredicatedMap.putAll(Ljava/util/Map;)V: I9 Branch 8 IFEQ L186 - false
   * 2 org.apache.commons.collections4.map.PredicatedMap.predicatedMap(Ljava/util/Map;Lorg/apache/commons/collections4/Predicate;Lorg/apache/commons/collections4/Predicate;)Lorg/apache/commons/collections4/map/PredicatedMap;: root-Branch
   * 3 org.apache.commons.collections4.map.PredicatedMap.validate(Ljava/lang/Object;Ljava/lang/Object;)V: I4 Branch 2 IFNULL L142 - false
   * 4 org.apache.commons.collections4.map.PredicatedMap.validate(Ljava/lang/Object;Ljava/lang/Object;)V: I9 Branch 3 IFNE L142 - false
   * 5 org.apache.commons.collections4.map.PredicatedMap.<init>(Ljava/util/Map;Lorg/apache/commons/collections4/Predicate;Lorg/apache/commons/collections4/Predicate;)V: I25 Branch 1 IFEQ L100 - true
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(203,"org.apache.commons.collections4.map.PredicatedMapEvoSuiteTest.test4");
      HashMap<Integer, String> hashMap0 = new HashMap<Integer, String>();
      Predicate<Object> predicate0 = FalsePredicate.INSTANCE;
      PredicatedMap<Integer, String> predicatedMap0 = PredicatedMap.predicatedMap((Map<Integer, String>) hashMap0, (Predicate<? super Integer>) predicate0, (Predicate<? super String>) predicate0);
      hashMap0.put((Integer) null, "Cannot add key - Predicate rejected it");
      // Undeclared exception!
      try {
        predicatedMap0.putAll((Map<? extends Integer, ? extends String>) hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add key - Predicate rejected it
         //
      }
  }
}
