/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.map;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Array;
import java.util.Comparator;
import java.util.NoSuchElementException;
import java.util.SortedMap;
import java.util.TreeMap;
import org.apache.commons.collections4.Closure;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.functors.ClosureTransformer;
import org.apache.commons.collections4.functors.ConstantTransformer;
import org.apache.commons.collections4.functors.InvokerTransformer;
import org.apache.commons.collections4.map.TransformedSortedMap;
import org.junit.BeforeClass;

public class TransformedSortedMapEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.map.TransformedSortedMap.firstKey()Ljava/lang/Object;: root-Branch
   * 2 org.apache.commons.collections4.map.TransformedSortedMap.<init>(Ljava/util/SortedMap;Lorg/apache/commons/collections4/Transformer;Lorg/apache/commons/collections4/Transformer;)V: root-Branch
   * 3 org.apache.commons.collections4.map.TransformedSortedMap.getSortedMap()Ljava/util/SortedMap;: root-Branch
   * 4 org.apache.commons.collections4.map.TransformedSortedMap.transformedSortedMap(Ljava/util/SortedMap;Lorg/apache/commons/collections4/Transformer;Lorg/apache/commons/collections4/Transformer;)Lorg/apache/commons/collections4/map/TransformedSortedMap;: I13 Branch 1 IFLE L95 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(262,"org.apache.commons.collections4.map.TransformedSortedMapEvoSuiteTest.test0");
      TreeMap<Integer, Integer> treeMap0 = new TreeMap<Integer, Integer>();
      ClosureTransformer<Integer> closureTransformer0 = new ClosureTransformer<Integer>((Closure<? super Integer>) null);
      TransformedSortedMap<Integer, Integer> transformedSortedMap0 = TransformedSortedMap.transformedSortedMap((SortedMap<Integer, Integer>) treeMap0, (Transformer<? super Integer, ? extends Integer>) closureTransformer0, (Transformer<? super Integer, ? extends Integer>) closureTransformer0);
      // Undeclared exception!
      try {
        transformedSortedMap0.firstKey();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.map.TransformedSortedMap.tailMap(Ljava/lang/Object;)Ljava/util/SortedMap;: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(263,"org.apache.commons.collections4.map.TransformedSortedMapEvoSuiteTest.test1");
      TreeMap<String, Object> treeMap0 = new TreeMap<String, Object>();
      TransformedSortedMap<String, Object> transformedSortedMap0 = TransformedSortedMap.transformedSortedMap((SortedMap<String, Object>) treeMap0, (Transformer<? super String, ? extends String>) null, (Transformer<? super Object, ?>) null);
      SortedMap<String, Object> sortedMap0 = transformedSortedMap0.tailMap("9%R1k");
      assertEquals(true, sortedMap0.isEmpty());
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.map.TransformedSortedMap.lastKey()Ljava/lang/Object;: root-Branch
   * 2 org.apache.commons.collections4.map.TransformedSortedMap.transformingSortedMap(Ljava/util/SortedMap;Lorg/apache/commons/collections4/Transformer;Lorg/apache/commons/collections4/Transformer;)Lorg/apache/commons/collections4/map/TransformedSortedMap;: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(264,"org.apache.commons.collections4.map.TransformedSortedMapEvoSuiteTest.test2");
      TreeMap<Object, Integer> treeMap0 = new TreeMap<Object, Integer>();
      ConstantTransformer<Object, String> constantTransformer0 = new ConstantTransformer<Object, String>("");
      ConstantTransformer<Object, Integer> constantTransformer1 = new ConstantTransformer<Object, Integer>((Integer) null);
      TransformedSortedMap<Object, Integer> transformedSortedMap0 = TransformedSortedMap.transformingSortedMap((SortedMap<Object, Integer>) treeMap0, (Transformer<? super Object, ?>) constantTransformer0, (Transformer<? super Integer, ? extends Integer>) constantTransformer1);
      // Undeclared exception!
      try {
        transformedSortedMap0.lastKey();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.map.TransformedSortedMap.subMap(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/SortedMap;: root-Branch
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(265,"org.apache.commons.collections4.map.TransformedSortedMapEvoSuiteTest.test3");
      TreeMap<Integer, Integer> treeMap0 = new TreeMap<Integer, Integer>();
      TreeMap<Integer, Object> treeMap1 = new TreeMap<Integer, Object>((SortedMap<Integer, ?>) treeMap0);
      Class<Integer>[] classArray0 = (Class<Integer>[]) Array.newInstance(Class.class, 7);
      InvokerTransformer<Object, Integer> invokerTransformer0 = new InvokerTransformer<Object, Integer>("V#)%<w5lBDgM/?pl", (Class<?>[]) classArray0, (Object[]) classArray0);
      TransformedSortedMap<Integer, Object> transformedSortedMap0 = TransformedSortedMap.transformingSortedMap((SortedMap<Integer, Object>) treeMap1, (Transformer<? super Integer, ? extends Integer>) invokerTransformer0, (Transformer<? super Object, ?>) invokerTransformer0);
      // Undeclared exception!
      try {
        transformedSortedMap0.subMap((Integer) null, (Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.map.TransformedSortedMap.comparator()Ljava/util/Comparator;: root-Branch
   * 2 org.apache.commons.collections4.map.TransformedSortedMap.transformingSortedMap(Ljava/util/SortedMap;Lorg/apache/commons/collections4/Transformer;Lorg/apache/commons/collections4/Transformer;)Lorg/apache/commons/collections4/map/TransformedSortedMap;: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(266,"org.apache.commons.collections4.map.TransformedSortedMapEvoSuiteTest.test4");
      TreeMap<Integer, Integer> treeMap0 = new TreeMap<Integer, Integer>();
      TreeMap<Integer, Object> treeMap1 = new TreeMap<Integer, Object>((SortedMap<Integer, ?>) treeMap0);
      Class<Integer>[] classArray0 = (Class<Integer>[]) Array.newInstance(Class.class, 7);
      InvokerTransformer<Object, Integer> invokerTransformer0 = new InvokerTransformer<Object, Integer>("V#)%<w5lBDgM/?pl", (Class<?>[]) classArray0, (Object[]) classArray0);
      TransformedSortedMap<Integer, Object> transformedSortedMap0 = TransformedSortedMap.transformingSortedMap((SortedMap<Integer, Object>) treeMap1, (Transformer<? super Integer, ? extends Integer>) invokerTransformer0, (Transformer<? super Object, ?>) invokerTransformer0);
      Comparator<? super Integer> comparator0 = transformedSortedMap0.comparator();
      assertNull(comparator0);
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.map.TransformedSortedMap.headMap(Ljava/lang/Object;)Ljava/util/SortedMap;: root-Branch
   * 2 org.apache.commons.collections4.map.TransformedSortedMap.getSortedMap()Ljava/util/SortedMap;: root-Branch
   * 3 org.apache.commons.collections4.map.TransformedSortedMap.transformedSortedMap(Ljava/util/SortedMap;Lorg/apache/commons/collections4/Transformer;Lorg/apache/commons/collections4/Transformer;)Lorg/apache/commons/collections4/map/TransformedSortedMap;: I13 Branch 1 IFLE L95 - true
   */

  @Test
  public void test5()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(267,"org.apache.commons.collections4.map.TransformedSortedMapEvoSuiteTest.test5");
      Class<String>[] classArray0 = (Class<String>[]) Array.newInstance(Class.class, 6);
      TreeMap<Object, String> treeMap0 = new TreeMap<Object, String>();
      InvokerTransformer<Object, String> invokerTransformer0 = new InvokerTransformer<Object, String>("", (Class<?>[]) classArray0, (Object[]) classArray0);
      TransformedSortedMap<Object, String> transformedSortedMap0 = TransformedSortedMap.transformedSortedMap((SortedMap<Object, String>) treeMap0, (Transformer<? super Object, ?>) invokerTransformer0, (Transformer<? super String, ? extends String>) invokerTransformer0);
      // Undeclared exception!
      try {
        transformedSortedMap0.headMap((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 6
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.map.TransformedSortedMap.transformedSortedMap(Ljava/util/SortedMap;Lorg/apache/commons/collections4/Transformer;Lorg/apache/commons/collections4/Transformer;)Lorg/apache/commons/collections4/map/TransformedSortedMap;: I13 Branch 1 IFLE L95 - false
   * 2 org.apache.commons.collections4.map.TransformedSortedMap.<init>(Ljava/util/SortedMap;Lorg/apache/commons/collections4/Transformer;Lorg/apache/commons/collections4/Transformer;)V: root-Branch
   */

  @Test
  public void test6()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(268,"org.apache.commons.collections4.map.TransformedSortedMapEvoSuiteTest.test6");
      TreeMap<String, Object> treeMap0 = new TreeMap<String, Object>();
      TreeMap<Object, Integer> treeMap1 = new TreeMap<Object, Integer>();
      treeMap0.put("9%R1k", (Object) treeMap1);
      TransformedSortedMap.transformedSortedMap((SortedMap<String, Object>) treeMap0, (Transformer<? super String, ? extends String>) null, (Transformer<? super Object, ?>) null);
      assertEquals("{9%R1k={}}", treeMap0.toString());
      assertEquals(false, treeMap0.isEmpty());
  }
}
