/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.map;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.HashMap;
import org.apache.commons.collections4.OrderedMap;
import org.apache.commons.collections4.map.UnmodifiableOrderedMap;
import org.junit.BeforeClass;

public class UnmodifiableOrderedMapEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.map.UnmodifiableOrderedMap.unmodifiableOrderedMap(Lorg/apache/commons/collections4/OrderedMap;)Lorg/apache/commons/collections4/OrderedMap;: I4 Branch 1 IFEQ L61 - true
   */

  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(269,"org.apache.commons.collections4.map.UnmodifiableOrderedMapEvoSuiteTest.test0");
      try {
        UnmodifiableOrderedMap.unmodifiableOrderedMap((OrderedMap<HashMap<Integer, Integer>, Object>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Map must not be null
         //
      }
  }
}
