/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.iterators;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Iterator;
import java.util.NoSuchElementException;
import org.apache.commons.collections4.FunctorException;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.functors.ExceptionTransformer;
import org.apache.commons.collections4.functors.StringValueTransformer;
import org.apache.commons.collections4.iterators.ObjectGraphIterator;
import org.junit.BeforeClass;

public class ObjectGraphIteratorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 15 covered goals:
   * 1 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I4 Branch 2 IFEQ L137 - false
   * 2 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I12 Branch 3 IFNONNULL L140 - true
   * 3 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I17 Branch 4 IFNONNULL L141 - true
   * 4 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I23 Branch 5 IFNONNULL L144 - false
   * 5 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNext(Ljava/lang/Object;)V: I4 Branch 6 IFEQ L163 - true
   * 6 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I5 Branch 7 IF_ACMPEQ L179 - true
   * 7 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I29 Branch 9 IFEQ L187 - false
   * 8 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I32 Branch 10 IFNE L187 - false
   * 9 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I43 Branch 11 IFNULL L189 - false
   * 10 org.apache.commons.collections4.iterators.ObjectGraphIterator.next()Ljava/lang/Object;: I8 Branch 14 IFNE L221 - true
   * 11 org.apache.commons.collections4.iterators.ObjectGraphIterator.<init>(Ljava/lang/Object;Lorg/apache/commons/collections4/Transformer;)V: I21 Branch 1 IFEQ L108 - false
   * 12 org.apache.commons.collections4.iterators.ObjectGraphIterator.hasNext()Z: root-Branch
   * 13 org.apache.commons.collections4.iterators.ObjectGraphIterator.<init>(Ljava/lang/Object;Lorg/apache/commons/collections4/Transformer;)V: I21 Branch 1 IFEQ L108 - true
   * 14 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I4 Branch 2 IFEQ L137 - true
   * 15 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I12 Branch 3 IFNONNULL L140 - false
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(601,"org.apache.commons.collections4.iterators.ObjectGraphIteratorEvoSuiteTest.test0");
      Object object0 = new Object();
      Transformer<Object, Object> transformer0 = ExceptionTransformer.INSTANCE;
      ObjectGraphIterator<Object> objectGraphIterator0 = new ObjectGraphIterator<Object>(object0, (Transformer<? super Object, ?>) null);
      assertEquals(true, objectGraphIterator0.hasNext());
      
      ObjectGraphIterator<Object> objectGraphIterator1 = new ObjectGraphIterator<Object>((Object) objectGraphIterator0, (Transformer<? super Object, ?>) transformer0);
      // Undeclared exception!
      boolean boolean0 = false;
      try {
        boolean0 = objectGraphIterator1.hasNext();
        fail("Expecting exception: FunctorException");
      
      } catch(FunctorException e) {
         //
         // ExceptionTransformer invoked
         //
      }
      
      assertEquals(false, objectGraphIterator0.hasNext());
  }

  //Test case number: 1
  /*
   * 5 covered goals:
   * 1 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I29 Branch 9 IFEQ L187 - true
   * 2 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I63 Branch 12 IFNE L195 - false
   * 3 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I67 Branch 13 IFNE L195 - true
   * 4 org.apache.commons.collections4.iterators.ObjectGraphIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * 5 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I17 Branch 4 IFNONNULL L141 - false
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(602,"org.apache.commons.collections4.iterators.ObjectGraphIteratorEvoSuiteTest.test1");
      ObjectGraphIterator<Object> objectGraphIterator0 = new ObjectGraphIterator<Object>((Iterator<?>) null);
      ObjectGraphIterator<Object> objectGraphIterator1 = new ObjectGraphIterator<Object>((Iterator<?>) objectGraphIterator0);
      boolean boolean0 = objectGraphIterator1.hasNext();
      assertEquals(false, boolean0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.iterators.ObjectGraphIterator.next()Ljava/lang/Object;: I8 Branch 14 IFNE L221 - false
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(603,"org.apache.commons.collections4.iterators.ObjectGraphIteratorEvoSuiteTest.test2");
      ObjectGraphIterator<Object> objectGraphIterator0 = new ObjectGraphIterator<Object>((Iterator<?>) null);
      // Undeclared exception!
      try {
        objectGraphIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No more elements in the iteration
         //
      }
  }

  //Test case number: 3
  /*
   * 20 covered goals:
   * 1 org.apache.commons.collections4.iterators.ObjectGraphIterator.remove()V: I4 Branch 15 IFNONNULL L245 - true
   * 2 org.apache.commons.collections4.iterators.ObjectGraphIterator.remove()V: I4 Branch 15 IFNONNULL L245 - false
   * 3 org.apache.commons.collections4.iterators.ObjectGraphIterator.hasNext()Z: root-Branch
   * 4 org.apache.commons.collections4.iterators.ObjectGraphIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * 5 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNext(Ljava/lang/Object;)V: I4 Branch 6 IFEQ L163 - true
   * 6 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I5 Branch 7 IF_ACMPEQ L179 - true
   * 7 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I29 Branch 9 IFEQ L187 - true
   * 8 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I29 Branch 9 IFEQ L187 - false
   * 9 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I32 Branch 10 IFNE L187 - false
   * 10 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I43 Branch 11 IFNULL L189 - true
   * 11 org.apache.commons.collections4.iterators.ObjectGraphIterator.findNextByIterator(Ljava/util/Iterator;)V: I63 Branch 12 IFNE L195 - true
   * 12 org.apache.commons.collections4.iterators.ObjectGraphIterator.next()Ljava/lang/Object;: I8 Branch 14 IFNE L221 - true
   * 13 org.apache.commons.collections4.iterators.ObjectGraphIterator.<init>(Ljava/lang/Object;Lorg/apache/commons/collections4/Transformer;)V: I21 Branch 1 IFEQ L108 - true
   * 14 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I4 Branch 2 IFEQ L137 - true
   * 15 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I4 Branch 2 IFEQ L137 - false
   * 16 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I12 Branch 3 IFNONNULL L140 - true
   * 17 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I12 Branch 3 IFNONNULL L140 - false
   * 18 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I17 Branch 4 IFNONNULL L141 - true
   * 19 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I17 Branch 4 IFNONNULL L141 - false
   * 20 org.apache.commons.collections4.iterators.ObjectGraphIterator.updateCurrentIterator()V: I23 Branch 5 IFNONNULL L144 - true
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(604,"org.apache.commons.collections4.iterators.ObjectGraphIteratorEvoSuiteTest.test3");
      Transformer<Object, String> transformer0 = StringValueTransformer.INSTANCE;
      ObjectGraphIterator<Object> objectGraphIterator0 = new ObjectGraphIterator<Object>((Object) "No more elements in the iteration", (Transformer<? super Object, ?>) transformer0);
      ObjectGraphIterator<Object> objectGraphIterator1 = new ObjectGraphIterator<Object>((Iterator<?>) objectGraphIterator0);
      String string0 = (String)objectGraphIterator1.next();
      assertNotNull(string0);
      
      // Undeclared exception!
      try {
        objectGraphIterator1.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Iterator remove() cannot be called at this time
         //
      }
  }
}
