/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.iterators;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Iterator;
import org.apache.commons.collections4.iterators.UniqueFilterIterator;
import org.junit.BeforeClass;

public class UniqueFilterIteratorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.iterators.UniqueFilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(667,"org.apache.commons.collections4.iterators.UniqueFilterIteratorEvoSuiteTest.test0");
      UniqueFilterIterator<Integer> uniqueFilterIterator0 = new UniqueFilterIterator<Integer>((Iterator<? extends Integer>) null);
  }
}
