/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.comparators;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.comparators.ComparableComparator;
import org.junit.BeforeClass;

public class ComparableComparatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.comparators.ComparableComparator.compare(Ljava/lang/Comparable;Ljava/lang/Comparable;)I: root-Branch
   * 2 org.apache.commons.collections4.comparators.ComparableComparator.hashCode()I: root-Branch
   * 3 org.apache.commons.collections4.comparators.ComparableComparator.<init>()V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(862,"org.apache.commons.collections4.comparators.ComparableComparatorEvoSuiteTest.test0");
      ComparableComparator<Integer> comparableComparator0 = new ComparableComparator<Integer>();
      int int0 = comparableComparator0.hashCode();
      assertEquals(1769708912, int0);
      
      int int1 = comparableComparator0.compare((Integer) 1769708912, (Integer) 1769708912);
      assertFalse(int1 == int0);
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.comparators.ComparableComparator.equals(Ljava/lang/Object;)Z: I7 Branch 2 IF_ACMPEQ L124 - false
   * 2 org.apache.commons.collections4.comparators.ComparableComparator.equals(Ljava/lang/Object;)Z: I13 Branch 3 IFEQ L124 - true
   * 3 org.apache.commons.collections4.comparators.ComparableComparator.equals(Ljava/lang/Object;)Z: I4 Branch 1 IF_ACMPEQ L124 - false
   * 4 org.apache.commons.collections4.comparators.ComparableComparator.equals(Ljava/lang/Object;)Z: I7 Branch 2 IF_ACMPEQ L124 - true
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(863,"org.apache.commons.collections4.comparators.ComparableComparatorEvoSuiteTest.test1");
      ComparableComparator<Integer> comparableComparator0 = new ComparableComparator<Integer>();
      comparableComparator0.equals((Object) null);
      boolean boolean0 = comparableComparator0.equals((Object) false);
      assertEquals(false, boolean0);
  }

  //Test case number: 2
  /*
   * 5 covered goals:
   * 1 org.apache.commons.collections4.comparators.ComparableComparator.equals(Ljava/lang/Object;)Z: I13 Branch 3 IFEQ L124 - false
   * 2 org.apache.commons.collections4.comparators.ComparableComparator.<init>()V: root-Branch
   * 3 org.apache.commons.collections4.comparators.ComparableComparator.comparableComparator()Lorg/apache/commons/collections4/comparators/ComparableComparator;: root-Branch
   * 4 org.apache.commons.collections4.comparators.ComparableComparator.equals(Ljava/lang/Object;)Z: I4 Branch 1 IF_ACMPEQ L124 - true
   * 5 org.apache.commons.collections4.comparators.ComparableComparator.equals(Ljava/lang/Object;)Z: I7 Branch 2 IF_ACMPEQ L124 - false
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(864,"org.apache.commons.collections4.comparators.ComparableComparatorEvoSuiteTest.test2");
      ComparableComparator<Integer> comparableComparator0 = new ComparableComparator<Integer>();
      ComparableComparator<Integer> comparableComparator1 = ComparableComparator.comparableComparator();
      boolean boolean0 = comparableComparator0.equals((Object) comparableComparator1);
      assertEquals(true, boolean0);
  }
}
