/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.comparators;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Array;
import java.util.LinkedList;
import java.util.List;
import org.apache.commons.collections4.comparators.FixedOrderComparator;
import org.junit.BeforeClass;

public class FixedOrderComparatorEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 8 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.getUnknownObjectBehavior()Lorg/apache/commons/collections4/comparators/FixedOrderComparator$UnknownObjectBehavior;: root-Branch
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.isLocked()Z: root-Branch
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>([Ljava/lang/Object;)V: I29 Branch 1 IFNONNULL L94 - true
   * 4 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>([Ljava/lang/Object;)V: I51 Branch 2 IF_ICMPGE L97 - true
   * 5 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>([Ljava/lang/Object;)V: I51 Branch 2 IF_ICMPGE L97 - false
   * 6 org.apache.commons.collections4.comparators.FixedOrderComparator.checkLocked()V: I4 Branch 5 IFEQ L140 - true
   * 7 org.apache.commons.collections4.comparators.FixedOrderComparator.add(Ljava/lang/Object;)Z: I23 Branch 7 IFNONNULL L185 - true
   * 8 org.apache.commons.collections4.comparators.FixedOrderComparator.add(Ljava/lang/Object;)Z: I23 Branch 7 IFNONNULL L185 - false
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(884,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test0");
      Integer[] integerArray0 = new Integer[11];
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>(integerArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = fixedOrderComparator0.getUnknownObjectBehavior();
      assertEquals("EXCEPTION", fixedOrderComparator_UnknownObjectBehavior0.name());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>([Ljava/lang/Object;)V: I29 Branch 1 IFNONNULL L94 - false
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(885,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test1");
      FixedOrderComparator<String> fixedOrderComparator0 = null;
      try {
        fixedOrderComparator0 = new FixedOrderComparator<String>((String[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The list of items must not be null
         //
      }
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>(Ljava/util/List;)V: I29 Branch 3 IFNONNULL L113 - false
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(893,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test2");
      FixedOrderComparator<Integer> fixedOrderComparator0 = null;
      try {
        fixedOrderComparator0 = new FixedOrderComparator<Integer>((List<Integer>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The list of items must not be null
         //
      }
  }

  //Test case number: 3
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>(Ljava/util/List;)V: I45 Branch 4 IFEQ L116 - false
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>(Ljava/util/List;)V: I29 Branch 3 IFNONNULL L113 - true
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>(Ljava/util/List;)V: I45 Branch 4 IFEQ L116 - true
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(894,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test3");
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("The list of items must not be null");
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>((List<String>) linkedList0);
      assertEquals(false, fixedOrderComparator0.isLocked());
  }

  //Test case number: 4
  /*
   * 9 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.checkLocked()V: I4 Branch 5 IFEQ L140 - false
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.setUnknownObjectBehavior(Lorg/apache/commons/collections4/comparators/FixedOrderComparator$UnknownObjectBehavior;)V: I7 Branch 6 IFNONNULL L164 - true
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I24 Branch 10 IFNULL L231 - true
   * 4 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 12 TABLESWITCH L232 Case 1 - true
   * 5 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 13 TABLESWITCH L232 Case 2 - false
   * 6 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 14 TABLESWITCH L232 Case 3 - false
   * 7 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 15 TABLESWITCH L232 Default-Case - false
   * 8 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I38 Branch 16 IFNONNULL L234 - false
   * 9 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I40 Branch 17 IFNONNULL L234 - false
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(895,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test4");
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>((List<String>) linkedList0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      assertEquals(FixedOrderComparator.UnknownObjectBehavior.BEFORE, fixedOrderComparator0.getUnknownObjectBehavior());
      
      fixedOrderComparator0.compare("LA;={", "LA;={");
      // Undeclared exception!
      try {
        fixedOrderComparator0.addAsEqual("LA;={", "LA;={");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Cannot modify a FixedOrderComparator after a comparison
         //
      }
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.setUnknownObjectBehavior(Lorg/apache/commons/collections4/comparators/FixedOrderComparator$UnknownObjectBehavior;)V: I7 Branch 6 IFNONNULL L164 - false
   */

  @Test
  public void test5()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(896,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test5");
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>((List<String>) linkedList0);
      // Undeclared exception!
      try {
        fixedOrderComparator0.setUnknownObjectBehavior((FixedOrderComparator.UnknownObjectBehavior) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unknown object behavior must not be null
         //
      }
  }

  //Test case number: 6
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.addAsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z: I15 Branch 8 IFNONNULL L204 - true
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.addAsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 9 IFNONNULL L208 - true
   */

  @Test
  public void test6()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(897,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test6");
      Integer[] integerArray0 = new Integer[3];
      Integer integer0 = new Integer(5);
      integerArray0[2] = integer0;
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>(integerArray0);
      boolean boolean0 = fixedOrderComparator0.addAsEqual((Integer) 5, integer0);
      assertEquals(false, boolean0);
  }

  //Test case number: 7
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.addAsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z: I15 Branch 8 IFNONNULL L204 - false
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.hashCode()I: I11 Branch 21 IFNONNULL L259 - true
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.hashCode()I: I28 Branch 22 IFNONNULL L260 - true
   * 4 org.apache.commons.collections4.comparators.FixedOrderComparator.hashCode()I: I54 Branch 23 IFEQ L262 - true
   */

  @Test
  public void test7()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(898,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test7");
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>((List<Integer>) linkedList0);
      // Undeclared exception!
      try {
        fixedOrderComparator0.addAsEqual((Integer) 1464, (Integer) 1464);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1464 not known to org.apache.commons.collections4.comparators.FixedOrderComparator@a78b0297
         //
      }
  }

  //Test case number: 8
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.addAsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z: I44 Branch 9 IFNONNULL L208 - false
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.addAsEqual(Ljava/lang/Object;Ljava/lang/Object;)Z: I15 Branch 8 IFNONNULL L204 - true
   */

  @Test
  public void test8()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(899,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test8");
      Integer[] integerArray0 = new Integer[3];
      Integer integer0 = new Integer((-673));
      Integer integer1 = new Integer(5);
      integerArray0[2] = integer1;
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>(integerArray0);
      boolean boolean0 = fixedOrderComparator0.addAsEqual((Integer) 5, integer0);
      assertEquals(true, boolean0);
  }

  //Test case number: 9
  /*
   * 5 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I26 Branch 11 IFNONNULL L231 - false
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 12 TABLESWITCH L232 Case 1 - false
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 14 TABLESWITCH L232 Case 3 - true
   * 4 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I68 Branch 20 IFNONNULL L238 - true
   * 5 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I24 Branch 10 IFNULL L231 - false
   */

  @Test
  public void test9()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(900,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test9");
      String[] stringArray0 = new String[4];
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>(stringArray0);
      // Undeclared exception!
      try {
        fixedOrderComparator0.compare((String) null, ",`$Om*Y");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Attempting to compare unknown object ,`$Om*Y
         //
      }
  }

  //Test case number: 10
  /*
   * 7 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 13 TABLESWITCH L232 Case 2 - true
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I53 Branch 18 IFNONNULL L236 - false
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I55 Branch 19 IFNONNULL L236 - false
   * 4 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I4 Branch 24 IF_ACMPNE L280 - true
   * 5 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I13 Branch 25 IF_ACMPNE L283 - true
   * 6 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I25 Branch 26 IFEQ L286 - true
   * 7 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 14 TABLESWITCH L232 Case 3 - false
   */

  @Test
  public void test10()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(886,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test10");
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>((List<Object>) linkedList0);
      fixedOrderComparator0.equals((Object) 0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.AFTER;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      assertEquals(false, fixedOrderComparator0.isLocked());
      
      int int0 = fixedOrderComparator0.compare((Object) false, (Object) false);
      assertEquals(true, fixedOrderComparator0.isLocked());
      assertEquals(0, int0);
  }

  //Test case number: 11
  /*
   * 6 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I68 Branch 20 IFNONNULL L238 - false
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I24 Branch 10 IFNULL L231 - true
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 12 TABLESWITCH L232 Case 1 - false
   * 4 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 13 TABLESWITCH L232 Case 2 - false
   * 5 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 14 TABLESWITCH L232 Case 3 - true
   * 6 org.apache.commons.collections4.comparators.FixedOrderComparator.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I34 Branch 15 TABLESWITCH L232 Default-Case - false
   */

  @Test
  public void test11()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(887,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test11");
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>((List<String>) linkedList0);
      assertEquals(false, fixedOrderComparator0.isLocked());
      
      // Undeclared exception!
      try {
        fixedOrderComparator0.compare("Ls;=&:", "Ls;=&:");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Attempting to compare unknown object Ls;=&:
         //
      }
  }

  
  //Test case number: 13
  /*
   * 13 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I4 Branch 24 IF_ACMPNE L280 - false
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I25 Branch 26 IFEQ L286 - false
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I36 Branch 27 IF_ACMPNE L288 - true
   * 4 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I52 Branch 29 IFEQ L288 - false
   * 5 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I56 Branch 30 IF_ACMPNE L288 - true
   * 6 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I71 Branch 32 IF_ACMPNE L288 - false
   * 7 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I76 Branch 33 IF_ICMPNE L288 - false
   * 8 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I81 Branch 34 IF_ICMPNE L288 - false
   * 9 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I86 Branch 35 IF_ACMPNE L288 - false
   * 10 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>()V: root-Branch
   * 11 org.apache.commons.collections4.comparators.FixedOrderComparator.hashCode()I: I11 Branch 21 IFNONNULL L259 - true
   * 12 org.apache.commons.collections4.comparators.FixedOrderComparator.hashCode()I: I28 Branch 22 IFNONNULL L260 - true
   * 13 org.apache.commons.collections4.comparators.FixedOrderComparator.hashCode()I: I54 Branch 23 IFEQ L262 - true
   */

  @Test
  public void test13()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(889,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test13");
      FixedOrderComparator<Integer>[] fixedOrderComparatorArray0 = (FixedOrderComparator<Integer>[]) Array.newInstance(FixedOrderComparator.class, 7);
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>();
      FixedOrderComparator<Integer> fixedOrderComparator1 = new FixedOrderComparator<Integer>();
      fixedOrderComparatorArray0[3] = fixedOrderComparator1;
      fixedOrderComparatorArray0[5] = fixedOrderComparator0;
      FixedOrderComparator<FixedOrderComparator<Integer>> fixedOrderComparator2 = new FixedOrderComparator<FixedOrderComparator<Integer>>(fixedOrderComparatorArray0);
      assertEquals(FixedOrderComparator.UnknownObjectBehavior.EXCEPTION, fixedOrderComparator2.getUnknownObjectBehavior());
  }

  //Test case number: 14
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I13 Branch 25 IF_ACMPNE L283 - false
   */

  @Test
  public void test14()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(890,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test14");
      Integer[] integerArray0 = new Integer[11];
      FixedOrderComparator<Integer> fixedOrderComparator0 = new FixedOrderComparator<Integer>(integerArray0);
      boolean boolean0 = fixedOrderComparator0.equals((Object) null);
      assertEquals(false, boolean0);
  }

  //Test case number: 15
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I52 Branch 29 IFEQ L288 - true
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I76 Branch 33 IF_ICMPNE L288 - true
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I71 Branch 32 IF_ACMPNE L288 - false
   */

  @Test
  public void test15()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(891,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test15");
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>((List<String>) linkedList0);
      Integer[] integerArray0 = new Integer[6];
      FixedOrderComparator<Integer> fixedOrderComparator1 = new FixedOrderComparator<Integer>(integerArray0);
      boolean boolean0 = fixedOrderComparator0.equals((Object) fixedOrderComparator1);
      assertEquals(false, fixedOrderComparator0.isLocked());
      assertEquals(false, boolean0);
  }

  //Test case number: 16
  /*
   * 16 covered goals:
   * 1 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I71 Branch 32 IF_ACMPNE L288 - true
   * 2 org.apache.commons.collections4.comparators.FixedOrderComparator.isLocked()Z: root-Branch
   * 3 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>(Ljava/util/List;)V: I29 Branch 3 IFNONNULL L113 - true
   * 4 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>(Ljava/util/List;)V: I45 Branch 4 IFEQ L116 - true
   * 5 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>([Ljava/lang/Object;)V: I29 Branch 1 IFNONNULL L94 - true
   * 6 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>([Ljava/lang/Object;)V: I51 Branch 2 IF_ICMPGE L97 - true
   * 7 org.apache.commons.collections4.comparators.FixedOrderComparator.<init>([Ljava/lang/Object;)V: I51 Branch 2 IF_ICMPGE L97 - false
   * 8 org.apache.commons.collections4.comparators.FixedOrderComparator.checkLocked()V: I4 Branch 5 IFEQ L140 - true
   * 9 org.apache.commons.collections4.comparators.FixedOrderComparator.setUnknownObjectBehavior(Lorg/apache/commons/collections4/comparators/FixedOrderComparator$UnknownObjectBehavior;)V: I7 Branch 6 IFNONNULL L164 - true
   * 10 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I4 Branch 24 IF_ACMPNE L280 - true
   * 11 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I13 Branch 25 IF_ACMPNE L283 - true
   * 12 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I25 Branch 26 IFEQ L286 - false
   * 13 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I36 Branch 27 IF_ACMPNE L288 - true
   * 14 org.apache.commons.collections4.comparators.FixedOrderComparator.equals(Ljava/lang/Object;)Z: I52 Branch 29 IFEQ L288 - true
   * 15 org.apache.commons.collections4.comparators.FixedOrderComparator.add(Ljava/lang/Object;)Z: I23 Branch 7 IFNONNULL L185 - true
   * 16 org.apache.commons.collections4.comparators.FixedOrderComparator.add(Ljava/lang/Object;)Z: I23 Branch 7 IFNONNULL L185 - false
   */

  @Test
  public void test16()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(892,"org.apache.commons.collections4.comparators.FixedOrderComparatorEvoSuiteTest.test16");
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FixedOrderComparator<String> fixedOrderComparator0 = new FixedOrderComparator<String>((List<String>) linkedList0);
      Integer[] integerArray0 = new Integer[6];
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      assertEquals(FixedOrderComparator.UnknownObjectBehavior.BEFORE, fixedOrderComparator0.getUnknownObjectBehavior());
      
      FixedOrderComparator<Integer> fixedOrderComparator1 = new FixedOrderComparator<Integer>(integerArray0);
      boolean boolean0 = fixedOrderComparator0.equals((Object) fixedOrderComparator1);
      assertEquals(false, boolean0);
  }
}
