/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.trie;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.trie.KeyAnalyzer;
import org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer;
import org.junit.BeforeClass;

public class KeyAnalyzerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.isOutOfBoundsIndex(I)Z: I4 Branch 1 IF_ICMPNE L58 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1245,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test0");
      boolean boolean0 = KeyAnalyzer.isOutOfBoundsIndex((-1260));
      assertEquals(false, boolean0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.isOutOfBoundsIndex(I)Z: I4 Branch 1 IF_ICMPNE L58 - false
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1246,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test1");
      boolean boolean0 = KeyAnalyzer.isOutOfBoundsIndex((-3));
      assertEquals(true, boolean0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.isEqualBitKey(I)Z: I4 Branch 2 IF_ICMPNE L65 - true
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1249,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test2");
      boolean boolean0 = KeyAnalyzer.isEqualBitKey((-1260));
      assertEquals(false, boolean0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.isEqualBitKey(I)Z: I4 Branch 2 IF_ICMPNE L65 - false
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1250,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test3");
      boolean boolean0 = KeyAnalyzer.isEqualBitKey((-2));
      assertEquals(true, boolean0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.isNullBitKey(I)Z: I4 Branch 3 IF_ICMPNE L72 - true
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1251,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test4");
      boolean boolean0 = KeyAnalyzer.isNullBitKey(848);
      assertEquals(false, boolean0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.isNullBitKey(I)Z: I4 Branch 3 IF_ICMPNE L72 - false
   */

  @Test
  public void test5()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1252,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test5");
      boolean boolean0 = KeyAnalyzer.isNullBitKey((-1));
      assertEquals(true, boolean0);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.isValidBitIndex(I)Z: I3 Branch 4 IFLT L80 - true
   */

  @Test
  public void test6()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1253,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test6");
      boolean boolean0 = KeyAnalyzer.isValidBitIndex((-2));
      assertEquals(false, boolean0);
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.isValidBitIndex(I)Z: I3 Branch 4 IFLT L80 - false
   */

  @Test
  public void test7()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1254,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test7");
      boolean boolean0 = KeyAnalyzer.isValidBitIndex(848);
      assertEquals(true, boolean0);
  }

  //Test case number: 8
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I3 Branch 5 IFNONNULL L139 - true
   * 2 org.apache.commons.collections4.trie.KeyAnalyzer.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I17 Branch 7 IFNONNULL L141 - true
   * 3 org.apache.commons.collections4.trie.KeyAnalyzer.<init>()V: root-Branch
   */

  @Test
  public void test8()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1255,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test8");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.compare("XE44Cq\"Ww<<j sxT:", "XE44Cq\"Ww<<j sxT:");
      assertEquals(0, int0);
  }

  //Test case number: 9
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I3 Branch 5 IFNONNULL L139 - false
   * 2 org.apache.commons.collections4.trie.KeyAnalyzer.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 6 IFNONNULL L140 - true
   */

  @Test
  public void test9()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1256,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test9");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.compare((String) null, "XE44Cq\"Ww<<j sxT:");
      assertEquals((-1), int0);
  }

  //Test case number: 10
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I7 Branch 6 IFNONNULL L140 - false
   * 2 org.apache.commons.collections4.trie.KeyAnalyzer.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I3 Branch 5 IFNONNULL L139 - false
   */

  @Test
  public void test10()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1247,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test10");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.compare((String) null, (String) null);
      assertEquals(0, int0);
  }

  //Test case number: 11
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.trie.KeyAnalyzer.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I17 Branch 7 IFNONNULL L141 - false
   * 2 org.apache.commons.collections4.trie.KeyAnalyzer.<init>()V: root-Branch
   * 3 org.apache.commons.collections4.trie.KeyAnalyzer.compare(Ljava/lang/Object;Ljava/lang/Object;)I: I3 Branch 5 IFNONNULL L139 - true
   */

  @Test
  public void test11()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1248,"org.apache.commons.collections4.trie.KeyAnalyzerEvoSuiteTest.test11");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.compare("XE44Cq\"Ww<<j sxT:", (String) null);
      assertEquals(1, int0);
  }
}
