/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.collection;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import org.apache.commons.collections4.collection.UnmodifiableCollection;
import org.apache.commons.collections4.list.UnmodifiableList;
import org.junit.BeforeClass;

public class UnmodifiableCollectionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.collection.UnmodifiableCollection.unmodifiableCollection(Ljava/util/Collection;)Ljava/util/Collection;: I4 Branch 1 IFEQ L55 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1007,"org.apache.commons.collections4.collection.UnmodifiableCollectionEvoSuiteTest.test0");
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Collection<Integer> collection0 = UnmodifiableCollection.unmodifiableCollection((Collection<Integer>) linkedList0);
      assertEquals(0, collection0.size());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.collection.UnmodifiableCollection.unmodifiableCollection(Ljava/util/Collection;)Ljava/util/Collection;: I4 Branch 1 IFEQ L55 - false
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1008,"org.apache.commons.collections4.collection.UnmodifiableCollectionEvoSuiteTest.test1");
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      UnmodifiableList<Integer> unmodifiableList0 = new UnmodifiableList<Integer>((List<Integer>) linkedList0);
      Collection<Integer> collection0 = UnmodifiableCollection.unmodifiableCollection((Collection<Integer>) unmodifiableList0);
      assertEquals(true, collection0.isEmpty());
  }
}
