/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.collection;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Collection;
import java.util.LinkedList;
import org.apache.commons.collections4.BoundedCollection;
import org.apache.commons.collections4.MultiMap;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.collection.IndexedCollection;
import org.apache.commons.collections4.collection.TransformedCollection;
import org.apache.commons.collections4.collection.UnmodifiableBoundedCollection;
import org.apache.commons.collections4.map.MultiValueMap;
import org.apache.commons.collections4.queue.CircularFifoQueue;
import org.junit.BeforeClass;

public class UnmodifiableBoundedCollectionEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Lorg/apache/commons/collections4/BoundedCollection;)Lorg/apache/commons/collections4/BoundedCollection;: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1003,"org.apache.commons.collections4.collection.UnmodifiableBoundedCollectionEvoSuiteTest.test0");
      try {
        UnmodifiableBoundedCollection.unmodifiableBoundedCollection((BoundedCollection<TransformedCollection<Object>>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Collection must not be null
         //
      }
  }

  //Test case number: 1
  /*
   * 6 covered goals:
   * 1 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I3 Branch 1 IFNONNULL L75 - true
   * 2 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I18 Branch 2 IF_ICMPGE L80 - false
   * 3 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I23 Branch 3 IFEQ L81 - true
   * 4 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I23 Branch 3 IFEQ L81 - false
   * 5 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I31 Branch 4 IFEQ L84 - false
   * 6 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I58 Branch 6 IFNE L91 - true
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1004,"org.apache.commons.collections4.collection.UnmodifiableBoundedCollectionEvoSuiteTest.test1");
      CircularFifoQueue<UnmodifiableBoundedCollection<String>> circularFifoQueue0 = new CircularFifoQueue<UnmodifiableBoundedCollection<String>>();
      MultiValueMap<Integer, UnmodifiableBoundedCollection<String>> multiValueMap0 = new MultiValueMap<Integer, UnmodifiableBoundedCollection<String>>();
      IndexedCollection<Integer, UnmodifiableBoundedCollection<String>> indexedCollection0 = new IndexedCollection<Integer, UnmodifiableBoundedCollection<String>>((Collection<UnmodifiableBoundedCollection<String>>) circularFifoQueue0, (Transformer<UnmodifiableBoundedCollection<String>, Integer>) null, (MultiMap<Integer, UnmodifiableBoundedCollection<String>>) multiValueMap0, true);
      BoundedCollection<Object> boundedCollection0 = UnmodifiableBoundedCollection.unmodifiableBoundedCollection((Collection<?>) indexedCollection0);
      assertEquals(true, boundedCollection0.isEmpty());
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I3 Branch 1 IFNONNULL L75 - false
   */

  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1005,"org.apache.commons.collections4.collection.UnmodifiableBoundedCollectionEvoSuiteTest.test2");
      try {
        UnmodifiableBoundedCollection.unmodifiableBoundedCollection((Collection<?>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The collection must not be null
         //
      }
  }

  //Test case number: 3
  /*
   * 7 covered goals:
   * 1 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I18 Branch 2 IF_ICMPGE L80 - true
   * 2 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I31 Branch 4 IFEQ L84 - true
   * 3 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I43 Branch 5 IFEQ L86 - true
   * 4 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I58 Branch 6 IFNE L91 - false
   * 5 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I3 Branch 1 IFNONNULL L75 - true
   * 6 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I18 Branch 2 IF_ICMPGE L80 - false
   * 7 org.apache.commons.collections4.collection.UnmodifiableBoundedCollection.unmodifiableBoundedCollection(Ljava/util/Collection;)Lorg/apache/commons/collections4/BoundedCollection;: I23 Branch 3 IFEQ L81 - true
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1006,"org.apache.commons.collections4.collection.UnmodifiableBoundedCollectionEvoSuiteTest.test3");
      LinkedList<IndexedCollection<Object, Object>> linkedList0 = new LinkedList<IndexedCollection<Object, Object>>();
      // Undeclared exception!
      try {
        UnmodifiableBoundedCollection.unmodifiableBoundedCollection((Collection<?>) linkedList0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The collection is not a bounded collection
         //
      }
  }
}
