/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Array;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedList;
import org.apache.commons.collections4.ComparatorUtils;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.functors.ConstantTransformer;
import org.apache.commons.collections4.functors.InvokerTransformer;
import org.junit.BeforeClass;

public class ComparatorUtilsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.ComparatorUtils.reversedComparator(Ljava/util/Comparator;)Ljava/util/Comparator;: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1303,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test0");
      Comparator<String>[] comparatorArray0 = (Comparator<String>[]) Array.newInstance(Comparator.class, 5);
      Comparator<String> comparator0 = ComparatorUtils.reversedComparator((Comparator<String>) null);
      assertNotNull(comparator0);
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.ComparatorUtils.chainedComparator([Ljava/util/Comparator;)Ljava/util/Comparator;: I28 Branch 2 IFNONNULL L82 - true
   * 2 org.apache.commons.collections4.ComparatorUtils.chainedComparator([Ljava/util/Comparator;)Ljava/util/Comparator;: I20 Branch 1 IF_ICMPGE L81 - false
   * 3 org.apache.commons.collections4.ComparatorUtils.chainedComparator([Ljava/util/Comparator;)Ljava/util/Comparator;: I28 Branch 2 IFNONNULL L82 - false
   * 4 org.apache.commons.collections4.ComparatorUtils.booleanComparator(Z)Ljava/util/Comparator;: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1304,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test1");
      Comparator<Boolean>[] comparatorArray0 = (Comparator<Boolean>[]) Array.newInstance(Comparator.class, 4);
      Comparator<Boolean> comparator0 = ComparatorUtils.booleanComparator(false);
      comparatorArray0[0] = comparator0;
      // Undeclared exception!
      try {
        ComparatorUtils.chainedComparator(comparatorArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Comparator cannot be null
         //
      }
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.ComparatorUtils.nullLowComparator(Ljava/util/Comparator;)Ljava/util/Comparator;: I3 Branch 3 IFNONNULL L153 - true
   * 2 org.apache.commons.collections4.ComparatorUtils.booleanComparator(Z)Ljava/util/Comparator;: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1309,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test2");
      Comparator<Boolean> comparator0 = ComparatorUtils.booleanComparator(false);
      Comparator<Boolean> comparator1 = ComparatorUtils.nullLowComparator(comparator0);
      assertFalse(comparator1.equals(comparator0));
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.ComparatorUtils.nullLowComparator(Ljava/util/Comparator;)Ljava/util/Comparator;: I3 Branch 3 IFNONNULL L153 - false
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1310,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test3");
      Comparator<Boolean>[] comparatorArray0 = (Comparator<Boolean>[]) Array.newInstance(Comparator.class, 5);
      Comparator<Boolean> comparator0 = ComparatorUtils.nullLowComparator((Comparator<Boolean>) null);
      assertNotNull(comparator0);
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.ComparatorUtils.nullHighComparator(Ljava/util/Comparator;)Ljava/util/Comparator;: I3 Branch 4 IFNONNULL L173 - true
   * 2 org.apache.commons.collections4.ComparatorUtils.naturalComparator()Ljava/util/Comparator;: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1311,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test4");
      Comparator<Boolean> comparator0 = ComparatorUtils.naturalComparator();
      Comparator<Boolean> comparator1 = ComparatorUtils.nullHighComparator(comparator0);
      assertFalse(comparator1.equals(comparator0));
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.ComparatorUtils.nullHighComparator(Ljava/util/Comparator;)Ljava/util/Comparator;: I3 Branch 4 IFNONNULL L173 - false
   */

  @Test
  public void test5()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1312,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test5");
      Comparator<Boolean> comparator0 = ComparatorUtils.nullHighComparator((Comparator<Boolean>) null);
      assertNotNull(comparator0);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.ComparatorUtils.transformedComparator(Ljava/util/Comparator;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Comparator;: I3 Branch 5 IFNONNULL L197 - true
   */

  @Test
  public void test6()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1313,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test6");
      Comparator<String> comparator0 = ComparatorUtils.naturalComparator();
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 9);
      InvokerTransformer<Boolean, String> invokerTransformer0 = new InvokerTransformer<Boolean, String>("", (Class<?>[]) classArray0, (Object[]) classArray0);
      Comparator<Boolean> comparator1 = ComparatorUtils.transformedComparator(comparator0, (Transformer<? super Boolean, ? extends String>) invokerTransformer0);
      assertNotNull(comparator1);
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.ComparatorUtils.transformedComparator(Ljava/util/Comparator;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Comparator;: I3 Branch 5 IFNONNULL L197 - false
   */

  @Test
  public void test7()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1314,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test7");
      Integer integer0 = new Integer(0);
      ConstantTransformer<Object, Integer> constantTransformer0 = new ConstantTransformer<Object, Integer>(integer0);
      Comparator<String> comparator0 = ComparatorUtils.transformedComparator((Comparator<Integer>) null, (Transformer<? super String, ? extends Integer>) constantTransformer0);
      assertNotNull(comparator0);
  }

  //Test case number: 8
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.ComparatorUtils.min(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I3 Branch 6 IFNONNULL L216 - true
   * 2 org.apache.commons.collections4.ComparatorUtils.min(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I18 Branch 7 IFGE L220 - true
   */

  @Test
  public void test8()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1315,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test8");
      Comparator<String> comparator0 = ComparatorUtils.naturalComparator();
      String string0 = ComparatorUtils.min("':", "':", comparator0);
      assertEquals("':", string0);
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.ComparatorUtils.min(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I3 Branch 6 IFNONNULL L216 - false
   */

  @Test
  public void test9()  throws Throwable  {
      // Undeclared exception!
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1316,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test9");
      try {
        ComparatorUtils.min((Boolean) null, (Boolean) null, (Comparator<Boolean>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 10
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.ComparatorUtils.min(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I18 Branch 7 IFGE L220 - false
   * 2 org.apache.commons.collections4.ComparatorUtils.min(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I3 Branch 6 IFNONNULL L216 - true
   */

  @Test
  public void test10()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1305,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test10");
      Comparator<String> comparator0 = ComparatorUtils.naturalComparator();
      assertNotNull(comparator0);
      
      String string0 = ComparatorUtils.min("':", "Compaator cannot b null", comparator0);
      assertEquals("':", string0);
  }

  //Test case number: 11
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.ComparatorUtils.max(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I3 Branch 8 IFNONNULL L236 - true
   * 2 org.apache.commons.collections4.ComparatorUtils.chainedComparator(Ljava/util/Collection;)Ljava/util/Comparator;: root-Branch
   * 3 org.apache.commons.collections4.ComparatorUtils.chainedComparator([Ljava/util/Comparator;)Ljava/util/Comparator;: I20 Branch 1 IF_ICMPGE L81 - true
   */

  @Test
  public void test11()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1306,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test11");
      LinkedList<Comparator<String>> linkedList0 = new LinkedList<Comparator<String>>();
      Comparator<String> comparator0 = ComparatorUtils.chainedComparator((Collection<Comparator<String>>) linkedList0);
      // Undeclared exception!
      try {
        ComparatorUtils.max("V", "V", comparator0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // ComparatorChains must contain at least one Comparator
         //
      }
  }

  //Test case number: 12
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.ComparatorUtils.max(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I3 Branch 8 IFNONNULL L236 - false
   * 2 org.apache.commons.collections4.ComparatorUtils.max(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I18 Branch 9 IFLE L240 - true
   */

  @Test
  public void test12()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1307,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test12");
      Boolean boolean0 = Boolean.FALSE;
      Boolean boolean1 = ComparatorUtils.max(boolean0, boolean0, (Comparator<Boolean>) null);
      assertEquals(false, (boolean)boolean1);
  }

  //Test case number: 13
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.ComparatorUtils.max(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I18 Branch 9 IFLE L240 - false
   * 2 org.apache.commons.collections4.ComparatorUtils.naturalComparator()Ljava/util/Comparator;: root-Branch
   * 3 org.apache.commons.collections4.ComparatorUtils.max(Ljava/lang/Object;Ljava/lang/Object;Ljava/util/Comparator;)Ljava/lang/Object;: I3 Branch 8 IFNONNULL L236 - true
   */

  @Test
  public void test13()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1308,"org.apache.commons.collections4.ComparatorUtilsEvoSuiteTest.test13");
      Comparator<Boolean> comparator0 = ComparatorUtils.naturalComparator();
      assertNotNull(comparator0);
      
      Boolean boolean0 = Boolean.TRUE;
      Boolean boolean1 = ComparatorUtils.max(boolean0, (Boolean) false, comparator0);
      assertEquals(true, (boolean)boolean1);
  }
}
