/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Enumeration;
import java.util.List;
import java.util.StringTokenizer;
import org.apache.commons.collections4.EnumerationUtils;
import org.junit.BeforeClass;

public class EnumerationUtilsEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.EnumerationUtils.toList(Ljava/util/Enumeration;)Ljava/util/List;: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1317,"org.apache.commons.collections4.EnumerationUtilsEvoSuiteTest.test0");
      try {
        EnumerationUtils.toList((Enumeration<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  }
