/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.queue;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayDeque;
import java.util.Queue;
import org.apache.commons.collections4.bag.UnmodifiableSortedBag;
import org.apache.commons.collections4.queue.UnmodifiableQueue;
import org.junit.BeforeClass;

public class UnmodifiableQueueEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.queue.UnmodifiableQueue.unmodifiableQueue(Ljava/util/Queue;)Ljava/util/Queue;: I4 Branch 1 IFEQ L56 - false
   * 2 org.apache.commons.collections4.queue.UnmodifiableQueue.unmodifiableQueue(Ljava/util/Queue;)Ljava/util/Queue;: I4 Branch 1 IFEQ L56 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1146,"org.apache.commons.collections4.queue.UnmodifiableQueueEvoSuiteTest.test0");
      ArrayDeque<UnmodifiableSortedBag<Object>> arrayDeque0 = new ArrayDeque<UnmodifiableSortedBag<Object>>();
      Queue<UnmodifiableSortedBag<Object>> queue0 = UnmodifiableQueue.unmodifiableQueue((Queue<UnmodifiableSortedBag<Object>>) arrayDeque0);
      Queue<UnmodifiableSortedBag<Object>> queue1 = UnmodifiableQueue.unmodifiableQueue(queue0);
      assertSame(queue1, queue0);
  }
}
