/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.embedder;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.util.LinkedList;
import java.util.List;
import java.util.Properties;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.LinkedBlockingDeque;
import java.util.concurrent.RejectedExecutionHandler;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.configuration.ParanamerConfiguration;
import org.jbehave.core.configuration.PropertyBasedConfiguration;
import org.jbehave.core.embedder.EmbedderControls;
import org.jbehave.core.embedder.EmbedderMonitor;
import org.jbehave.core.embedder.EmbedderMonitorDecorator;
import org.jbehave.core.embedder.MetaFilter;
import org.jbehave.core.embedder.NullEmbedderMonitor;
import org.jbehave.core.embedder.PrintStreamEmbedderMonitor;
import org.jbehave.core.embedder.ReportingFailuresEmbedderMonitor;
import org.jbehave.core.embedder.SilentEmbedderMonitor;
import org.jbehave.core.failures.BatchFailures;
import org.jbehave.core.failures.UUIDExceptionWrapper;
import org.jbehave.core.model.ExamplesTable;
import org.jbehave.core.model.Meta;
import org.jbehave.core.model.Narrative;
import org.jbehave.core.model.OutcomesTable;
import org.jbehave.core.model.Story;
import org.jbehave.core.model.StoryDuration;
import org.jbehave.core.model.StoryMap;
import org.jbehave.core.model.StoryMaps;
import org.jbehave.core.reporters.ReportsCount;
import org.jbehave.core.steps.ParameterConverters;


public class EmbedderMonitorDecoratorEvoSuiteTest {


  //Test case number: 0
  /*
   * 4 covered goals:
   * 1 org.jbehave.core.embedder.EmbedderMonitorDecorator.<init>(Lorg/jbehave/core/embedder/EmbedderMonitor;)V: root-Branch
   * 2 org.jbehave.core.embedder.EmbedderMonitorDecorator.usingControls(Lorg/jbehave/core/embedder/EmbedderControls;)V: root-Branch
   * 3 org.jbehave.core.embedder.EmbedderMonitorDecorator.metaNotAllowed(Lorg/jbehave/core/model/Meta;Lorg/jbehave/core/embedder/MetaFilter;)V: root-Branch
   * 4 org.jbehave.core.embedder.EmbedderMonitorDecorator.mappingStory(Ljava/lang/String;Ljava/util/List;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      PrintStreamEmbedderMonitor printStreamEmbedderMonitor0 = new PrintStreamEmbedderMonitor();
      EmbedderMonitorDecorator embedderMonitorDecorator0 = new EmbedderMonitorDecorator((EmbedderMonitor) printStreamEmbedderMonitor0);
      EmbedderControls embedderControls0 = new EmbedderControls();
      EmbedderControls embedderControls1 = embedderControls0.doVerboseFailures(true);
      embedderMonitorDecorator0.mappingStory("GivenStories", (List<String>) null);
      EmbedderControls embedderControls2 = embedderControls1.doIgnoreFailureInStories(false);
      EmbedderControls embedderControls3 = embedderControls2.doIgnoreFailureInView(true);
      EmbedderControls embedderControls4 = embedderControls2.doVerboseFiltering(false);
      EmbedderControls embedderControls5 = embedderControls4.useStoryTimeoutInSecs((long) 1);
      EmbedderControls embedderControls6 = embedderControls5.doBatch(false);
      embedderMonitorDecorator0.usingControls(embedderControls6);
      EmbedderMonitorDecorator embedderMonitorDecorator1 = new EmbedderMonitorDecorator((EmbedderMonitor) null);
      String string0 = "{f%{}5T b66S";
      Story story0 = new Story("{f%{}5T b66S");
      StoryDuration storyDuration0 = new StoryDuration(1035L, 1035L);
      Meta meta0 = null;
      MetaFilter metaFilter0 = null;
      // Undeclared exception!
      try {
        embedderMonitorDecorator1.metaNotAllowed((Meta) null, (MetaFilter) null);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.embedder.EmbedderMonitorDecorator.metaNotAllowed(EmbedderMonitorDecorator.java:32)"/></ex>%%%
         */
      }
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.embedder.EmbedderMonitorDecorator.systemPropertySet(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * 2 org.jbehave.core.embedder.EmbedderMonitorDecorator.<init>(Lorg/jbehave/core/embedder/EmbedderMonitor;)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      EmbedderMonitorDecorator embedderMonitorDecorator0 = new EmbedderMonitorDecorator((EmbedderMonitor) null);
      // Undeclared exception!
      try {
        embedderMonitorDecorator0.systemPropertySet("xY[Rcby8K~hl", "xY[Rcby8K~hl");
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.embedder.EmbedderMonitorDecorator.systemPropertySet(EmbedderMonitorDecorator.java:120)"/></ex>%%%
         */
      }
  }

  //Test case number: 5
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.embedder.EmbedderMonitorDecorator.beforeOrAfterStoriesFailed()V: root-Branch
   * 2 org.jbehave.core.embedder.EmbedderMonitorDecorator.<init>(Lorg/jbehave/core/embedder/EmbedderMonitor;)V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      PrintStream printStream0 = null;
      ReportingFailuresEmbedderMonitor reportingFailuresEmbedderMonitor0 = new ReportingFailuresEmbedderMonitor((PrintStream) null);
      EmbedderMonitorDecorator embedderMonitorDecorator0 = new EmbedderMonitorDecorator((EmbedderMonitor) reportingFailuresEmbedderMonitor0);
      // Undeclared exception!
      try {
        embedderMonitorDecorator0.beforeOrAfterStoriesFailed();
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="17"/><causeDepth val="0"/><source val="org.jbehave.core.reporters.Format.println(Format.java:108)"/></ex>%%%
         */
      }
  }

  //Test case number: 6
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.embedder.EmbedderMonitorDecorator.reportsViewGenerated(Lorg/jbehave/core/reporters/ReportsCount;)V: root-Branch
   * 2 org.jbehave.core.embedder.EmbedderMonitorDecorator.<init>(Lorg/jbehave/core/embedder/EmbedderMonitor;)V: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      ReportingFailuresEmbedderMonitor reportingFailuresEmbedderMonitor0 = new ReportingFailuresEmbedderMonitor();
      EmbedderMonitorDecorator embedderMonitorDecorator0 = new EmbedderMonitorDecorator((EmbedderMonitor) reportingFailuresEmbedderMonitor0);
      int int0 = 0;
      reportingFailuresEmbedderMonitor0.reportsViewNotGenerated();
      ReportsCount reportsCount0 = new ReportsCount(0, 966, 0, 966, 966, 966, 966, (-1));
      embedderMonitorDecorator0.reportsViewGenerated(reportsCount0);
      EmbedderMonitorDecorator embedderMonitorDecorator1 = new EmbedderMonitorDecorator((EmbedderMonitor) reportingFailuresEmbedderMonitor0);
      String string0 = "SDIg";
      // Undeclared exception!
      try {
        File.createTempFile("SDIg", "SDIg");
      }catch(SecurityException e) {
        /*
         * Security manager blocks (java.io.FilePermission /tmp/SDIg7765269710387596651SDIg write)
         * java.lang.Thread.getStackTrace(Thread.java:1495)
         * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
         * java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
         * java.io.File.checkAndCreate(File.java:1709)
         * java.io.File.createTempFile0(File.java:1738)
         * java.io.File.createTempFile(File.java:1850)
         * sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
         * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         * java.lang.reflect.Method.invoke(Method.java:616)
         * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
         * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
         * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
         * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
         * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:1)
         * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
         * java.util.concurrent.FutureTask.run(FutureTask.java:166)
         * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
         * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
         * java.lang.Thread.run(Thread.java:679)
         */
        /*
      %%%<ex><className val="SecurityException"/><stackDepth val="18"/><causeDepth val="0"/><source val="org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:307)"/></ex>%%%
         */
      }
  }

  //Test case number: 8
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.embedder.EmbedderMonitorDecorator.embeddableNotConfigurable(Ljava/lang/String;)V: root-Branch
   * 2 org.jbehave.core.embedder.EmbedderMonitorDecorator.<init>(Lorg/jbehave/core/embedder/EmbedderMonitor;)V: root-Branch
   */
  @Test
  public void test8()  throws Throwable  {
      EmbedderMonitor embedderMonitor0 = null;
      EmbedderMonitorDecorator embedderMonitorDecorator0 = new EmbedderMonitorDecorator((EmbedderMonitor) null);
      // Undeclared exception!
      try {
        embedderMonitorDecorator0.embeddableNotConfigurable("K9HukpA)I:7zI8K2|P/");
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.embedder.EmbedderMonitorDecorator.embeddableNotConfigurable(EmbedderMonitorDecorator.java:24)"/></ex>%%%
         */
      }
  }

  //Test case number: 9
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.embedder.EmbedderMonitorDecorator.<init>(Lorg/jbehave/core/embedder/EmbedderMonitor;)V: root-Branch
   * 2 org.jbehave.core.embedder.EmbedderMonitorDecorator.storiesNotAllowed(Ljava/util/List;Lorg/jbehave/core/embedder/MetaFilter;)V: root-Branch
   */
  @Test
  public void test9()  throws Throwable  {
      ReportingFailuresEmbedderMonitor reportingFailuresEmbedderMonitor0 = new ReportingFailuresEmbedderMonitor();
      EmbedderMonitorDecorator embedderMonitorDecorator0 = new EmbedderMonitorDecorator((EmbedderMonitor) reportingFailuresEmbedderMonitor0);
      MetaFilter metaFilter0 = MetaFilter.EMPTY;
      // Undeclared exception!
      try {
        embedderMonitorDecorator0.storiesNotAllowed((List<Story>) null, metaFilter0);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="16"/><causeDepth val="0"/><source val="org.jbehave.core.embedder.PrintStreamEmbedderMonitor.storiesNotAllowed(PrintStreamEmbedderMonitor.java:63)"/></ex>%%%
         */
      }
  }
}
