/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.embedder;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jbehave.core.embedder.FilteredStory;
import org.jbehave.core.embedder.MetaFilter;
import org.jbehave.core.embedder.StoryControls;
import org.jbehave.core.model.Story;


public class FilteredStoryEvoSuiteTest {


  //Test case number: 0  @Test
  public void test0()  throws Throwable  {
      StoryControls storyControls0 = new StoryControls();
      FilteredStory filteredStory0 = null;
      try {
        filteredStory0 = new FilteredStory((MetaFilter) null, (Story) null, storyControls0);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.embedder.FilteredStory.&lt;init&gt;(FilteredStory.java:12)"/></ex>%%%
         */
      }
  }
}
