/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.embedder;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jbehave.core.embedder.PropertyBasedEmbedderControls;
import org.jbehave.core.i18n.LocalizedKeywords;


public class PropertyBasedEmbedderControlsEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.jbehave.core.embedder.PropertyBasedEmbedderControls.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      PropertyBasedEmbedderControls propertyBasedEmbedderControls0 = null;
      try {
        propertyBasedEmbedderControls0 = new PropertyBasedEmbedderControls();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@13e5454
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="27"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }
}
