/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.embedder;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.List;
import java.util.Map;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.PriorityBlockingQueue;
import java.util.concurrent.RejectedExecutionHandler;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import org.jbehave.core.configuration.Configuration;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.configuration.ParanamerConfiguration;
import org.jbehave.core.configuration.PropertyBasedConfiguration;
import org.jbehave.core.embedder.EmbedderControls;
import org.jbehave.core.embedder.EmbedderMonitor;
import org.jbehave.core.embedder.MetaFilter;
import org.jbehave.core.embedder.NullEmbedderMonitor;
import org.jbehave.core.embedder.ReportingFailuresEmbedderMonitor;
import org.jbehave.core.embedder.StoryManager;
import org.jbehave.core.embedder.StoryRunner;
import org.jbehave.core.failures.BatchFailures;
import org.jbehave.core.failures.UUIDExceptionWrapper;
import org.jbehave.core.i18n.LocalizedKeywords;
import org.jbehave.core.model.OutcomesTable;
import org.jbehave.core.model.Scenario;
import org.jbehave.core.model.Story;
import org.jbehave.core.reporters.ANSIConsoleOutput;
import org.jbehave.core.reporters.StoryReporter;
import org.jbehave.core.steps.CandidateSteps;
import org.jbehave.core.steps.InjectableStepsFactory;
import org.jbehave.core.steps.InstanceStepsFactory;
import org.jbehave.core.steps.ProvidedStepsFactory;
import org.jbehave.core.steps.StepType;


public class StoryManagerEvoSuiteTest {


  //Test case number: 0  @Test
  public void test0()  throws Throwable  {
      Story story0 = null;
      int int0 = (-1049);
      ThreadPoolExecutor.DiscardPolicy threadPoolExecutor_DiscardPolicy0 = new ThreadPoolExecutor.DiscardPolicy();
      ScheduledThreadPoolExecutor scheduledThreadPoolExecutor0 = null;
      try {
        scheduledThreadPoolExecutor0 = new ScheduledThreadPoolExecutor((-1049), (RejectedExecutionHandler) threadPoolExecutor_DiscardPolicy0);
      }catch(IllegalArgumentException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="IllegalArgumentException"/><stackDepth val="17"/><causeDepth val="0"/><source val="java.util.concurrent.ThreadPoolExecutor.&lt;init&gt;(ThreadPoolExecutor.java:1311)"/></ex>%%%
         */
      }
  }

  //Test case number: 2  @Test
  public void test2()  throws Throwable  {
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@1964fe8
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="24"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 3
  /*
   * 4 covered goals:
   * 1 org.jbehave.core.embedder.StoryManager$StoryExecutionFailed.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V: root-Branch
   * 2 org.jbehave.core.embedder.StoryManager$ThrowableStory.<init>(Lorg/jbehave/core/model/Story;Ljava/lang/Throwable;)V: root-Branch
   * 3 org.jbehave.core.embedder.StoryManager$ThrowableStory.getStory()Lorg/jbehave/core/model/Story;: root-Branch
   * 4 org.jbehave.core.embedder.StoryManager$ThrowableStory.getThrowable()Ljava/lang/Throwable;: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      List<String> list0 = keywords0.outcomeFields();
      OutcomesTable outcomesTable0 = new OutcomesTable(keywords0, "byQV96");
      UUIDExceptionWrapper uUIDExceptionWrapper0 = outcomesTable0.failureCause();
      StoryManager.ThrowableStory storyManager_ThrowableStory0 = new StoryManager.ThrowableStory((Story) null, (Throwable) null);
      Story story0 = storyManager_ThrowableStory0.getStory();
      StepType stepType0 = StepType.THEN;
      String[] stringArray0 = keywords0.startingWordsFor(stepType0);
      StoryManager.ThrowableStory storyManager_ThrowableStory1 = new StoryManager.ThrowableStory((Story) null, (Throwable) null);
      List<OutcomesTable.Outcome<?>> list1 = outcomesTable0.getOutcomes();
      Throwable throwable0 = storyManager_ThrowableStory0.getThrowable();
      Throwable throwable1 = new Throwable((Throwable) null);
      Map<String, String> map0 = Keywords.defaultKeywords();
      StoryManager.StoryExecutionFailed storyManager_StoryExecutionFailed0 = new StoryManager.StoryExecutionFailed("byQV96", throwable1);
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@1964fe8
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="24"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.embedder.StoryManager.<init>(Lorg/jbehave/core/configuration/Configuration;Lorg/jbehave/core/embedder/EmbedderControls;Lorg/jbehave/core/embedder/EmbedderMonitor;Ljava/util/concurrent/ExecutorService;Lorg/jbehave/core/steps/InjectableStepsFactory;Lorg/jbehave/core/embedder/StoryRunner;)V: root-Branch
   * 2 org.jbehave.core.embedder.StoryManager.storyOfPath(Ljava/lang/String;)Lorg/jbehave/core/model/Story;: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      EmbedderControls embedderControls0 = new EmbedderControls();
      EmbedderControls embedderControls1 = embedderControls0.useThreads(1464);
      EmbedderControls embedderControls2 = embedderControls1.useStoryTimeoutInSecs((long) 1464);
      boolean boolean0 = true;
      EmbedderControls embedderControls3 = embedderControls2.doGenerateViewAfterStories(true);
      NullEmbedderMonitor nullEmbedderMonitor0 = new NullEmbedderMonitor();
      ProvidedStepsFactory providedStepsFactory0 = new ProvidedStepsFactory((List<CandidateSteps>) null);
      StoryRunner storyRunner0 = new StoryRunner();
      StoryManager storyManager0 = new StoryManager((Configuration) null, embedderControls3, (EmbedderMonitor) nullEmbedderMonitor0, (ExecutorService) null, (InjectableStepsFactory) providedStepsFactory0, storyRunner0);
      // Undeclared exception!
      try {
        storyManager0.storyOfPath("trusted_templates");
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="16"/><causeDepth val="0"/><source val="org.jbehave.core.embedder.StoryRunner.storyOfPath(StoryRunner.java:156)"/></ex>%%%
         */
      }
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.jbehave.core.embedder.StoryManager$StoryExecutionFailed.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      Throwable throwable0 = new Throwable("");
      StoryManager.StoryExecutionFailed storyManager_StoryExecutionFailed0 = new StoryManager.StoryExecutionFailed("", throwable0);
      // Undeclared exception!
      try {
        storyManager_StoryExecutionFailed0.initCause(throwable0);
      }catch(IllegalStateException e) {
        /*
         * Can't overwrite cause
         */
        /*
      %%%<ex><className val="IllegalStateException"/><stackDepth val="14"/><causeDepth val="0"/><source val="java.lang.Throwable.initCause(Throwable.java:337)"/></ex>%%%
         */
      }
  }
}
