/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.embedder;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import org.jbehave.core.embedder.MetaFilter;
import org.jbehave.core.embedder.StoryMapper;
import org.jbehave.core.model.Description;
import org.jbehave.core.model.GivenStories;
import org.jbehave.core.model.Meta;
import org.jbehave.core.model.Narrative;
import org.jbehave.core.model.Scenario;
import org.jbehave.core.model.Story;
import org.jbehave.core.model.StoryMap;
import org.jbehave.core.model.StoryMaps;


public class StoryMapperEvoSuiteTest {

}
