/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.configuration;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.io.Writer;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.testcase.CodeUnderTestException;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.steps.StepType;


public class KeywordsEvoSuiteTest {


  //Test case number: 0
  /*
   * 22 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.pending()Ljava/lang/String;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.startingWordsFor(Lorg/jbehave/core/steps/StepType;)[Ljava/lang/String;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;Ljava/util/Map;)V: root-Branch
   * 6 org.jbehave.core.configuration.Keywords.synonymsOf(Ljava/lang/String;)[Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.configuration.Keywords.<init>()V: root-Branch
   * 8 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 9 org.jbehave.core.configuration.Keywords.notPerformed()Ljava/lang/String;: root-Branch
   * 10 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 11 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 12 org.jbehave.core.configuration.Keywords.stepStartsWithWord(Ljava/lang/String;Ljava/lang/String;)Z: root-Branch
   * 13 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 14 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 15 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   * 16 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I23 Branch 5 IFEQ L380 - true
   * 17 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I34 Branch 6 IF_ICMPLT L379 - true
   * 18 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I58 Branch 7 IFEQ L385 - true
   * 19 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I69 Branch 8 IF_ICMPLT L384 - true
   * 20 org.jbehave.core.configuration.Keywords.startingWordFor(Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I11 Branch 15 IFNONNULL L420 - true
   * 21 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I34 Branch 6 IF_ICMPLT L379 - false
   * 22 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I69 Branch 8 IF_ICMPLT L384 - false
   */
  @Test
  public void test0()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      String string0 = keywords0.pending();
      String string1 = "=mfgho0eQ\\4";
      String string2 = keywords0.notPerformed();
      StepType stepType0 = StepType.WHEN;
      StepType stepType1 = StepType.WHEN;
      try {
        keywords0.startingWord("=mfgho0eQ\u0004", stepType1);
      }catch(Keywords.StartingWordNotFound e) {
        /*
         * No starting word found for step '=mfgho0eQ\u0004' of type 'WHEN' amongst '{IGNORABLE=!--, WHEN=When, AND=And, GIVEN=Given, THEN=Then}'
         */
        /*
      %%%<ex><className val="StartingWordNotFound"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.startingWord(Keywords.java:389)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 33 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.startingWordsByType()Ljava/util/Map;: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.examplesTableValueSeparator()Ljava/lang/String;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.stepWithoutStartingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords.dryRun()Ljava/lang/String;: root-Branch
   * 6 org.jbehave.core.configuration.Keywords.startingWordsFor(Lorg/jbehave/core/steps/StepType;)[Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 8 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;Ljava/util/Map;)V: root-Branch
   * 9 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 10 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 11 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 12 org.jbehave.core.configuration.Keywords.stepStartsWithWord(Ljava/lang/String;Ljava/lang/String;)Z: root-Branch
   * 13 org.jbehave.core.configuration.Keywords.no()Ljava/lang/String;: root-Branch
   * 14 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 15 org.jbehave.core.configuration.Keywords$KeywordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 16 org.jbehave.core.configuration.Keywords.failed()Ljava/lang/String;: root-Branch
   * 17 org.jbehave.core.configuration.Keywords.yes()Ljava/lang/String;: root-Branch
   * 18 org.jbehave.core.configuration.Keywords.synonymsOf(Ljava/lang/String;)[Ljava/lang/String;: root-Branch
   * 19 org.jbehave.core.configuration.Keywords.<init>()V: root-Branch
   * 20 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 21 org.jbehave.core.configuration.Keywords.scenario()Ljava/lang/String;: root-Branch
   * 22 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 23 org.jbehave.core.configuration.Keywords.storyCancelled()Ljava/lang/String;: root-Branch
   * 24 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   * 25 org.jbehave.core.configuration.Keywords.startingWords()[Ljava/lang/String;: I32 Branch 2 IFNE L344 - true
   * 26 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I23 Branch 5 IFEQ L380 - true
   * 27 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I34 Branch 6 IF_ICMPLT L379 - true
   * 28 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I58 Branch 7 IFEQ L385 - true
   * 29 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I69 Branch 8 IF_ICMPLT L384 - true
   * 30 org.jbehave.core.configuration.Keywords.startingWordFor(Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I11 Branch 15 IFNONNULL L420 - true
   * 31 org.jbehave.core.configuration.Keywords.startingWords()[Ljava/lang/String;: I32 Branch 2 IFNE L344 - false
   * 32 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I34 Branch 6 IF_ICMPLT L379 - false
   * 33 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I69 Branch 8 IF_ICMPLT L384 - false
   */
  @Test
  public void test1()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      Map<String, String> map0 = Keywords.defaultKeywords();
      StepType stepType0 = StepType.WHEN;
      String[] stringArray0 = keywords0.startingWordsFor(stepType0);
      String string0 = "ExamplesTableRow";
      Map<String, String> map1 = Keywords.defaultKeywords();
      Keywords keywords1 = new Keywords(map1);
      String string1 = keywords0.examplesTableValueSeparator();
      String string2 = keywords0.dryRun();
      String string3 = keywords0.yes();
      String[] stringArray1 = keywords0.startingWords();
      String string4 = keywords0.scenario();
      String string5 = keywords1.storyCancelled();
      Keywords.KeywordNotFound keywords_KeywordNotFound0 = new Keywords.KeywordNotFound("Scenario:", map0);
      Throwable throwable0 = keywords_KeywordNotFound0.getCause();
      Keywords keywords2 = new Keywords(map1);
      String string6 = keywords2.failed();
      // Undeclared exception!
      try {
        keywords_KeywordNotFound0.printStackTrace((PrintStream) null);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="15"/><causeDepth val="0"/><source val="java.lang.Throwable.printStackTrace(Throwable.java:477)"/></ex>%%%
         */
      }
  }

  //Test case number: 2
  /*
   * 33 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.startingWordsByType()Ljava/util/Map;: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.examplesTableValueSeparator()Ljava/lang/String;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.stepWithoutStartingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords.dryRun()Ljava/lang/String;: root-Branch
   * 6 org.jbehave.core.configuration.Keywords.startingWordsFor(Lorg/jbehave/core/steps/StepType;)[Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 8 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;Ljava/util/Map;)V: root-Branch
   * 9 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 10 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 11 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 12 org.jbehave.core.configuration.Keywords.stepStartsWithWord(Ljava/lang/String;Ljava/lang/String;)Z: root-Branch
   * 13 org.jbehave.core.configuration.Keywords.no()Ljava/lang/String;: root-Branch
   * 14 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 15 org.jbehave.core.configuration.Keywords$KeywordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 16 org.jbehave.core.configuration.Keywords.failed()Ljava/lang/String;: root-Branch
   * 17 org.jbehave.core.configuration.Keywords.yes()Ljava/lang/String;: root-Branch
   * 18 org.jbehave.core.configuration.Keywords.synonymsOf(Ljava/lang/String;)[Ljava/lang/String;: root-Branch
   * 19 org.jbehave.core.configuration.Keywords.<init>()V: root-Branch
   * 20 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 21 org.jbehave.core.configuration.Keywords.scenario()Ljava/lang/String;: root-Branch
   * 22 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 23 org.jbehave.core.configuration.Keywords.storyCancelled()Ljava/lang/String;: root-Branch
   * 24 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   * 25 org.jbehave.core.configuration.Keywords.startingWords()[Ljava/lang/String;: I32 Branch 2 IFNE L344 - true
   * 26 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I23 Branch 5 IFEQ L380 - true
   * 27 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I34 Branch 6 IF_ICMPLT L379 - true
   * 28 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I58 Branch 7 IFEQ L385 - true
   * 29 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I69 Branch 8 IF_ICMPLT L384 - true
   * 30 org.jbehave.core.configuration.Keywords.startingWordFor(Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I11 Branch 15 IFNONNULL L420 - true
   * 31 org.jbehave.core.configuration.Keywords.startingWords()[Ljava/lang/String;: I32 Branch 2 IFNE L344 - false
   * 32 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I34 Branch 6 IF_ICMPLT L379 - false
   * 33 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I69 Branch 8 IF_ICMPLT L384 - false
   */
  @Test
  public void test2()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      Map<String, String> map0 = Keywords.defaultKeywords();
      StepType stepType0 = StepType.WHEN;
      String[] stringArray0 = keywords0.startingWordsFor(stepType0);
      String string0 = "ExamplesTableRow";
      Map<String, String> map1 = Keywords.defaultKeywords();
      Keywords keywords1 = new Keywords(map1);
      String string1 = keywords0.examplesTableValueSeparator();
      String string2 = keywords0.dryRun();
      String string3 = keywords0.yes();
      String[] stringArray1 = keywords0.startingWords();
      String string4 = keywords0.scenario();
      String string5 = keywords1.storyCancelled();
      Keywords.KeywordNotFound keywords_KeywordNotFound0 = new Keywords.KeywordNotFound("Scenario:", map0);
      Throwable throwable0 = keywords_KeywordNotFound0.getCause();
      Keywords keywords2 = new Keywords(map1);
      String string6 = keywords2.failed();
      Keywords.KeywordNotFound keywords_KeywordNotFound1 = new Keywords.KeywordNotFound("FAILED", map1);
      String string7 = keywords_KeywordNotFound1.getLocalizedMessage();
      String string8 = keywords0.failed();
      Keywords keywords3 = new Keywords();
      HashMap<StepType, String> hashMap0 = new HashMap<StepType, String>();
      Keywords.StartingWordNotFound keywords_StartingWordNotFound0 = new Keywords.StartingWordNotFound("|", (Map<StepType, String>) hashMap0);
      String string9 = keywords3.no();
      // Undeclared exception!
      try {
        keywords3.stepWithoutStartingWord("|", stepType0);
      }catch(Keywords.StartingWordNotFound e) {
        /*
         * No starting word found for step '|' of type 'WHEN' amongst '{IGNORABLE=!--, WHEN=When, AND=And, GIVEN=Given, THEN=Then}'
         */
        /*
      %%%<ex><className val="StartingWordNotFound"/><stackDepth val="15"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.startingWord(Keywords.java:389)"/></ex>%%%
         */
      }
  }

  //Test case number: 3
  /*
   * 21 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.duration()Ljava/lang/String;: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.asA()Ljava/lang/String;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.startingWordsFor(Lorg/jbehave/core/steps/StepType;)[Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 6 org.jbehave.core.configuration.Keywords.synonymsOf(Ljava/lang/String;)[Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 8 org.jbehave.core.configuration.Keywords.<init>()V: root-Branch
   * 9 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 10 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 11 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 12 org.jbehave.core.configuration.Keywords.stepStartsWithWord(Ljava/lang/String;Ljava/lang/String;)Z: root-Branch
   * 13 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 14 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 15 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   * 16 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I36 Branch 12 IFEQ L406 - true
   * 17 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I47 Branch 13 IF_ICMPLT L405 - true
   * 18 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I52 Branch 14 IFNE L404 - true
   * 19 org.jbehave.core.configuration.Keywords.startingWordFor(Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I11 Branch 15 IFNONNULL L420 - true
   * 20 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I47 Branch 13 IF_ICMPLT L405 - false
   * 21 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I52 Branch 14 IFNE L404 - false
   */
  @Test
  public void test3()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      String string0 = keywords0.asA();
      String string1 = keywords0.duration();
      Keywords keywords1 = new Keywords();
      String string2 = "N]'";
      StepType stepType0 = StepType.IGNORABLE;
      String string3 = keywords0.startingWordFor(stepType0);
      try {
        keywords1.stepTypeFor("N]'");
      }catch(Keywords.StartingWordNotFound e) {
        /*
         * No starting word found for step 'N]'' amongst '{IGNORABLE=!--, WHEN=When, AND=And, GIVEN=Given, THEN=Then}'
         */
        /*
      %%%<ex><className val="StartingWordNotFound"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.stepTypeFor(Keywords.java:411)"/></ex>%%%
         */
      }
  }

  //Test case number: 4
  /*
   * 10 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.<init>()V: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 6 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 8 org.jbehave.core.configuration.Keywords$KeywordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 9 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 10 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   */
  @Test
  public void test4()  throws Throwable  {
      Map<String, String> map0 = Keywords.defaultKeywords();
      Keywords.KeywordNotFound keywords_KeywordNotFound0 = new Keywords.KeywordNotFound("_*Y >WBX=? hs", map0);
      Keywords.KeywordNotFound keywords_KeywordNotFound1 = (Keywords.KeywordNotFound)keywords_KeywordNotFound0.fillInStackTrace();
      Keywords keywords0 = new Keywords();
      String string0 = keywords0.given();
      HashMap<String, String> hashMap0 = null;
      try {
        hashMap0 = new HashMap<String, String>((-2034));
      }catch(IllegalArgumentException e) {
        /*
         * Illegal initial capacity: -2034
         */
        /*
      %%%<ex><className val="IllegalArgumentException"/><stackDepth val="15"/><causeDepth val="0"/><source val="java.util.HashMap.&lt;init&gt;(HashMap.java:189)"/></ex>%%%
         */
      }
  }

  //Test case number: 5
  /*
   * 21 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.isIgnorableStep(Ljava/lang/String;)Z: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.asA()Ljava/lang/String;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.dryRun()Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Lorg/jbehave/core/steps/StepType;Ljava/util/Map;)V: root-Branch
   * 6 org.jbehave.core.configuration.Keywords.startingWordsFor(Lorg/jbehave/core/steps/StepType;)[Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 8 org.jbehave.core.configuration.Keywords.synonymsOf(Ljava/lang/String;)[Ljava/lang/String;: root-Branch
   * 9 org.jbehave.core.configuration.Keywords.<init>()V: root-Branch
   * 10 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 11 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 12 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 13 org.jbehave.core.configuration.Keywords.stepStartsWithWord(Ljava/lang/String;Ljava/lang/String;)Z: root-Branch
   * 14 org.jbehave.core.configuration.Keywords$KeywordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 15 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 16 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 17 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   * 18 org.jbehave.core.configuration.Keywords.ofStepType(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Z: I31 Branch 3 IFEQ L358 - true
   * 19 org.jbehave.core.configuration.Keywords.ofStepType(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Z: I41 Branch 4 IF_ICMPLT L356 - true
   * 20 org.jbehave.core.configuration.Keywords.startingWordFor(Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I11 Branch 15 IFNONNULL L420 - true
   * 21 org.jbehave.core.configuration.Keywords.ofStepType(Ljava/lang/String;Lorg/jbehave/core/steps/StepType;)Z: I41 Branch 4 IF_ICMPLT L356 - false
   */
  @Test
  public void test5()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      String string0 = keywords0.asA();
      String string1 = keywords0.when();
      boolean boolean0 = keywords0.isIgnorableStep("");
      Map<String, String> map0 = Keywords.defaultKeywords();
      Keywords keywords1 = new Keywords(map0);
      StepType stepType0 = StepType.AND;
      Map<String, String> map1 = Keywords.defaultKeywords();
  }

  //Test case number: 7
  /*
   * 20 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.narrative()Ljava/lang/String;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.startingWordsFor(Lorg/jbehave/core/steps/StepType;)[Ljava/lang/String;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords.synonymsOf(Ljava/lang/String;)[Ljava/lang/String;: root-Branch
   * 6 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 7 org.jbehave.core.configuration.Keywords.<init>()V: root-Branch
   * 8 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 9 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 10 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 11 org.jbehave.core.configuration.Keywords.stepStartsWithWord(Ljava/lang/String;Ljava/lang/String;)Z: root-Branch
   * 12 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 13 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 14 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   * 15 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;)Ljava/lang/String;: I36 Branch 9 IFEQ L395 - true
   * 16 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;)Ljava/lang/String;: I47 Branch 10 IF_ICMPLT L394 - true
   * 17 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;)Ljava/lang/String;: I52 Branch 11 IFNE L393 - true
   * 18 org.jbehave.core.configuration.Keywords.startingWordFor(Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I11 Branch 15 IFNONNULL L420 - true
   * 19 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;)Ljava/lang/String;: I47 Branch 10 IF_ICMPLT L394 - false
   * 20 org.jbehave.core.configuration.Keywords.startingWord(Ljava/lang/String;)Ljava/lang/String;: I52 Branch 11 IFNE L393 - false
   */
  @Test
  public void test7()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      Map<String, String> map0 = Keywords.defaultKeywords();
      Keywords keywords1 = new Keywords(map0);
      StepType stepType0 = StepType.THEN;
      String string0 = keywords0.narrative();
      try {
        keywords0.startingWord("jz`Qh~/?@3");
      }catch(Keywords.StartingWordNotFound e) {
        /*
         * No starting word found for step 'jz`Qh~/?@3' amongst '{IGNORABLE=!--, WHEN=When, AND=And, GIVEN=Given, THEN=Then}'
         */
        /*
      %%%<ex><className val="StartingWordNotFound"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.startingWord(Keywords.java:400)"/></ex>%%%
         */
      }
  }

  //Test case number: 8
  /*
   * 23 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.failed()Ljava/lang/String;: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.examplesTable()Ljava/lang/String;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.outcomeFields()Ljava/util/List;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords.startingWordsFor(Lorg/jbehave/core/steps/StepType;)[Ljava/lang/String;: root-Branch
   * 6 org.jbehave.core.configuration.Keywords.iWantTo()Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 8 org.jbehave.core.configuration.Keywords.synonymsOf(Ljava/lang/String;)[Ljava/lang/String;: root-Branch
   * 9 org.jbehave.core.configuration.Keywords$StartingWordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 10 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 11 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 12 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 13 org.jbehave.core.configuration.Keywords.stepStartsWithWord(Ljava/lang/String;Ljava/lang/String;)Z: root-Branch
   * 14 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 15 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 16 org.jbehave.core.configuration.Keywords$KeywordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 17 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   * 18 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I36 Branch 12 IFEQ L406 - true
   * 19 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I47 Branch 13 IF_ICMPLT L405 - true
   * 20 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I52 Branch 14 IFNE L404 - true
   * 21 org.jbehave.core.configuration.Keywords.startingWordFor(Lorg/jbehave/core/steps/StepType;)Ljava/lang/String;: I11 Branch 15 IFNONNULL L420 - true
   * 22 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I47 Branch 13 IF_ICMPLT L405 - false
   * 23 org.jbehave.core.configuration.Keywords.stepTypeFor(Ljava/lang/String;)Lorg/jbehave/core/steps/StepType;: I52 Branch 14 IFNE L404 - false
   */
  @Test
  public void test8()  throws Throwable  {
      Map<String, String> map0 = Keywords.defaultKeywords();
      Keywords keywords0 = new Keywords(map0);
      String string0 = keywords0.then();
      Map<String, String> map1 = Keywords.defaultKeywords();
      Keywords keywords1 = new Keywords(map1);
      String string1 = keywords1.iWantTo();
      String string2 = keywords1.examplesTable();
      String string3 = keywords0.failed();
      Keywords.KeywordNotFound keywords_KeywordNotFound0 = new Keywords.KeywordNotFound("jK@^9I6d8??@_s?&1B", (Map<String, String>) null);
      Throwable throwable0 = keywords_KeywordNotFound0.getCause();
      Map<String, String> map2 = Keywords.defaultKeywords();
      Keywords.KeywordNotFound keywords_KeywordNotFound1 = new Keywords.KeywordNotFound("jK@^9I6d8??@_s?&1B", map2);
      HashMap<StepType, String> hashMap0 = new HashMap<StepType, String>();
      List<String> list0 = keywords1.outcomeFields();
      boolean boolean0 = keywords1.stepStartsWithWord("jK@^9I6d8??@_s?&1B", "jK@^9I6d8??@_s?&1B");
      Keywords.StartingWordNotFound keywords_StartingWordNotFound0 = new Keywords.StartingWordNotFound("jK@^9I6d8??@_s?&1B", (Map<StepType, String>) hashMap0);
      StepType stepType0 = StepType.GIVEN;
      try {
        keywords0.stepTypeFor("Then");
      }catch(Keywords.StartingWordNotFound e) {
        /*
         * No starting word found for step 'Then' amongst '{IGNORABLE=!--, WHEN=When, AND=And, GIVEN=Given, THEN=Then}'
         */
        /*
      %%%<ex><className val="StartingWordNotFound"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.stepTypeFor(Keywords.java:411)"/></ex>%%%
         */
      }
  }

  //Test case number: 9
  /*
   * 15 covered goals:
   * 1 org.jbehave.core.configuration.Keywords.startingWordsByType()Ljava/util/Map;: root-Branch
   * 2 org.jbehave.core.configuration.Keywords.defaultKeywords()Ljava/util/Map;: root-Branch
   * 3 org.jbehave.core.configuration.Keywords.when()Ljava/lang/String;: root-Branch
   * 4 org.jbehave.core.configuration.Keywords.synonymsOf(Ljava/lang/String;)[Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.configuration.Keywords.given()Ljava/lang/String;: root-Branch
   * 6 org.jbehave.core.configuration.Keywords.then()Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.configuration.Keywords.<init>(Ljava/util/Map;)V: root-Branch
   * 8 org.jbehave.core.configuration.Keywords.and()Ljava/lang/String;: root-Branch
   * 9 org.jbehave.core.configuration.Keywords.ignorable()Ljava/lang/String;: root-Branch
   * 10 org.jbehave.core.configuration.Keywords$KeywordNotFound.<init>(Ljava/lang/String;Ljava/util/Map;)V: root-Branch
   * 11 org.jbehave.core.configuration.Keywords.examplesTableHeaderSeparator()Ljava/lang/String;: root-Branch
   * 12 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - true
   * 13 org.jbehave.core.configuration.Keywords.startingWords()[Ljava/lang/String;: I32 Branch 2 IFNE L344 - true
   * 14 org.jbehave.core.configuration.Keywords.keyword(Ljava/lang/String;Ljava/util/Map;)Ljava/lang/String;: I10 Branch 1 IFNONNULL L224 - false
   * 15 org.jbehave.core.configuration.Keywords.startingWords()[Ljava/lang/String;: I32 Branch 2 IFNE L344 - false
   */
  @Test
  public void test9()  throws Throwable  {
      Map<String, String> map0 = Keywords.defaultKeywords();
      Keywords keywords0 = new Keywords(map0);
      String[] stringArray0 = keywords0.startingWords();
      String string0 = keywords0.then();
      String string1 = keywords0.examplesTableHeaderSeparator();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      Keywords keywords1 = null;
      try {
        keywords1 = new Keywords((Map<String, String>) hashMap0);
      }catch(Keywords.KeywordNotFound e) {
        /*
         * Keyword Meta not found amongst {}
         */
        /*
      %%%<ex><className val="KeywordNotFound"/><stackDepth val="15"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.keyword(Keywords.java:225)"/></ex>%%%
         */
      }
  }
}
