/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.functors;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Collection;
import java.util.LinkedList;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.functors.ChainedTransformer;
import org.apache.commons.collections4.functors.NOPTransformer;
import org.junit.BeforeClass;

public class ChainedTransformerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.ChainedTransformer.chainedTransformer(Ljava/util/Collection;)Lorg/apache/commons/collections4/Transformer;: I3 Branch 2 IFNONNULL L71 - true
   * 2 org.apache.commons.collections4.functors.ChainedTransformer.chainedTransformer(Ljava/util/Collection;)Lorg/apache/commons/collections4/Transformer;: I15 Branch 3 IFNE L74 - false
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(697,"org.apache.commons.collections4.functors.ChainedTransformerEvoSuiteTest.test0");
      LinkedList<NOPTransformer<Object>> linkedList0 = new LinkedList<NOPTransformer<Object>>();
      Transformer<Object, Object> transformer0 = ChainedTransformer.chainedTransformer((Collection<? extends Transformer<Object, Object>>) linkedList0);
      assertNotNull(transformer0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.ChainedTransformer.chainedTransformer(Ljava/util/Collection;)Lorg/apache/commons/collections4/Transformer;: I3 Branch 2 IFNONNULL L71 - false
   */

  @Test
  public void test1()  throws Throwable  {
      // Undeclared exception!
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(698,"org.apache.commons.collections4.functors.ChainedTransformerEvoSuiteTest.test1");
      try {
        ChainedTransformer.chainedTransformer((Collection<? extends Transformer<Integer, Integer>>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Transformer collection must not be null
         //
      }
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.ChainedTransformer.chainedTransformer(Ljava/util/Collection;)Lorg/apache/commons/collections4/Transformer;: I15 Branch 3 IFNE L74 - true
   * 2 org.apache.commons.collections4.functors.ChainedTransformer.chainedTransformer(Ljava/util/Collection;)Lorg/apache/commons/collections4/Transformer;: I3 Branch 2 IFNONNULL L71 - true
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(699,"org.apache.commons.collections4.functors.ChainedTransformerEvoSuiteTest.test2");
      LinkedList<NOPTransformer<Object>> linkedList0 = new LinkedList<NOPTransformer<Object>>();
      linkedList0.add((NOPTransformer<Object>) null);
      // Undeclared exception!
      try {
        ChainedTransformer.chainedTransformer((Collection<? extends Transformer<Object, Object>>) linkedList0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The transformer array must not contain a null transformer, index 0 was null
         //
      }
  }
}
