/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.functors;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Comparator;
import org.apache.commons.collections4.functors.ComparatorPredicate;
import org.junit.BeforeClass;

public class ComparatorPredicateEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.ComparatorPredicate.comparatorPredicate(Ljava/lang/Object;Ljava/util/Comparator;)Lorg/apache/commons/collections4/Predicate;: root-Branch
   * 2 org.apache.commons.collections4.functors.ComparatorPredicate.comparatorPredicate(Ljava/lang/Object;Ljava/util/Comparator;Lorg/apache/commons/collections4/functors/ComparatorPredicate$Criterion;)Lorg/apache/commons/collections4/Predicate;: I3 Branch 1 IFNONNULL L123 - false
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(705,"org.apache.commons.collections4.functors.ComparatorPredicateEvoSuiteTest.test0");
      Object object0 = new Object();
      // Undeclared exception!
      try {
        ComparatorPredicate.comparatorPredicate(object0, (Comparator<Object>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Comparator must not be null.
         //
      }
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.ComparatorPredicate.<init>(Ljava/lang/Object;Ljava/util/Comparator;Lorg/apache/commons/collections4/functors/ComparatorPredicate$Criterion;)V: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(706,"org.apache.commons.collections4.functors.ComparatorPredicateEvoSuiteTest.test1");
      ComparatorPredicate.Criterion comparatorPredicate_Criterion0 = ComparatorPredicate.Criterion.GREATER;
      ComparatorPredicate<String> comparatorPredicate0 = new ComparatorPredicate<String>("", (Comparator<String>) null, (ComparatorPredicate.Criterion) comparatorPredicate_Criterion0);
  }
}
