/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.functors;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.functors.DefaultEquator;
import org.apache.commons.collections4.functors.EqualPredicate;
import org.apache.commons.collections4.functors.Equator;
import org.junit.BeforeClass;

public class EqualPredicateEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.EqualPredicate.<init>(Ljava/lang/Object;Lorg/apache/commons/collections4/functors/Equator;)V: root-Branch
   * 2 org.apache.commons.collections4.functors.EqualPredicate.equalPredicate(Ljava/lang/Object;Lorg/apache/commons/collections4/functors/Equator;)Lorg/apache/commons/collections4/Predicate;: I3 Branch 2 IFNONNULL L69 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(715,"org.apache.commons.collections4.functors.EqualPredicateEvoSuiteTest.test0");
      DefaultEquator<Object> defaultEquator0 = DefaultEquator.INSTANCE;
      Predicate<Object> predicate0 = EqualPredicate.equalPredicate((Object) defaultEquator0, (Equator<Object>) defaultEquator0);
      assertNotNull(predicate0);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.EqualPredicate.<init>(Ljava/lang/Object;)V: root-Branch
   * 2 org.apache.commons.collections4.functors.EqualPredicate.equalPredicate(Ljava/lang/Object;)Lorg/apache/commons/collections4/Predicate;: I3 Branch 1 IFNONNULL L52 - true
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(716,"org.apache.commons.collections4.functors.EqualPredicateEvoSuiteTest.test1");
      Predicate<Object> predicate0 = EqualPredicate.equalPredicate((Object) "2");
      assertNotNull(predicate0);
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.EqualPredicate.equalPredicate(Ljava/lang/Object;)Lorg/apache/commons/collections4/Predicate;: I3 Branch 1 IFNONNULL L52 - false
   * 2 org.apache.commons.collections4.functors.EqualPredicate.getValue()Ljava/lang/Object;: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(717,"org.apache.commons.collections4.functors.EqualPredicateEvoSuiteTest.test2");
      DefaultEquator<Object> defaultEquator0 = DefaultEquator.INSTANCE;
      EqualPredicate<Object> equalPredicate0 = new EqualPredicate<Object>((Object) null, (Equator<Object>) defaultEquator0);
      equalPredicate0.getValue();
      Predicate<Object> predicate0 = EqualPredicate.equalPredicate((Object) null);
      assertNotNull(predicate0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.EqualPredicate.equalPredicate(Ljava/lang/Object;Lorg/apache/commons/collections4/functors/Equator;)Lorg/apache/commons/collections4/Predicate;: I3 Branch 2 IFNONNULL L69 - false
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(718,"org.apache.commons.collections4.functors.EqualPredicateEvoSuiteTest.test3");
      DefaultEquator<Object> defaultEquator0 = DefaultEquator.INSTANCE;
      Predicate<Object> predicate0 = EqualPredicate.equalPredicate((Object) null, (Equator<Object>) defaultEquator0);
      assertNotNull(predicate0);
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.EqualPredicate.evaluate(Ljava/lang/Object;)Z: I4 Branch 3 IFNULL L108 - true
   * 2 org.apache.commons.collections4.functors.EqualPredicate.<init>(Ljava/lang/Object;)V: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(719,"org.apache.commons.collections4.functors.EqualPredicateEvoSuiteTest.test4");
      EqualPredicate<Integer> equalPredicate0 = new EqualPredicate<Integer>((Integer) null);
      // Undeclared exception!
      try {
        equalPredicate0.evaluate((Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 org.apache.commons.collections4.functors.EqualPredicate.evaluate(Ljava/lang/Object;)Z: I4 Branch 3 IFNULL L108 - false
   * 2 org.apache.commons.collections4.functors.EqualPredicate.<init>(Ljava/lang/Object;Lorg/apache/commons/collections4/functors/Equator;)V: root-Branch
   * 3 org.apache.commons.collections4.functors.EqualPredicate.getValue()Ljava/lang/Object;: root-Branch
   */

  @Test
  public void test5()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(720,"org.apache.commons.collections4.functors.EqualPredicateEvoSuiteTest.test5");
      DefaultEquator<Object> defaultEquator0 = DefaultEquator.INSTANCE;
      EqualPredicate<Object> equalPredicate0 = new EqualPredicate<Object>((Object) "2", (Equator<Object>) defaultEquator0);
      String string0 = (String)equalPredicate0.getValue();
      assertNotNull(string0);
      
      boolean boolean0 = equalPredicate0.evaluate((Object) "2");
      assertEquals(true, boolean0);
  }
}
