/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.functors;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.functors.NullPredicate;
import org.junit.BeforeClass;

public class NullPredicateEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.NullPredicate.nullPredicate()Lorg/apache/commons/collections4/Predicate;: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(806,"org.apache.commons.collections4.functors.NullPredicateEvoSuiteTest.test0");
      Predicate<Integer> predicate0 = NullPredicate.nullPredicate();
      assertNotNull(predicate0);
  }
}
