/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.functors;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Array;
import org.apache.commons.collections4.FunctorException;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.functors.AnyPredicate;
import org.apache.commons.collections4.functors.ExceptionPredicate;
import org.apache.commons.collections4.functors.NullIsFalsePredicate;
import org.junit.BeforeClass;

public class NullIsFalsePredicateEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.NullIsFalsePredicate.getPredicates()[Lorg/apache/commons/collections4/Predicate;: root-Branch
   * 2 org.apache.commons.collections4.functors.NullIsFalsePredicate.<init>(Lorg/apache/commons/collections4/Predicate;)V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(796,"org.apache.commons.collections4.functors.NullIsFalsePredicateEvoSuiteTest.test0");
      NullIsFalsePredicate<String> nullIsFalsePredicate0 = new NullIsFalsePredicate<String>((Predicate<? super String>) null);
      Predicate<? super String>[] predicateArray0 = nullIsFalsePredicate0.getPredicates();
      assertNotNull(predicateArray0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.NullIsFalsePredicate.nullIsFalsePredicate(Lorg/apache/commons/collections4/Predicate;)Lorg/apache/commons/collections4/Predicate;: I3 Branch 1 IFNONNULL L46 - true
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(797,"org.apache.commons.collections4.functors.NullIsFalsePredicateEvoSuiteTest.test1");
      Predicate<Object>[] predicateArray0 = (Predicate<Object>[]) Array.newInstance(Predicate.class, 2);
      AnyPredicate<Object> anyPredicate0 = new AnyPredicate<Object>(predicateArray0);
      Predicate<Object> predicate0 = NullIsFalsePredicate.nullIsFalsePredicate((Predicate<? super Object>) anyPredicate0);
      assertNotNull(predicate0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.NullIsFalsePredicate.nullIsFalsePredicate(Lorg/apache/commons/collections4/Predicate;)Lorg/apache/commons/collections4/Predicate;: I3 Branch 1 IFNONNULL L46 - false
   */

  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(798,"org.apache.commons.collections4.functors.NullIsFalsePredicateEvoSuiteTest.test2");
      try {
        NullIsFalsePredicate.nullIsFalsePredicate((Predicate<? super Integer>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Predicate must not be null
         //
      }
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.NullIsFalsePredicate.evaluate(Ljava/lang/Object;)Z: I3 Branch 2 IFNONNULL L71 - true
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(799,"org.apache.commons.collections4.functors.NullIsFalsePredicateEvoSuiteTest.test3");
      Predicate<Object> predicate0 = ExceptionPredicate.INSTANCE;
      NullIsFalsePredicate<Object> nullIsFalsePredicate0 = new NullIsFalsePredicate<Object>(predicate0);
      // Undeclared exception!
      try {
        nullIsFalsePredicate0.evaluate((Object) "");
        fail("Expecting exception: FunctorException");
      
      } catch(FunctorException e) {
         //
         // ExceptionPredicate invoked
         //
      }
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.NullIsFalsePredicate.evaluate(Ljava/lang/Object;)Z: I3 Branch 2 IFNONNULL L71 - false
   * 2 org.apache.commons.collections4.functors.NullIsFalsePredicate.<init>(Lorg/apache/commons/collections4/Predicate;)V: root-Branch
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(800,"org.apache.commons.collections4.functors.NullIsFalsePredicateEvoSuiteTest.test4");
      NullIsFalsePredicate<Object> nullIsFalsePredicate0 = new NullIsFalsePredicate<Object>((Predicate<? super Object>) null);
      boolean boolean0 = nullIsFalsePredicate0.evaluate((Object) null);
      assertEquals(false, boolean0);
  }
}
