/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.functors;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Array;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.functors.AnyPredicate;
import org.apache.commons.collections4.functors.NotNullPredicate;
import org.apache.commons.collections4.functors.NullIsExceptionPredicate;
import org.apache.commons.collections4.functors.PredicateTransformer;
import org.junit.BeforeClass;

public class PredicateTransformerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.PredicateTransformer.getPredicate()Lorg/apache/commons/collections4/Predicate;: root-Branch
   * 2 org.apache.commons.collections4.functors.PredicateTransformer.<init>(Lorg/apache/commons/collections4/Predicate;)V: root-Branch
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(818,"org.apache.commons.collections4.functors.PredicateTransformerEvoSuiteTest.test0");
      Predicate<Boolean>[] predicateArray0 = (Predicate<Boolean>[]) Array.newInstance(Predicate.class, 2);
      AnyPredicate<Boolean> anyPredicate0 = new AnyPredicate<Boolean>(predicateArray0);
      PredicateTransformer<Boolean> predicateTransformer0 = new PredicateTransformer<Boolean>((Predicate<? super Boolean>) anyPredicate0);
      Predicate<? super Boolean> predicate0 = predicateTransformer0.getPredicate();
      assertNotNull(predicate0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.PredicateTransformer.transform(Ljava/lang/Object;)Ljava/lang/Boolean;: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(819,"org.apache.commons.collections4.functors.PredicateTransformerEvoSuiteTest.test1");
      Predicate<Boolean>[] predicateArray0 = (Predicate<Boolean>[]) Array.newInstance(Predicate.class, 2);
      AnyPredicate<Boolean> anyPredicate0 = new AnyPredicate<Boolean>(predicateArray0);
      PredicateTransformer<Boolean> predicateTransformer0 = new PredicateTransformer<Boolean>((Predicate<? super Boolean>) anyPredicate0);
      Boolean boolean0 = Boolean.valueOf("?JwV{>VO");
      // Undeclared exception!
      try {
        predicateTransformer0.transform(boolean0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.functors.PredicateTransformer.predicateTransformer(Lorg/apache/commons/collections4/Predicate;)Lorg/apache/commons/collections4/Transformer;: I3 Branch 1 IFNONNULL L48 - true
   * 2 org.apache.commons.collections4.functors.PredicateTransformer.<init>(Lorg/apache/commons/collections4/Predicate;)V: root-Branch
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(820,"org.apache.commons.collections4.functors.PredicateTransformerEvoSuiteTest.test2");
      Predicate<Object> predicate0 = NotNullPredicate.INSTANCE;
      NullIsExceptionPredicate<Object> nullIsExceptionPredicate0 = new NullIsExceptionPredicate<Object>(predicate0);
      Transformer<Object, Boolean> transformer0 = PredicateTransformer.predicateTransformer((Predicate<? super Object>) nullIsExceptionPredicate0);
      assertNotNull(transformer0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.functors.PredicateTransformer.predicateTransformer(Lorg/apache/commons/collections4/Predicate;)Lorg/apache/commons/collections4/Transformer;: I3 Branch 1 IFNONNULL L48 - false
   */

  @Test
  public void test3()  throws Throwable  {
      // Undeclared exception!
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(821,"org.apache.commons.collections4.functors.PredicateTransformerEvoSuiteTest.test3");
      try {
        PredicateTransformer.predicateTransformer((Predicate<? super Object>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Predicate must not be null
         //
      }
  }
}
