/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.parsers;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.regex.Pattern;
import org.jbehave.core.model.StepPattern;
import org.jbehave.core.parsers.RegexStepMatcher;
import org.jbehave.core.steps.StepType;


public class RegexStepMatcherEvoSuiteTest {


  //Test case number: 1
  /*
   * 6 covered goals:
   * 1 org.jbehave.core.parsers.RegexStepMatcher.pattern()Lorg/jbehave/core/model/StepPattern;: root-Branch
   * 2 org.jbehave.core.parsers.RegexStepMatcher.matcher(Ljava/lang/String;)V: root-Branch
   * 3 org.jbehave.core.parsers.RegexStepMatcher.<init>(Lorg/jbehave/core/steps/StepType;Ljava/lang/String;Ljava/util/regex/Pattern;[Ljava/lang/String;)V: root-Branch
   * 4 org.jbehave.core.parsers.RegexStepMatcher.parameterNames()[Ljava/lang/String;: root-Branch
   * 5 org.jbehave.core.parsers.RegexStepMatcher.parameter(I)Ljava/lang/String;: root-Branch
   * 6 org.jbehave.core.parsers.RegexStepMatcher.matches(Ljava/lang/String;)Z: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      StepType stepType0 = StepType.AND;
      String string0 = "";
      Pattern pattern0 = Pattern.compile("", (-1));
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "";
      StepType stepType1 = StepType.GIVEN;
      RegexStepMatcher regexStepMatcher0 = new RegexStepMatcher(stepType1, "", pattern0, stringArray0);
      boolean boolean0 = regexStepMatcher0.matches("");
      stringArray0[2] = "";
      stringArray0[3] = "";
      RegexStepMatcher regexStepMatcher1 = new RegexStepMatcher(stepType0, "", pattern0, stringArray0);
      StepPattern stepPattern0 = regexStepMatcher1.pattern();
      String[] stringArray1 = new String[2];
      StepPattern stepPattern1 = regexStepMatcher1.pattern();
      StepType stepType2 = StepType.AND;
      String string1 = Pattern.quote("");
      StepType stepType3 = StepType.THEN;
      String[] stringArray2 = regexStepMatcher1.parameterNames();
      RegexStepMatcher regexStepMatcher2 = new RegexStepMatcher(stepType3, "QE", pattern0, stringArray1);
      // Undeclared exception!
      try {
        regexStepMatcher2.parameter((-1));
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.parsers.RegexStepMatcher.parameter(RegexStepMatcher.java:30)"/></ex>%%%
         */
      }
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 org.jbehave.core.parsers.RegexStepMatcher.<init>(Lorg/jbehave/core/steps/StepType;Ljava/lang/String;Ljava/util/regex/Pattern;[Ljava/lang/String;)V: root-Branch
   * 2 org.jbehave.core.parsers.RegexStepMatcher.parameterNames()[Ljava/lang/String;: root-Branch
   * 3 org.jbehave.core.parsers.RegexStepMatcher.parameter(I)Ljava/lang/String;: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      StepType stepType0 = StepType.GIVEN;
      Pattern pattern0 = Pattern.compile("pf3j5 p", (-1));
      String[] stringArray0 = new String[6];
      stringArray0[0] = "pf3j5 p";
      stringArray0[1] = "pf3j5 p";
      stringArray0[2] = "pf3j5 p";
      stringArray0[3] = "pf3j5 p";
      stringArray0[4] = "pf3j5 p";
      stringArray0[5] = "pf3j5 p";
      RegexStepMatcher regexStepMatcher0 = new RegexStepMatcher(stepType0, "pf3j5 p", pattern0, stringArray0);
      String[] stringArray1 = regexStepMatcher0.parameterNames();
      StepType stepType1 = StepType.GIVEN;
      Pattern pattern1 = Pattern.compile("", 1390);
      String[] stringArray2 = new String[1];
      stringArray2[0] = "";
      RegexStepMatcher regexStepMatcher1 = new RegexStepMatcher(stepType1, "", pattern1, stringArray2);
      // Undeclared exception!
      try {
        regexStepMatcher1.parameter(1390);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.parsers.RegexStepMatcher.parameter(RegexStepMatcher.java:30)"/></ex>%%%
         */
      }
  }
}
