/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.reporters;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.net.InterfaceAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import org.jbehave.core.configuration.Configuration;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.configuration.ParanamerConfiguration;
import org.jbehave.core.configuration.UnmodifiableConfiguration;
import org.jbehave.core.failures.UUIDExceptionWrapper;
import org.jbehave.core.i18n.LocalizedKeywords;
import org.jbehave.core.model.Description;
import org.jbehave.core.model.ExamplesTable;
import org.jbehave.core.model.GivenStories;
import org.jbehave.core.model.GivenStory;
import org.jbehave.core.model.Meta;
import org.jbehave.core.model.Narrative;
import org.jbehave.core.model.OutcomesTable;
import org.jbehave.core.model.Scenario;
import org.jbehave.core.model.Story;
import org.jbehave.core.reporters.ANSIConsoleOutput;
import org.jbehave.core.reporters.ConcurrentStoryReporter;
import org.jbehave.core.reporters.ConsoleOutput;
import org.jbehave.core.reporters.DelegatingStoryReporter;
import org.jbehave.core.reporters.FreemarkerProcessor;
import org.jbehave.core.reporters.HtmlOutput;
import org.jbehave.core.reporters.HtmlTemplateOutput;
import org.jbehave.core.reporters.IdeOnlyConsoleOutput;
import org.jbehave.core.reporters.NullStoryReporter;
import org.jbehave.core.reporters.PrintStreamOutput;
import org.jbehave.core.reporters.StoryReporter;
import org.jbehave.core.reporters.TemplateProcessor;
import org.jbehave.core.reporters.TxtOutput;
import org.jbehave.core.reporters.XmlOutput;
import org.jbehave.core.steps.Parameters;
import org.jbehave.core.steps.StepType;


public class ConcurrentStoryReporterEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.jbehave.core.reporters.ConcurrentStoryReporter.<init>(Lorg/jbehave/core/reporters/StoryReporter;Lorg/jbehave/core/reporters/StoryReporter;Z)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      ConcurrentStoryReporter concurrentStoryReporter0 = new ConcurrentStoryReporter((StoryReporter) null, (StoryReporter) null, true);
      String string0 = "src/test/java";
      // Undeclared exception!
      try {
        concurrentStoryReporter0.notPerformed("src/test/java");
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="15"/><causeDepth val="0"/><source val="org.jbehave.core.reporters.ConcurrentStoryReporter.notPerformed(ConcurrentStoryReporter.java:259)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 org.jbehave.core.reporters.ConcurrentStoryReporter$DelayedMethod.<init>(Ljava/lang/reflect/Method;[Ljava/lang/Object;)V: root-Branch
   * 2 org.jbehave.core.reporters.ConcurrentStoryReporter.<init>(Lorg/jbehave/core/reporters/StoryReporter;Lorg/jbehave/core/reporters/StoryReporter;Z)V: root-Branch
   * 3 org.jbehave.core.reporters.ConcurrentStoryReporter.beforeStep(Ljava/lang/String;)V: I10 Branch 14 IFEQ L224 - false
   */
  @Test
  public void test1()  throws Throwable  {
      String string0 = "koP48BJB3Uq(SEAVb";
      NullStoryReporter nullStoryReporter0 = new NullStoryReporter();
      ConcurrentStoryReporter concurrentStoryReporter0 = new ConcurrentStoryReporter((StoryReporter) nullStoryReporter0, (StoryReporter) nullStoryReporter0, true);
      concurrentStoryReporter0.beforeStep("koP48BJB3Uq(SEAVb");
      // Undeclared exception!
      try {
        File.createTempFile("koP48BJB3Uq(SEAVb", "koP48BJB3Uq(SEAVb");
      }catch(SecurityException e) {
        /*
         * Security manager blocks (java.io.FilePermission /tmp/koP48BJB3Uq(SEAVb3542914020187951323koP48BJB3Uq(SEAVb write)
         * java.lang.Thread.getStackTrace(Thread.java:1495)
         * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
         * java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
         * java.io.File.checkAndCreate(File.java:1709)
         * java.io.File.createTempFile0(File.java:1738)
         * java.io.File.createTempFile(File.java:1850)
         * sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         * sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
         * sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         * java.lang.reflect.Method.invoke(Method.java:616)
         * org.evosuite.testcase.MethodStatement$1.execute(MethodStatement.java:262)
         * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
         * org.evosuite.testcase.MethodStatement.execute(MethodStatement.java:217)
         * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
         * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:1)
         * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
         * java.util.concurrent.FutureTask.run(FutureTask.java:166)
         * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
         * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
         * java.lang.Thread.run(Thread.java:679)
         */
        /*
      %%%<ex><className val="SecurityException"/><stackDepth val="19"/><causeDepth val="0"/><source val="org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:307)"/></ex>%%%
         */
      }
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.jbehave.core.reporters.ConcurrentStoryReporter.<init>(Lorg/jbehave/core/reporters/StoryReporter;Lorg/jbehave/core/reporters/StoryReporter;Z)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      PrintStream printStream0 = null;
      Properties properties0 = new Properties();
      Keywords keywords0 = new Keywords();
      XmlOutput xmlOutput0 = new XmlOutput((PrintStream) null, properties0, keywords0);
      ConcurrentStoryReporter concurrentStoryReporter0 = new ConcurrentStoryReporter((StoryReporter) xmlOutput0, (StoryReporter) xmlOutput0, true);
      // Undeclared exception!
      try {
        concurrentStoryReporter0.afterExamples();
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="17"/><causeDepth val="0"/><source val="org.jbehave.core.reporters.PrintStreamOutput.print(PrintStreamOutput.java:373)"/></ex>%%%
         */
      }
  }

  //Test case number: 4  @Test
  public void test4()  throws Throwable  {
      File file0 = new File("");
      File file1 = file0.getAbsoluteFile();
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@115a298
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="24"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 5  @Test
  public void test5()  throws Throwable  {
      String string0 = "J*FoH[S!q)%n!ulL%~Q";
      PrintStream printStream0 = null;
      try {
        printStream0 = new PrintStream("J*FoH[S!q)%n!ulL%~Q");
      }catch(SecurityException e) {
        /*
         * Security manager blocks (java.io.FilePermission J*FoH[S!q)%n!ulL%~Q write)
         * java.lang.Thread.getStackTrace(Thread.java:1495)
         * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
         * java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
         * java.io.FileOutputStream.<init>(FileOutputStream.java:198)
         * java.io.FileOutputStream.<init>(FileOutputStream.java:99)
         * java.io.PrintStream.<init>(PrintStream.java:173)
         * sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
         * sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
         * java.lang.reflect.Constructor.newInstance(Constructor.java:532)
         * org.evosuite.testcase.ConstructorStatement$1.execute(ConstructorStatement.java:226)
         * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
         * org.evosuite.testcase.ConstructorStatement.execute(ConstructorStatement.java:188)
         * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
         * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:1)
         * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
         * java.util.concurrent.FutureTask.run(FutureTask.java:166)
         * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
         * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
         * java.lang.Thread.run(Thread.java:679)
         */
        /*
      %%%<ex><className val="SecurityException"/><stackDepth val="18"/><causeDepth val="0"/><source val="org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:307)"/></ex>%%%
         */
      }
  }

  //Test case number: 6  @Test
  public void test6()  throws Throwable  {
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@115a298
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="24"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 org.jbehave.core.reporters.ConcurrentStoryReporter.<init>(Lorg/jbehave/core/reporters/StoryReporter;Lorg/jbehave/core/reporters/StoryReporter;Z)V: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      StoryReporter storyReporter0 = null;
      boolean boolean0 = true;
      ConcurrentStoryReporter concurrentStoryReporter0 = new ConcurrentStoryReporter((StoryReporter) null, (StoryReporter) null, true);
      String string0 = "";
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@115a298
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="24"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }
}
