/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.reporters;

import java.io.File;
import java.net.URL;

import org.jbehave.core.io.StoryLocation;
import org.junit.Test;


public class FilePrintStreamFactoryEvoSuiteTest {


  //Test case number: 0
  /*
   * 13 covered goals:
   * 1 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;)V: root-Branch
   * 2 org.jbehave.core.reporters.FilePrintStreamFactory.outputFile()Ljava/io/File;: root-Branch
   * 3 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.getPathResolver()Lorg/jbehave/core/reporters/FilePrintStreamFactory$FilePathResolver;: root-Branch
   * 4 org.jbehave.core.reporters.FilePrintStreamFactory.outputDirectory()Ljava/io/File;: root-Branch
   * 5 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FileConfiguration;)V: root-Branch
   * 6 org.jbehave.core.reporters.FilePrintStreamFactory$AbstractPathResolver.resolveDirectory(Lorg/jbehave/core/io/StoryLocation;Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.reporters.FilePrintStreamFactory$AbstractPathResolver.<init>()V: root-Branch
   * 8 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>()V: root-Branch
   * 9 org.jbehave.core.reporters.FilePrintStreamFactory.useConfiguration(Lorg/jbehave/core/reporters/FilePrintStreamFactory$FileConfiguration;)V: root-Branch
   * 10 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.getRelativeDirectory()Ljava/lang/String;: root-Branch
   * 11 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FilePathResolver;)V: root-Branch
   * 12 org.jbehave.core.reporters.FilePrintStreamFactory$ResolveToPackagedName.<init>()V: root-Branch
   * 13 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      StoryLocation storyLocation0 = new StoryLocation((URL) null, "#Bg]@`:loF `A");
      FilePrintStreamFactory filePrintStreamFactory0 = new FilePrintStreamFactory(storyLocation0);
      FilePrintStreamFactory.FileConfiguration filePrintStreamFactory_FileConfiguration0 = new FilePrintStreamFactory.FileConfiguration();
      // Undeclared exception!
      try {
        filePrintStreamFactory0.useConfiguration(filePrintStreamFactory_FileConfiguration0);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="18"/><causeDepth val="0"/><source val="org.jbehave.core.io.CodeLocations.getPathFromURL(CodeLocations.java:77)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 15 covered goals:
   * 1 org.jbehave.core.reporters.FilePrintStreamFactory$AbstractPathResolver.<init>()V: root-Branch
   * 2 org.jbehave.core.reporters.FilePrintStreamFactory$ResolveToPackagedName.<init>()V: root-Branch
   * 3 org.jbehave.core.reporters.FilePrintStreamFactory$AbstractPathResolver.resolveDirectory(Lorg/jbehave/core/io/StoryLocation;Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * 4 org.jbehave.core.reporters.FilePrintStreamFactory$ResolveToPackagedName.resolveName(Lorg/jbehave/core/io/StoryLocation;Ljava/lang/String;)Ljava/lang/String;: I14 Branch 1 IFLE L94 - true
   * 5 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;)V: root-Branch
   * 6 org.jbehave.core.reporters.FilePrintStreamFactory.outputFile()Ljava/io/File;: root-Branch
   * 7 org.jbehave.core.reporters.FilePrintStreamFactory$PrintStreamCreationFailed.<init>(Lorg/jbehave/core/reporters/FilePrintStreamFactory;Ljava/io/File;Ljava/lang/Exception;)V: root-Branch
   * 8 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.getPathResolver()Lorg/jbehave/core/reporters/FilePrintStreamFactory$FilePathResolver;: root-Branch
   * 9 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.getExtension()Ljava/lang/String;: root-Branch
   * 10 org.jbehave.core.reporters.FilePrintStreamFactory.outputDirectory()Ljava/io/File;: root-Branch
   * 11 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FileConfiguration;)V: root-Branch
   * 12 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>()V: root-Branch
   * 13 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.getRelativeDirectory()Ljava/lang/String;: root-Branch
   * 14 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FilePathResolver;)V: root-Branch
   * 15 org.jbehave.core.reporters.FilePrintStreamFactory.createPrintStream()Ljava/io/PrintStream;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      FilePrintStreamFactory.ResolveToPackagedName filePrintStreamFactory_ResolveToPackagedName0 = new FilePrintStreamFactory.ResolveToPackagedName();
      StoryLocation storyLocation0 = new StoryLocation((URL) null, "");
      FilePrintStreamFactory.FileConfiguration filePrintStreamFactory_FileConfiguration0 = new FilePrintStreamFactory.FileConfiguration();
      String string0 = filePrintStreamFactory_ResolveToPackagedName0.resolveName(storyLocation0, "");
      String string1 = filePrintStreamFactory_FileConfiguration0.getExtension();
      String string2 = filePrintStreamFactory_ResolveToPackagedName0.resolveName(storyLocation0, "8y7|}TKG/R");
      FilePrintStreamFactory filePrintStreamFactory0 = new FilePrintStreamFactory(storyLocation0, filePrintStreamFactory_FileConfiguration0);
      // Undeclared exception!
      try {
        filePrintStreamFactory0.createPrintStream();
      }catch(FilePrintStreamFactory.PrintStreamCreationFailed e) {
        /*
         * Failed to create print stream for file null
         */
        /*
      %%%<ex><className val="PrintStreamCreationFailed"/><stackDepth val="18"/><causeDepth val="1"/><source val="org.jbehave.core.io.CodeLocations.getPathFromURL(CodeLocations.java:77)"/></ex>%%%
         */
      }
  }

  //Test case number: 2
  /*
   * 9 covered goals:
   * 1 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>()V: root-Branch
   * 2 org.jbehave.core.reporters.FilePrintStreamFactory$AbstractPathResolver.<init>()V: root-Branch
   * 3 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;)V: root-Branch
   * 4 org.jbehave.core.reporters.FilePrintStreamFactory.configuration()Lorg/jbehave/core/reporters/FilePrintStreamFactory$FileConfiguration;: root-Branch
   * 5 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FilePathResolver;)V: root-Branch
   * 6 org.jbehave.core.reporters.FilePrintStreamFactory$PrintStreamCreationFailed.<init>(Lorg/jbehave/core/reporters/FilePrintStreamFactory;Ljava/io/File;Ljava/lang/Exception;)V: root-Branch
   * 7 org.jbehave.core.reporters.FilePrintStreamFactory$ResolveToPackagedName.<init>()V: root-Branch
   * 8 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;)V: root-Branch
   * 9 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FileConfiguration;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      String string0 = "Dm5+\"E";
      File file0 = new File("Dm5+\"E", "Dm5+\"E");
      boolean boolean0 = true;
      StoryLocation storyLocation0 = new StoryLocation((URL) null, "Dm5+\"E");
      FilePrintStreamFactory filePrintStreamFactory0 = new FilePrintStreamFactory(storyLocation0);
      FilePrintStreamFactory.FileConfiguration filePrintStreamFactory_FileConfiguration0 = filePrintStreamFactory0.configuration();
      Exception exception0 = new Exception((Throwable) null);
      FilePrintStreamFactory.FilePrintStream filePrintStreamFactory_FilePrintStream0 = null;
      try {
        filePrintStreamFactory_FilePrintStream0 = new FilePrintStreamFactory.FilePrintStream(file0, true);
      }catch(Throwable e) {
        /*
         * Security manager blocks (java.io.FilePermission Dm5+\"E/Dm5+\"E write)
         * java.lang.Thread.getStackTrace(Thread.java:1495)
         * org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:303)
         * java.lang.SecurityManager.checkWrite(SecurityManager.java:979)
         * java.io.FileOutputStream.<init>(FileOutputStream.java:198)
         * org.jbehave.core.reporters.FilePrintStreamFactory$FilePrintStream.<init>(FilePrintStreamFactory.java:122)
         * sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)
         * sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
         * java.lang.reflect.Constructor.newInstance(Constructor.java:532)
         * org.evosuite.testcase.ConstructorStatement$1.execute(ConstructorStatement.java:226)
         * org.evosuite.testcase.AbstractStatement.exceptionHandler(AbstractStatement.java:142)
         * org.evosuite.testcase.ConstructorStatement.execute(ConstructorStatement.java:188)
         * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:291)
         * org.evosuite.testcase.TestRunnable.call(TestRunnable.java:1)
         * java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
         * java.util.concurrent.FutureTask.run(FutureTask.java:166)
         * java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
         * java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
         * java.lang.Thread.run(Thread.java:679)
         */
        /*
      %%%<ex><className val="SecurityException"/><stackDepth val="17"/><causeDepth val="0"/><source val="org.evosuite.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:307)"/></ex>%%%
         */
      }
  }

  //Test case number: 3
  /*
   * 11 covered goals:
   * 1 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>()V: root-Branch
   * 2 org.jbehave.core.reporters.FilePrintStreamFactory$AbstractPathResolver.<init>()V: root-Branch
   * 3 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;)V: root-Branch
   * 4 org.jbehave.core.reporters.FilePrintStreamFactory$ResolveToSimpleName.<init>()V: root-Branch
   * 5 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FilePathResolver;)V: root-Branch
   * 6 org.jbehave.core.reporters.FilePrintStreamFactory$PrintStreamCreationFailed.<init>(Lorg/jbehave/core/reporters/FilePrintStreamFactory;Ljava/io/File;Ljava/lang/Exception;)V: root-Branch
   * 7 org.jbehave.core.reporters.FilePrintStreamFactory$ResolveToPackagedName.<init>()V: root-Branch
   * 8 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;)V: root-Branch
   * 9 org.jbehave.core.reporters.FilePrintStreamFactory$AbstractPathResolver.resolveDirectory(Lorg/jbehave/core/io/StoryLocation;Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * 10 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FileConfiguration;)V: root-Branch
   * 11 org.jbehave.core.reporters.FilePrintStreamFactory$ResolveToSimpleName.resolveName(Lorg/jbehave/core/io/StoryLocation;Ljava/lang/String;)Ljava/lang/String;: I10 Branch 2 IFEQ L108 - true
   */
  @Test
  public void test3()  throws Throwable  {
      FilePrintStreamFactory.ResolveToSimpleName filePrintStreamFactory_ResolveToSimpleName0 = new FilePrintStreamFactory.ResolveToSimpleName();
      FilePrintStreamFactory filePrintStreamFactory0 = new FilePrintStreamFactory((StoryLocation) null);
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[10];
      stackTraceElementArray0[2] = null;
      StoryLocation storyLocation0 = new StoryLocation((URL) null, "@A");
      String string0 = filePrintStreamFactory_ResolveToSimpleName0.resolveName(storyLocation0, "");
      StoryLocation storyLocation1 = new StoryLocation((URL) null, "@A");
      // Undeclared exception!
      try {
        filePrintStreamFactory_ResolveToSimpleName0.resolveDirectory(storyLocation1, "@A.");
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="15"/><causeDepth val="0"/><source val="org.jbehave.core.io.CodeLocations.getPathFromURL(CodeLocations.java:77)"/></ex>%%%
         */
      }
  }

  //Test case number: 6
  /*
   * 9 covered goals:
   * 1 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>()V: root-Branch
   * 2 org.jbehave.core.reporters.FilePrintStreamFactory$AbstractPathResolver.<init>()V: root-Branch
   * 3 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;)V: root-Branch
   * 4 org.jbehave.core.reporters.FilePrintStreamFactory.getOutputFile()Ljava/io/File;: root-Branch
   * 5 org.jbehave.core.reporters.FilePrintStreamFactory$FileConfiguration.<init>(Ljava/lang/String;Ljava/lang/String;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FilePathResolver;)V: root-Branch
   * 6 org.jbehave.core.reporters.FilePrintStreamFactory$PrintStreamCreationFailed.<init>(Lorg/jbehave/core/reporters/FilePrintStreamFactory;Ljava/io/File;Ljava/lang/Exception;)V: root-Branch
   * 7 org.jbehave.core.reporters.FilePrintStreamFactory$ResolveToPackagedName.<init>()V: root-Branch
   * 8 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;)V: root-Branch
   * 9 org.jbehave.core.reporters.FilePrintStreamFactory.<init>(Lorg/jbehave/core/io/StoryLocation;Lorg/jbehave/core/reporters/FilePrintStreamFactory$FileConfiguration;)V: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      String string0 = "(VuO]Ls_WaA";
      StoryLocation storyLocation0 = new StoryLocation((URL) null, "(VuO]Ls_WaA");
      FilePrintStreamFactory filePrintStreamFactory0 = new FilePrintStreamFactory(storyLocation0);
      File file0 = filePrintStreamFactory0.getOutputFile();
      // Undeclared exception!
      try {
        storyLocation0.getURL();
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.io.StoryLocation.getURL(StoryLocation.java:41)"/></ex>%%%
         */
      }
  }
}
