/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.reporters;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.File;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import org.jbehave.core.configuration.Configuration;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.configuration.ParanamerConfiguration;
import org.jbehave.core.configuration.UnmodifiableConfiguration;
import org.jbehave.core.failures.FailureStrategy;
import org.jbehave.core.failures.PendingStepStrategy;
import org.jbehave.core.i18n.LocalizedKeywords;
import org.jbehave.core.io.LoadFromClasspath;
import org.jbehave.core.io.ResourceLoader;
import org.jbehave.core.model.ExamplesTable;
import org.jbehave.core.model.ExamplesTableFactory;
import org.jbehave.core.model.Meta;
import org.jbehave.core.model.TableTransformers;
import org.jbehave.core.reporters.FreemarkerProcessor;
import org.jbehave.core.reporters.HtmlTemplateOutput;
import org.jbehave.core.reporters.TemplateProcessor;
import org.jbehave.core.steps.ParameterConverters;


public class HtmlTemplateOutputEvoSuiteTest {


  //Test case number: 0  @Test
  public void test0()  throws Throwable  {
      String string0 = "";
      File file0 = new File("", "");
      File file1 = file0.getAbsoluteFile();
      File file2 = file1.getParentFile();
      File file3 = new File((File) null, "");
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@1364b53
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="25"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 1  @Test
  public void test1()  throws Throwable  {
      File file0 = null;
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@1364b53
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="25"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }
}
