/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.reporters;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.File;
import java.io.PrintStream;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import org.jbehave.core.configuration.Configuration;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.configuration.ParanamerConfiguration;
import org.jbehave.core.configuration.PropertyBasedConfiguration;
import org.jbehave.core.configuration.UnmodifiableConfiguration;
import org.jbehave.core.i18n.LocalizedKeywords;
import org.jbehave.core.io.StoryLocation;
import org.jbehave.core.model.ExamplesTable;
import org.jbehave.core.reporters.ANSIConsoleOutput;
import org.jbehave.core.reporters.CrossReference;
import org.jbehave.core.reporters.FilePrintStreamFactory;
import org.jbehave.core.reporters.Format;
import org.jbehave.core.reporters.FreemarkerProcessor;
import org.jbehave.core.reporters.IdeOnlyConsoleOutput;
import org.jbehave.core.reporters.PrintStreamOutput;
import org.jbehave.core.reporters.StepFailureDecorator;
import org.jbehave.core.reporters.StoryReporter;
import org.jbehave.core.reporters.StoryReporterBuilder;
import org.jbehave.core.reporters.TemplateProcessor;
import org.jbehave.core.reporters.TemplateableOutput;
import org.jbehave.core.reporters.XmlOutput;
import org.jbehave.core.steps.ChainedRow;
import org.jbehave.core.steps.ConvertedParameters;
import org.jbehave.core.steps.ParameterControls;
import org.jbehave.core.steps.ParameterConverters;
import org.jbehave.core.steps.Parameters;
import org.jbehave.core.steps.Row;


public class StoryReporterBuilderEvoSuiteTest {


  //Test case number: 0  @Test
  public void test0()  throws Throwable  {
      StoryLocation storyLocation0 = null;
      FilePrintStreamFactory filePrintStreamFactory0 = new FilePrintStreamFactory((StoryLocation) null);
      FilePrintStreamFactory.FileConfiguration filePrintStreamFactory_FileConfiguration0 = filePrintStreamFactory0.configuration();
      FilePrintStreamFactory filePrintStreamFactory1 = new FilePrintStreamFactory((StoryLocation) null, filePrintStreamFactory_FileConfiguration0);
      File file0 = filePrintStreamFactory1.getOutputFile();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      Keywords keywords0 = null;
      try {
        keywords0 = new Keywords((Map<String, String>) hashMap0);
      }catch(Keywords.KeywordNotFound e) {
        /*
         * Keyword Meta not found amongst {}
         */
        /*
      %%%<ex><className val="KeywordNotFound"/><stackDepth val="16"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.keyword(Keywords.java:225)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.jbehave.core.reporters.StoryReporterBuilder.<init>()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      StoryReporterBuilder storyReporterBuilder0 = null;
      try {
        storyReporterBuilder0 = new StoryReporterBuilder();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@8777c
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="23"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 2  @Test
  public void test2()  throws Throwable  {
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@8777c
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="25"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 3  @Test
  public void test3()  throws Throwable  {
      PropertyBasedConfiguration propertyBasedConfiguration0 = null;
      try {
        propertyBasedConfiguration0 = new PropertyBasedConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@8777c
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="25"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }
}
