/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.trie.analyzer;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer;
import org.junit.BeforeClass;

public class StringKeyAnalyzerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 5 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.mask(I)I: root-Branch
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.<init>()V: root-Branch
   * 3 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isBitSet(Ljava/lang/String;II)Z: I3 Branch 13 IFNULL L111 - false
   * 4 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isBitSet(Ljava/lang/String;II)Z: I6 Branch 14 IF_ICMPLT L111 - true
   * 5 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isBitSet(Ljava/lang/String;II)Z: I31 Branch 15 IFEQ L118 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1223,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test0");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      boolean boolean0 = stringKeyAnalyzer0.isBitSet("!@", (-2), 0);
      assertEquals(false, boolean0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.lengthInBits(Ljava/lang/String;)I: I3 Branch 1 IFNULL L50 - true
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1224,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test1");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.lengthInBits((String) null);
      assertEquals(0, int0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.lengthInBits(Ljava/lang/String;)I: I3 Branch 1 IFNULL L50 - false
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1230,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test2");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.lengthInBits("3");
      assertEquals(16, int0);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I9 Branch 2 IFNE L58 - true
   */

  @Test
  public void test3()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1231,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test3");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      // Undeclared exception!
      try {
        stringKeyAnalyzer0.bitIndex("", 487, 487, "", 487, 487);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The offsets and lengths must be at Character boundaries
         //
      }
  }

  //Test case number: 4
  /*
   * 15 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I9 Branch 2 IFNE L58 - false
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I13 Branch 3 IFNE L58 - false
   * 3 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I17 Branch 4 IFNE L58 - false
   * 4 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I21 Branch 5 IFEQ L58 - true
   * 5 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I77 Branch 6 IF_ICMPGE L75 - true
   * 6 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I77 Branch 6 IF_ICMPGE L75 - false
   * 7 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I94 Branch 7 IF_ICMPLT L79 - true
   * 8 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I94 Branch 7 IF_ICMPLT L79 - false
   * 9 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I109 Branch 8 IFNULL L85 - false
   * 10 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I112 Branch 9 IF_ICMPLT L85 - true
   * 11 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I112 Branch 9 IF_ICMPLT L85 - false
   * 12 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I128 Branch 10 IF_ICMPEQ L91 - true
   * 13 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I149 Branch 11 IFEQ L96 - true
   * 14 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I149 Branch 11 IFEQ L96 - false
   * 15 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I161 Branch 12 IFEQ L102 - true
   */

  @Test
  public void test4()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1232,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test4");
      StringKeyAnalyzer stringKeyAnalyzer0 = StringKeyAnalyzer.INSTANCE;
      int int0 = stringKeyAnalyzer0.bitIndex("owsAF6", 16, 16, "owsAF6", 16, 16);
      assertEquals((-2), int0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I13 Branch 3 IFNE L58 - true
   */

  @Test
  public void test5()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1233,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test5");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      // Undeclared exception!
      try {
        stringKeyAnalyzer0.bitIndex("Cannot determine prefix outside of Character boundaries", 0, (-817), "Cannot determine prefix outside of Character boundaries", (-817), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The offsets and lengths must be at Character boundaries
         //
      }
  }

  //Test case number: 6
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I17 Branch 4 IFNE L58 - true
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I161 Branch 12 IFEQ L102 - false
   */

  @Test
  public void test6()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1234,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test6");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      stringKeyAnalyzer0.bitIndex("3", 32768, 0, "3", 0, 0);
      stringKeyAnalyzer0.compare("3", "3");
      // Undeclared exception!
      try {
        stringKeyAnalyzer0.bitIndex("3", 0, (-1), "3", 0, (-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The offsets and lengths must be at Character boundaries
         //
      }
  }

  //Test case number: 7
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I21 Branch 5 IFEQ L58 - false
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitsPerElement()I: root-Branch
   */

  @Test
  public void test7()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1235,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test7");
      StringKeyAnalyzer stringKeyAnalyzer0 = StringKeyAnalyzer.INSTANCE;
      int int0 = stringKeyAnalyzer0.bitsPerElement();
      assertEquals(16, int0);
      
      // Undeclared exception!
      try {
        stringKeyAnalyzer0.bitIndex("|<|~$o3p}", 16, 16, "|<|~$o3p}", 16, 1601);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The offsets and lengths must be at Character boundaries
         //
      }
  }

  //Test case number: 8
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I128 Branch 10 IF_ICMPEQ L91 - false
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I94 Branch 7 IF_ICMPLT L79 - true
   */

  @Test
  public void test8()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1236,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test8");
      StringKeyAnalyzer stringKeyAnalyzer0 = StringKeyAnalyzer.INSTANCE;
      stringKeyAnalyzer0.bitsPerElement();
      stringKeyAnalyzer0.compare("|<|~$o3p}", "|<|~$o3p}");
      int int0 = stringKeyAnalyzer0.bitIndex("|<|~$o3p}", 0, 16, "|<|~$o3p}", 0, 0);
      assertEquals(9, int0);
  }

  //Test case number: 9
  /*
   * 13 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isBitSet(Ljava/lang/String;II)Z: I3 Branch 13 IFNULL L111 - true
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I9 Branch 2 IFNE L58 - false
   * 3 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I13 Branch 3 IFNE L58 - false
   * 4 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I17 Branch 4 IFNE L58 - false
   * 5 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I21 Branch 5 IFEQ L58 - true
   * 6 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I77 Branch 6 IF_ICMPGE L75 - true
   * 7 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I77 Branch 6 IF_ICMPGE L75 - false
   * 8 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I94 Branch 7 IF_ICMPLT L79 - false
   * 9 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I109 Branch 8 IFNULL L85 - false
   * 10 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I112 Branch 9 IF_ICMPLT L85 - false
   * 11 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I128 Branch 10 IF_ICMPEQ L91 - true
   * 12 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I149 Branch 11 IFEQ L96 - true
   * 13 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitIndex(Ljava/lang/String;IILjava/lang/String;II)I: I161 Branch 12 IFEQ L102 - false
   */

  @Test
  public void test9()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1237,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test9");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.bitIndex("3", 32768, 0, "3", 0, 0);
      assertEquals((-1), int0);
      
      boolean boolean0 = stringKeyAnalyzer0.isBitSet((String) null, (-1), 0);
      assertEquals(false, boolean0);
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isBitSet(Ljava/lang/String;II)Z: I6 Branch 14 IF_ICMPLT L111 - false
   */

  @Test
  public void test10()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1225,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test10");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.bitsPerElement();
      assertEquals(16, int0);
      
      boolean boolean0 = stringKeyAnalyzer0.isBitSet("2>.5}S\"rO?cMW o{", 16, 16);
      assertEquals(false, boolean0);
  }

  //Test case number: 11
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isBitSet(Ljava/lang/String;II)Z: I31 Branch 15 IFEQ L118 - false
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.mask(I)I: root-Branch
   * 3 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isBitSet(Ljava/lang/String;II)Z: I3 Branch 13 IFNULL L111 - false
   * 4 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isBitSet(Ljava/lang/String;II)Z: I6 Branch 14 IF_ICMPLT L111 - true
   */

  @Test
  public void test11()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1226,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test11");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      boolean boolean0 = stringKeyAnalyzer0.isBitSet("e9A*Ks*mIb~D'/sG6", 153, 1763);
      assertEquals(true, boolean0);
  }

  //Test case number: 12
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isPrefix(Ljava/lang/String;IILjava/lang/String;)Z: I5 Branch 16 IFNE L123 - true
   */

  @Test
  public void test12()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1227,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test12");
      StringKeyAnalyzer stringKeyAnalyzer0 = StringKeyAnalyzer.INSTANCE;
      // Undeclared exception!
      try {
        stringKeyAnalyzer0.isPrefix("", (-589), (-589), "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot determine prefix outside of Character boundaries
         //
      }
  }

  //Test case number: 13
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isPrefix(Ljava/lang/String;IILjava/lang/String;)Z: I5 Branch 16 IFNE L123 - false
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isPrefix(Ljava/lang/String;IILjava/lang/String;)Z: I9 Branch 17 IFEQ L123 - false
   */

  @Test
  public void test13()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1228,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test13");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      // Undeclared exception!
      try {
        stringKeyAnalyzer0.isPrefix("!@", 0, (-2), "!@");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot determine prefix outside of Character boundaries
         //
      }
  }

  //Test case number: 14
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isPrefix(Ljava/lang/String;IILjava/lang/String;)Z: I9 Branch 17 IFEQ L123 - true
   * 2 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.bitsPerElement()I: root-Branch
   * 3 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.<init>()V: root-Branch
   * 4 org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzer.isPrefix(Ljava/lang/String;IILjava/lang/String;)Z: I5 Branch 16 IFNE L123 - false
   */

  @Test
  public void test14()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1229,"org.apache.commons.collections4.trie.analyzer.StringKeyAnalyzerEvoSuiteTest.test14");
      StringKeyAnalyzer stringKeyAnalyzer0 = new StringKeyAnalyzer();
      int int0 = stringKeyAnalyzer0.bitsPerElement();
      assertEquals(16, int0);
      
      boolean boolean0 = stringKeyAnalyzer0.isPrefix("2>.5}S\"rO?cMW o{", 16, 16, "2>.5}S\"rO?cMW o{");
      assertEquals(true, boolean0);
  }
}
