/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.steps;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;
import org.jbehave.core.io.LoadFromRelativeFile;
import org.jbehave.core.steps.ConvertedParameters;
import org.jbehave.core.steps.ParameterConverters;
import org.jbehave.core.steps.Row;


public class ConvertedParametersEvoSuiteTest {


  //Test case number: 0
  /*
   * 7 covered goals:
   * 1 org.jbehave.core.steps.ConvertedParameters$ValueNotFound.<init>(Ljava/lang/String;)V: root-Branch
   * 2 org.jbehave.core.steps.ConvertedParameters.<init>(Ljava/util/Map;Lorg/jbehave/core/steps/ParameterConverters;)V: root-Branch
   * 3 org.jbehave.core.steps.ConvertedParameters.valueAs(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;: root-Branch
   * 4 org.jbehave.core.steps.ConvertedParameters.valueFor(Ljava/lang/String;)Ljava/lang/String;: I6 Branch 2 IFGT L51 - false
   * 5 org.jbehave.core.steps.ConvertedParameters.valueAs(Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object;: I6 Branch 1 IFLE L40 - true
   * 6 org.jbehave.core.steps.ConvertedParameters.values()Ljava/util/Map;: root-Branch
   * 7 org.jbehave.core.steps.ConvertedParameters.<init>(Lorg/jbehave/core/steps/Row;Lorg/jbehave/core/steps/ParameterConverters;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      ConvertedParameters convertedParameters0 = new ConvertedParameters((Map<String, String>) hashMap0, (ParameterConverters) null);
      ConvertedParameters convertedParameters1 = new ConvertedParameters((Map<String, String>) hashMap0, (ParameterConverters) null);
      ConvertedParameters convertedParameters2 = new ConvertedParameters((Row) convertedParameters1, (ParameterConverters) null);
      Class<?> class0 = LoadFromRelativeFile.StoryFilePath.class;
      String string0 = convertedParameters0.valueAs("+D,$P", (Class<String>) class0, "+D,$P");
      String string1 = convertedParameters0.valueAs("+D,$P", (Class<String>) class0, "+D,$P");
      // Undeclared exception!
      try {
        convertedParameters0.valueAs("+D,$P", (Class<Object>) class0);
      }catch(ConvertedParameters.ValueNotFound e) {
        /*
         * +D,$P
         */
        /*
      %%%<ex><className val="ValueNotFound"/><stackDepth val="15"/><causeDepth val="0"/><source val="org.jbehave.core.steps.ConvertedParameters.valueFor(ConvertedParameters.java:52)"/></ex>%%%
         */
      }
  }
}
