/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.steps;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.net.InetAddress;
import java.net.InterfaceAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Currency;
import java.util.GregorianCalendar;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Properties;
import org.jbehave.core.annotations.ScenarioType;
import org.jbehave.core.configuration.Configuration;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.configuration.MostUsefulConfiguration;
import org.jbehave.core.configuration.ParanamerConfiguration;
import org.jbehave.core.configuration.PropertyBasedConfiguration;
import org.jbehave.core.configuration.UnmodifiableConfiguration;
import org.jbehave.core.failures.FailureStrategy;
import org.jbehave.core.i18n.LocalizedKeywords;
import org.jbehave.core.model.ExamplesTable;
import org.jbehave.core.model.GivenStories;
import org.jbehave.core.model.GivenStory;
import org.jbehave.core.model.Meta;
import org.jbehave.core.model.OutcomesTable;
import org.jbehave.core.model.Scenario;
import org.jbehave.core.model.Story;
import org.jbehave.core.reporters.ANSIConsoleOutput;
import org.jbehave.core.steps.BeforeOrAfterStep;
import org.jbehave.core.steps.CandidateSteps;
import org.jbehave.core.steps.ChainedRow;
import org.jbehave.core.steps.CompositeStepsFactory;
import org.jbehave.core.steps.ConvertedParameters;
import org.jbehave.core.steps.InjectableStepsFactory;
import org.jbehave.core.steps.InstanceStepsFactory;
import org.jbehave.core.steps.MarkUnmatchedStepsAsPending;
import org.jbehave.core.steps.ParameterConverters;
import org.jbehave.core.steps.Parameters;
import org.jbehave.core.steps.ProvidedStepsFactory;
import org.jbehave.core.steps.Row;
import org.jbehave.core.steps.Step;
import org.jbehave.core.steps.StepCandidate;
import org.jbehave.core.steps.StepCollector;
import org.jbehave.core.steps.StepFinder;
import org.jbehave.core.steps.StepMonitor;
import org.jbehave.core.steps.Steps;


public class MarkUnmatchedStepsAsPendingEvoSuiteTest {


  //Test case number: 0  @Test
  public void test0()  throws Throwable  {
      MarkUnmatchedStepsAsPending markUnmatchedStepsAsPending0 = null;
      try {
        markUnmatchedStepsAsPending0 = new MarkUnmatchedStepsAsPending();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@3b0b1e
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="23"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 1  @Test
  public void test1()  throws Throwable  {
      MostUsefulConfiguration mostUsefulConfiguration0 = null;
      try {
        mostUsefulConfiguration0 = new MostUsefulConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@3b0b1e
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="23"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 2  @Test
  public void test2()  throws Throwable  {
      MarkUnmatchedStepsAsPending markUnmatchedStepsAsPending0 = null;
      try {
        markUnmatchedStepsAsPending0 = new MarkUnmatchedStepsAsPending();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@3b0b1e
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="23"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 3  @Test
  public void test3()  throws Throwable  {
      StepFinder.ByLevenshteinDistance stepFinder_ByLevenshteinDistance0 = new StepFinder.ByLevenshteinDistance();
      StepFinder stepFinder0 = new StepFinder((StepFinder.PrioritisingStrategy) stepFinder_ByLevenshteinDistance0);
      MarkUnmatchedStepsAsPending markUnmatchedStepsAsPending0 = null;
      try {
        markUnmatchedStepsAsPending0 = new MarkUnmatchedStepsAsPending(stepFinder0);
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@3b0b1e
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="22"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 4  @Test
  public void test4()  throws Throwable  {
      PropertyBasedConfiguration propertyBasedConfiguration0 = null;
      try {
        propertyBasedConfiguration0 = new PropertyBasedConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@3b0b1e
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="24"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 5
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.steps.MarkUnmatchedStepsAsPending.<init>(Lorg/jbehave/core/steps/StepFinder;Lorg/jbehave/core/configuration/Keywords;)V: root-Branch
   * 2 org.jbehave.core.steps.MarkUnmatchedStepsAsPending.<init>(Lorg/jbehave/core/configuration/Keywords;)V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      StepFinder stepFinder0 = null;
      MarkUnmatchedStepsAsPending markUnmatchedStepsAsPending0 = new MarkUnmatchedStepsAsPending((Keywords) null);
      PropertyBasedConfiguration propertyBasedConfiguration0 = null;
      try {
        propertyBasedConfiguration0 = new PropertyBasedConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@3b0b1e
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="24"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 6  @Test
  public void test6()  throws Throwable  {
      MostUsefulConfiguration mostUsefulConfiguration0 = null;
      try {
        mostUsefulConfiguration0 = new MostUsefulConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@3b0b1e
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="23"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 7  @Test
  public void test7()  throws Throwable  {
      StepFinder.ByLevenshteinDistance stepFinder_ByLevenshteinDistance0 = new StepFinder.ByLevenshteinDistance();
      StepFinder stepFinder0 = new StepFinder((StepFinder.PrioritisingStrategy) stepFinder_ByLevenshteinDistance0);
      MarkUnmatchedStepsAsPending markUnmatchedStepsAsPending0 = null;
      try {
        markUnmatchedStepsAsPending0 = new MarkUnmatchedStepsAsPending(stepFinder0);
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@3b0b1e
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="22"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }
}
