/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.steps;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.Map;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.steps.PendingStepMethodGenerator;
import org.jbehave.core.steps.StepCreator;


public class PendingStepMethodGeneratorEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.steps.PendingStepMethodGenerator.<init>(Lorg/jbehave/core/configuration/Keywords;)V: root-Branch
   * 2 org.jbehave.core.steps.PendingStepMethodGenerator.generateMethod(Lorg/jbehave/core/steps/StepCreator$PendingStep;)Ljava/lang/String;: I20 Branch 1 IFEQ L17 - true
   */
  @Test
  public void test0()  throws Throwable  {
      Map<String, String> map0 = Keywords.defaultKeywords();
      Keywords keywords0 = new Keywords(map0);
      PendingStepMethodGenerator pendingStepMethodGenerator0 = new PendingStepMethodGenerator(keywords0);
      StepCreator.PendingStep stepCreator_PendingStep0 = new StepCreator.PendingStep("fwS' tgi,sRP`YA$`", "fwS' tgi,sRP`YA$`");
      // Undeclared exception!
      try {
        pendingStepMethodGenerator0.generateMethod(stepCreator_PendingStep0);
      }catch(Keywords.StartingWordNotFound e) {
        /*
         * No starting word found for step 'fwS' tgi,sRP`YA$`' amongst '{AND=And, GIVEN=Given, THEN=Then, IGNORABLE=!--, WHEN=When}'
         */
        /*
      %%%<ex><className val="StartingWordNotFound"/><stackDepth val="15"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.stepTypeFor(Keywords.java:411)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.steps.PendingStepMethodGenerator.<init>(Lorg/jbehave/core/configuration/Keywords;)V: root-Branch
   * 2 org.jbehave.core.steps.PendingStepMethodGenerator.generateMethod(Lorg/jbehave/core/steps/StepCreator$PendingStep;)Ljava/lang/String;: I20 Branch 1 IFEQ L17 - true
   */
  @Test
  public void test1()  throws Throwable  {
      Map<String, String> map0 = Keywords.defaultKeywords();
      Keywords keywords0 = new Keywords(map0);
      PendingStepMethodGenerator pendingStepMethodGenerator0 = new PendingStepMethodGenerator(keywords0);
      StepCreator.PendingStep stepCreator_PendingStep0 = new StepCreator.PendingStep("java.awt.printerjob", "java.awt.printerjob");
      // Undeclared exception!
      try {
        pendingStepMethodGenerator0.generateMethod(stepCreator_PendingStep0);
      }catch(Keywords.StartingWordNotFound e) {
        /*
         * No starting word found for step 'java.awt.printerjob' amongst '{AND=And, GIVEN=Given, THEN=Then, IGNORABLE=!--, WHEN=When}'
         */
        /*
      %%%<ex><className val="StartingWordNotFound"/><stackDepth val="15"/><causeDepth val="0"/><source val="org.jbehave.core.configuration.Keywords.stepTypeFor(Keywords.java:411)"/></ex>%%%
         */
      }
  }
}
