/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.steps;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jbehave.core.steps.StepCandidate;
import org.jbehave.core.steps.Stepdoc;


public class StepdocEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.jbehave.core.steps.Stepdoc.<init>(Lorg/jbehave/core/steps/StepCandidate;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Stepdoc stepdoc0 = null;
      try {
        stepdoc0 = new Stepdoc((StepCandidate) null);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.steps.Stepdoc.&lt;init&gt;(Stepdoc.java:27)"/></ex>%%%
         */
      }
  }
}
