/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.steps;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.io.OutputStream;
import java.io.PrintStream;
import java.lang.reflect.Method;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import org.evosuite.testcase.CodeUnderTestException;
import org.jbehave.core.configuration.Configuration;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.configuration.ParanamerConfiguration;
import org.jbehave.core.configuration.PropertyBasedConfiguration;
import org.jbehave.core.configuration.UnmodifiableConfiguration;
import org.jbehave.core.i18n.LocalizedKeywords;
import org.jbehave.core.model.ExamplesTable;
import org.jbehave.core.model.ExamplesTableFactory;
import org.jbehave.core.model.GivenStories;
import org.jbehave.core.model.GivenStory;
import org.jbehave.core.model.Meta;
import org.jbehave.core.model.OutcomesTable;
import org.jbehave.core.model.Scenario;
import org.jbehave.core.model.TableTransformers;
import org.jbehave.core.reporters.StoryReporter;
import org.jbehave.core.reporters.XmlOutput;
import org.jbehave.core.steps.BeforeOrAfterStep;
import org.jbehave.core.steps.CandidateSteps;
import org.jbehave.core.steps.ConvertedParameters;
import org.jbehave.core.steps.InjectableStepsFactory;
import org.jbehave.core.steps.InstanceStepsFactory;
import org.jbehave.core.steps.ParameterControls;
import org.jbehave.core.steps.ParameterConverters;
import org.jbehave.core.steps.Parameters;
import org.jbehave.core.steps.Row;
import org.jbehave.core.steps.StepCandidate;
import org.jbehave.core.steps.StepFinder;
import org.jbehave.core.steps.Stepdoc;
import org.jbehave.core.steps.Steps;


public class StepFinderEvoSuiteTest {


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 org.jbehave.core.steps.StepFinder$ByPriorityField.<init>()V: root-Branch
   * 2 org.jbehave.core.steps.StepFinder.<init>()V: root-Branch
   * 3 org.jbehave.core.steps.StepFinder.<init>(Lorg/jbehave/core/steps/StepFinder$PrioritisingStrategy;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      StepFinder stepFinder0 = new StepFinder();
      StepFinder.ByPriorityField stepFinder_ByPriorityField0 = new StepFinder.ByPriorityField();
      StepFinder stepFinder1 = new StepFinder();
      List<CandidateSteps> list0 = null;
      // Undeclared exception!
      try {
        stepFinder1.stepsInstances((List<CandidateSteps>) null);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.steps.StepFinder.stepsInstances(StepFinder.java:84)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 org.jbehave.core.steps.StepFinder$ByLevenshteinDistance.prioritise(Ljava/lang/String;Ljava/util/List;)Ljava/util/List;: root-Branch
   * 2 org.jbehave.core.steps.StepFinder$ByLevenshteinDistance.<init>()V: root-Branch
   * 3 org.jbehave.core.steps.StepFinder$ByLevenshteinDistance$1.<init>(Lorg/jbehave/core/steps/StepFinder$ByLevenshteinDistance;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      StepFinder.ByLevenshteinDistance stepFinder_ByLevenshteinDistance0 = new StepFinder.ByLevenshteinDistance();
      String string0 = "z&1";
      List<StepCandidate> list0 = null;
      // Undeclared exception!
      try {
        stepFinder_ByLevenshteinDistance0.prioritise("z&1", (List<StepCandidate>) null);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="15"/><causeDepth val="0"/><source val="java.util.Collections.sort(Collections.java:175)"/></ex>%%%
         */
      }
  }

  //Test case number: 2  @Test
  public void test2()  throws Throwable  {
      ParanamerConfiguration paranamerConfiguration0 = null;
      try {
        paranamerConfiguration0 = new ParanamerConfiguration();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@823618
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="24"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.steps.StepFinder$ByPriorityField.<init>()V: root-Branch
   * 2 org.jbehave.core.steps.StepFinder.<init>(Lorg/jbehave/core/steps/StepFinder$PrioritisingStrategy;)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      StepFinder.ByPriorityField stepFinder_ByPriorityField0 = new StepFinder.ByPriorityField();
      ExamplesTable examplesTable0 = null;
      try {
        examplesTable0 = ExamplesTable.EMPTY;
      } catch(NoClassDefFoundError e) {}
  }

  //Test case number: 4
  /*
   * 3 covered goals:
   * 1 org.jbehave.core.steps.StepFinder$ByPriorityField.<init>()V: root-Branch
   * 2 org.jbehave.core.steps.StepFinder.<init>(Lorg/jbehave/core/steps/StepFinder$PrioritisingStrategy;)V: root-Branch
   * 3 org.jbehave.core.steps.StepFinder.collectCandidates(Ljava/util/List;)Ljava/util/List;: I28 Branch 6 IFNE L101 - true
   */
  @Test
  public void test4()  throws Throwable  {
      StepFinder.ByPriorityField stepFinder_ByPriorityField0 = new StepFinder.ByPriorityField();
      StepFinder stepFinder0 = new StepFinder((StepFinder.PrioritisingStrategy) stepFinder_ByPriorityField0);
      String string0 = "=B?Nu8X+!pI*Xq$C7Y";
      List<String> list0 = Keywords.KEYWORDS;
      List<String> list1 = ParameterConverters.trim(list0);
  }

  //Test case number: 5
  /*
   * 10 covered goals:
   * 1 org.jbehave.core.steps.StepFinder$ByPriorityField.<init>()V: root-Branch
   * 2 org.jbehave.core.steps.StepFinder.<init>()V: root-Branch
   * 3 org.jbehave.core.steps.StepFinder.<init>(Lorg/jbehave/core/steps/StepFinder$PrioritisingStrategy;)V: root-Branch
   * 4 org.jbehave.core.steps.StepFinder$ByPriorityField.prioritise(Ljava/lang/String;Ljava/util/List;)Ljava/util/List;: root-Branch
   * 5 org.jbehave.core.steps.StepFinder.prioritise(Ljava/lang/String;Ljava/util/List;)Ljava/util/List;: root-Branch
   * 6 org.jbehave.core.steps.StepFinder.collectCandidates(Ljava/util/List;)Ljava/util/List;: I28 Branch 6 IFNE L101 - false
   * 7 org.jbehave.core.steps.StepFinder.findMatching(Ljava/lang/String;Ljava/util/List;)Ljava/util/List;: I38 Branch 3 IFNE L67 - false
   * 8 org.jbehave.core.steps.StepFinder.stepdocs(Ljava/util/List;)Ljava/util/List;: I32 Branch 1 IFNE L49 - false
   * 9 org.jbehave.core.steps.StepFinder.stepsInstances(Ljava/util/List;)Ljava/util/List;: I34 Branch 5 IFNE L84 - false
   * 10 org.jbehave.core.steps.StepFinder$ByPriorityField$1.<init>(Lorg/jbehave/core/steps/StepFinder$ByPriorityField;)V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      StepFinder stepFinder0 = new StepFinder();
      LinkedList<CandidateSteps> linkedList0 = new LinkedList<CandidateSteps>();
      List<Object> list0 = stepFinder0.stepsInstances((List<CandidateSteps>) linkedList0);
      List<Stepdoc> list1 = stepFinder0.findMatching("jov", (List<CandidateSteps>) linkedList0);
      List<Stepdoc> list2 = stepFinder0.findMatching((String) null, (List<CandidateSteps>) linkedList0);
      List<Stepdoc> list3 = stepFinder0.stepdocs((List<CandidateSteps>) linkedList0);
      List<StepCandidate> list4 = stepFinder0.collectCandidates((List<CandidateSteps>) linkedList0);
      // Undeclared exception!
      try {
        stepFinder0.prioritise("", (List<StepCandidate>) null);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="16"/><causeDepth val="0"/><source val="java.util.Collections.sort(Collections.java:175)"/></ex>%%%
         */
      }
  }

  //Test case number: 6
  /*
   * 9 covered goals:
   * 1 org.jbehave.core.steps.StepFinder$ByPriorityField.<init>()V: root-Branch
   * 2 org.jbehave.core.steps.StepFinder.<init>()V: root-Branch
   * 3 org.jbehave.core.steps.StepFinder.<init>(Lorg/jbehave/core/steps/StepFinder$PrioritisingStrategy;)V: root-Branch
   * 4 org.jbehave.core.steps.StepFinder$ByPriorityField.prioritise(Ljava/lang/String;Ljava/util/List;)Ljava/util/List;: root-Branch
   * 5 org.jbehave.core.steps.StepFinder.prioritise(Ljava/lang/String;Ljava/util/List;)Ljava/util/List;: root-Branch
   * 6 org.jbehave.core.steps.StepFinder.collectCandidates(Ljava/util/List;)Ljava/util/List;: I28 Branch 6 IFNE L101 - false
   * 7 org.jbehave.core.steps.StepFinder.findMatching(Ljava/lang/String;Ljava/util/List;)Ljava/util/List;: I38 Branch 3 IFNE L67 - false
   * 8 org.jbehave.core.steps.StepFinder.stepdocs(Ljava/util/List;)Ljava/util/List;: I32 Branch 1 IFNE L49 - false
   * 9 org.jbehave.core.steps.StepFinder.stepsInstances(Ljava/util/List;)Ljava/util/List;: I34 Branch 5 IFNE L84 - false
   */
  @Test
  public void test6()  throws Throwable  {
      StepFinder stepFinder0 = new StepFinder();
      LinkedList<CandidateSteps> linkedList0 = new LinkedList<CandidateSteps>();
      List<Object> list0 = stepFinder0.stepsInstances((List<CandidateSteps>) linkedList0);
      List<Stepdoc> list1 = stepFinder0.findMatching("jov", (List<CandidateSteps>) linkedList0);
      List<Stepdoc> list2 = stepFinder0.findMatching((String) null, (List<CandidateSteps>) linkedList0);
      List<Stepdoc> list3 = stepFinder0.stepdocs((List<CandidateSteps>) linkedList0);
      List<StepCandidate> list4 = stepFinder0.collectCandidates((List<CandidateSteps>) linkedList0);
      // Undeclared exception!
      try {
        stepFinder0.prioritise("", (List<StepCandidate>) null);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="16"/><causeDepth val="0"/><source val="java.util.Collections.sort(Collections.java:175)"/></ex>%%%
         */
      }
  }
}
