/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.lang.reflect.Type;
import java.util.List;
import org.jbehave.core.configuration.Configuration;
import org.jbehave.core.configuration.Keywords;
import org.jbehave.core.configuration.PropertyBasedConfiguration;
import org.jbehave.core.configuration.UnmodifiableConfiguration;
import org.jbehave.core.i18n.LocalizedKeywords;
import org.jbehave.core.io.LoadFromClasspath;
import org.jbehave.core.io.LoadFromURL;
import org.jbehave.core.io.ResourceLoader;
import org.jbehave.core.model.ExamplesTable;
import org.jbehave.core.model.ExamplesTableFactory;
import org.jbehave.core.model.OutcomesTable;
import org.jbehave.core.model.TableTransformers;
import org.jbehave.core.reporters.ANSIConsoleOutput;
import org.jbehave.core.steps.ParameterConverters;


public class ExamplesTableFactoryEvoSuiteTest {


  //Test case number: 0  @Test
  public void test0()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      ExamplesTableFactory examplesTableFactory0 = null;
      try {
        examplesTableFactory0 = new ExamplesTableFactory(keywords0);
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@c3601b
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="27"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.model.ExamplesTableFactory.<init>(Lorg/jbehave/core/configuration/Keywords;Lorg/jbehave/core/io/ResourceLoader;Lorg/jbehave/core/steps/ParameterConverters;Lorg/jbehave/core/model/TableTransformers;)V: root-Branch
   * 2 org.jbehave.core.model.ExamplesTableFactory.<init>(Lorg/jbehave/core/configuration/Keywords;Lorg/jbehave/core/io/ResourceLoader;Lorg/jbehave/core/steps/ParameterConverters;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      Keywords keywords0 = new Keywords();
      LoadFromURL loadFromURL0 = new LoadFromURL();
      ExamplesTableFactory examplesTableFactory0 = new ExamplesTableFactory(keywords0, (ResourceLoader) loadFromURL0, (ParameterConverters) null);
      ParameterConverters parameterConverters0 = null;
      try {
        parameterConverters0 = new ParameterConverters(true);
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@c3601b
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="25"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 2  @Test
  public void test2()  throws Throwable  {
      ExamplesTableFactory examplesTableFactory0 = null;
      try {
        examplesTableFactory0 = new ExamplesTableFactory((ParameterConverters) null);
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@c3601b
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="22"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 3  @Test
  public void test3()  throws Throwable  {
      Class<?> class0 = ExamplesTableFactory.class;
      LoadFromClasspath loadFromClasspath0 = new LoadFromClasspath(class0);
      ExamplesTableFactory examplesTableFactory0 = null;
      try {
        examplesTableFactory0 = new ExamplesTableFactory((ResourceLoader) loadFromClasspath0);
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@c3601b
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="22"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 4  @Test
  public void test4()  throws Throwable  {
      TableTransformers tableTransformers0 = new TableTransformers();
      String string0 = "[c`:\"P*Q,-W";
      TableTransformers.FromLandscape tableTransformers_FromLandscape0 = new TableTransformers.FromLandscape();
      tableTransformers0.useTransformer("[c`:\"P*Q,-W", (TableTransformers.TableTransformer) tableTransformers_FromLandscape0);
      ExamplesTableFactory examplesTableFactory0 = null;
      try {
        examplesTableFactory0 = new ExamplesTableFactory(tableTransformers0);
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@c3601b
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="22"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }

  //Test case number: 5  @Test
  public void test5()  throws Throwable  {
      ExamplesTableFactory examplesTableFactory0 = null;
      try {
        examplesTableFactory0 = new ExamplesTableFactory();
      }catch(LocalizedKeywords.ResourceBundleNotFound e) {
        /*
         * Resource bundle i18n/keywords not found for locale en in classLoader org.evosuite.instrumentation.InstrumentingClassLoader@c3601b
         */
        /*
      %%%<ex><className val="ResourceBundleNotFound"/><stackDepth val="22"/><causeDepth val="1"/><source val="java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1539)"/></ex>%%%
         */
      }
  }
}
