/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.Map;
import org.jbehave.core.model.GivenStory;


public class GivenStoryEvoSuiteTest {


  //Test case number: 0
  /*
   * 10 covered goals:
   * 1 org.jbehave.core.model.GivenStory.toString()Ljava/lang/String;: root-Branch
   * 2 org.jbehave.core.model.GivenStory.getAnchor()Ljava/lang/String;: root-Branch
   * 3 org.jbehave.core.model.GivenStory.<init>(Ljava/lang/String;)V: root-Branch
   * 4 org.jbehave.core.model.GivenStory.useParameters(Ljava/util/Map;)V: root-Branch
   * 5 org.jbehave.core.model.GivenStory.getParameters()Ljava/util/Map;: root-Branch
   * 6 org.jbehave.core.model.GivenStory.asString()Ljava/lang/String;: root-Branch
   * 7 org.jbehave.core.model.GivenStory.getPath()Ljava/lang/String;: root-Branch
   * 8 org.jbehave.core.model.GivenStory.parse()V: I18 Branch 1 IFLE L21 - true
   * 9 org.jbehave.core.model.GivenStory.hasAnchor()Z: I5 Branch 2 IFEQ L39 - false
   * 10 org.jbehave.core.model.GivenStory.parse()V: I18 Branch 1 IFLE L21 - false
   */
  @Test
  public void test0()  throws Throwable  {
      GivenStory givenStory0 = null;
      try {
        givenStory0 = new GivenStory("(.*)#{!.*?6%}");
      }catch(IllegalStateException e) {
        /*
         * No match found
         */
        /*
      %%%<ex><className val="IllegalStateException"/><stackDepth val="16"/><causeDepth val="0"/><source val="java.util.regex.Matcher.group(Matcher.java:485)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.model.GivenStory.<init>(Ljava/lang/String;)V: root-Branch
   * 2 org.jbehave.core.model.GivenStory.parse()V: I18 Branch 1 IFLE L21 - false
   */
  @Test
  public void test1()  throws Throwable  {
      GivenStory givenStory0 = null;
      try {
        givenStory0 = new GivenStory("q#{}");
      }catch(IllegalStateException e) {
        /*
         * No match found
         */
        /*
      %%%<ex><className val="IllegalStateException"/><stackDepth val="16"/><causeDepth val="0"/><source val="java.util.regex.Matcher.group(Matcher.java:485)"/></ex>%%%
         */
      }
  }
}
