/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import org.jbehave.core.io.StoryNameResolver;
import org.jbehave.core.io.UnderscoredToCapitalized;
import org.jbehave.core.model.Description;
import org.jbehave.core.model.Narrative;
import org.jbehave.core.model.Story;
import org.jbehave.core.model.StoryLanes;
import org.jbehave.core.model.StoryMap;
import org.jbehave.core.model.StoryMaps;


public class StoryLanesEvoSuiteTest {


  //Test case number: 1
  /*
   * 10 covered goals:
   * 1 org.jbehave.core.model.StoryLanes.<init>(Lorg/jbehave/core/model/StoryMaps;Lorg/jbehave/core/io/StoryNameResolver;)V: root-Branch
   * 2 org.jbehave.core.model.StoryLanes.inLane(Ljava/lang/String;Lorg/jbehave/core/model/Story;)Z: I29 Branch 2 IFNE L37 - false
   * 3 org.jbehave.core.model.StoryLanes.laneStories(Ljava/lang/String;)Ljava/util/List;: I16 Branch 3 IFNONNULL L48 - false
   * 4 org.jbehave.core.model.StoryLanes.laneStories(Ljava/lang/String;)Ljava/util/List;: I41 Branch 4 IFNE L49 - false
   * 5 org.jbehave.core.model.StoryLanes.nameStories(Ljava/util/List;)V: I24 Branch 5 IFNE L60 - false
   * 6 org.jbehave.core.model.StoryLanes.laneStories(Ljava/lang/String;)Ljava/util/List;: I41 Branch 4 IFNE L49 - true
   * 7 org.jbehave.core.model.StoryLanes.laneStories(Ljava/lang/String;)Ljava/util/List;: I16 Branch 3 IFNONNULL L48 - true
   * 8 org.jbehave.core.model.StoryLanes.getLanes()Ljava/util/List;: root-Branch
   * 9 org.jbehave.core.model.StoryLanes$1.<init>(Lorg/jbehave/core/model/StoryLanes;)V: root-Branch
   * 10 org.jbehave.core.model.StoryLanes.getStories()Ljava/util/List;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      LinkedList<StoryMap> linkedList0 = new LinkedList<StoryMap>();
      LinkedHashSet<Story> linkedHashSet0 = new LinkedHashSet<Story>();
      StoryMap storyMap0 = new StoryMap("Ma", (Set<Story>) linkedHashSet0);
      boolean boolean0 = linkedList0.offer(storyMap0);
      StoryMaps storyMaps0 = new StoryMaps((List<StoryMap>) linkedList0);
      UnderscoredToCapitalized underscoredToCapitalized0 = new UnderscoredToCapitalized();
      StoryLanes storyLanes0 = new StoryLanes(storyMaps0, (StoryNameResolver) underscoredToCapitalized0);
      List<Story> list0 = storyLanes0.getStories();
      boolean boolean1 = storyLanes0.inLane("", (Story) null);
      boolean boolean2 = storyLanes0.inLane("Ma", (Story) null);
      String string0 = "1wM8R$0p8";
      List<String> list1 = storyLanes0.getLanes();
      Description description0 = new Description("ON_BLUE");
      Story story0 = null;
      try {
        story0 = new Story();
      }catch(NoClassDefFoundError e) {
        /*
         * Could not initialize class org.jbehave.core.model.GivenStories
         */
        /*
      %%%<ex><className val="NoClassDefFoundError"/><stackDepth val="18"/><causeDepth val="0"/><source val="org.jbehave.core.model.Story.&lt;init&gt;(Story.java:40)"/></ex>%%%
         */
      }
  }
}
