/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.model;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.List;
import java.util.regex.PatternSyntaxException;
import org.jbehave.core.model.TableUtils;


public class TableUtilsEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I36 Branch 1 IF_ICMPLT L7 - true
   * 2 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I36 Branch 1 IF_ICMPLT L7 - false
   */
  @Test
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try {
        TableUtils.parseRow("/Xdc,Acf1'", "/Xdc,Acf1'", true);
      }catch(PatternSyntaxException e) {
        /*
         * Illegal/unsupported escape sequence near index 3
         * \\/\\X\\d\\c\\,\\A\\c\\f\\1\\'
         *    ^
         */
        /*
      %%%<ex><className val="PatternSyntaxException"/><stackDepth val="23"/><causeDepth val="0"/><source val="java.util.regex.Pattern.error(Pattern.java:1730)"/></ex>%%%
         */
      }
  }

  //Test case number: 1
  /*
   * 13 covered goals:
   * 1 org.jbehave.core.model.TableUtils.<init>()V: root-Branch
   * 2 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I36 Branch 1 IF_ICMPLT L7 - true
   * 3 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I66 Branch 2 IFEQ L12 - true
   * 4 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I81 Branch 3 IF_ICMPLT L11 - true
   * 5 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I89 Branch 4 IFEQ L14 - true
   * 6 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I107 Branch 5 IF_ICMPEQ L18 - true
   * 7 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I113 Branch 6 IFEQ L18 - true
   * 8 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I36 Branch 1 IF_ICMPLT L7 - false
   * 9 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I66 Branch 2 IFEQ L12 - false
   * 10 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I81 Branch 3 IF_ICMPLT L11 - false
   * 11 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I89 Branch 4 IFEQ L14 - false
   * 12 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I107 Branch 5 IF_ICMPEQ L18 - false
   * 13 org.jbehave.core.model.TableUtils.parseRow(Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/List;: I113 Branch 6 IFEQ L18 - false
   */
  @Test
  public void test1()  throws Throwable  {
      String string0 = "";
      List<String> list0 = TableUtils.parseRow("", "", true);
      String string1 = "\\";
      List<String> list1 = TableUtils.parseRow("", "", true);
      boolean boolean0 = false;
      List<String> list2 = TableUtils.parseRow("", "", false);
      List<String> list3 = TableUtils.parseRow("", "", false);
      List<String> list4 = TableUtils.parseRow("", "", false);
      List<String> list5 = TableUtils.parseRow("", "", false);
      TableUtils tableUtils0 = new TableUtils();
      String string2 = "+Op`";
      TableUtils tableUtils1 = new TableUtils();
      List<String> list6 = TableUtils.parseRow("+Op`", "", false);
      // Undeclared exception!
      try {
        TableUtils.parseRow("", "+Op`", false);
      }catch(PatternSyntaxException e) {
        /*
         * Illegal/unsupported escape sequence near index 3
         * \\+\\O\\p\\`
         *    ^
         */
        /*
      %%%<ex><className val="PatternSyntaxException"/><stackDepth val="23"/><causeDepth val="0"/><source val="java.util.regex.Pattern.error(Pattern.java:1730)"/></ex>%%%
         */
      }
  }
}
