/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.set;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Array;
import java.util.HashSet;
import java.util.Set;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.functors.InvokerTransformer;
import org.apache.commons.collections4.set.TransformedSet;
import org.junit.BeforeClass;

public class TransformedSetEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 4 covered goals:
   * 1 org.apache.commons.collections4.set.TransformedSet.<init>(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)V: root-Branch
   * 2 org.apache.commons.collections4.set.TransformedSet.transformedSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Set;: I11 Branch 1 IFNULL L78 - false
   * 3 org.apache.commons.collections4.set.TransformedSet.transformedSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Set;: I13 Branch 2 IFNULL L78 - false
   * 4 org.apache.commons.collections4.set.TransformedSet.transformedSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Set;: I16 Branch 3 IFLE L78 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1195,"org.apache.commons.collections4.set.TransformedSetEvoSuiteTest.test0");
      HashSet<String> hashSet0 = new HashSet<String>();
      Class<String>[] classArray0 = (Class<String>[]) Array.newInstance(Class.class, 6);
      InvokerTransformer<String, String> invokerTransformer0 = new InvokerTransformer<String, String>("", (Class<?>[]) classArray0, (Object[]) classArray0);
      Set<String> set0 = TransformedSet.transformedSet((Set<String>) hashSet0, (Transformer<? super String, ? extends String>) invokerTransformer0);
      assertEquals(true, set0.isEmpty());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.apache.commons.collections4.set.TransformedSet.transformingSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Lorg/apache/commons/collections4/set/TransformedSet;: root-Branch
   */

  @Test
  public void test1()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1196,"org.apache.commons.collections4.set.TransformedSetEvoSuiteTest.test1");
      Class<String>[] classArray0 = (Class<String>[]) Array.newInstance(Class.class, 9);
      InvokerTransformer<Object, Integer> invokerTransformer0 = new InvokerTransformer<Object, Integer>("S5~G![R", (Class<?>[]) classArray0, (Object[]) classArray0);
      // Undeclared exception!
      try {
        TransformedSet.transformingSet((Set<Integer>) null, (Transformer<? super Integer, ? extends Integer>) invokerTransformer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Collection must not be null
         //
      }
  }

  //Test case number: 2
  /*
   * 6 covered goals:
   * 1 org.apache.commons.collections4.set.TransformedSet.transformedSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Set;: I41 Branch 4 IF_ICMPGE L82 - true
   * 2 org.apache.commons.collections4.set.TransformedSet.<init>(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)V: root-Branch
   * 3 org.apache.commons.collections4.set.TransformedSet.transformedSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Set;: I11 Branch 1 IFNULL L78 - false
   * 4 org.apache.commons.collections4.set.TransformedSet.transformedSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Set;: I13 Branch 2 IFNULL L78 - false
   * 5 org.apache.commons.collections4.set.TransformedSet.transformedSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Set;: I16 Branch 3 IFLE L78 - false
   * 6 org.apache.commons.collections4.set.TransformedSet.transformedSet(Ljava/util/Set;Lorg/apache/commons/collections4/Transformer;)Ljava/util/Set;: I41 Branch 4 IF_ICMPGE L82 - false
   */

  @Test
  public void test2()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1197,"org.apache.commons.collections4.set.TransformedSetEvoSuiteTest.test2");
      HashSet<String> hashSet0 = new HashSet<String>();
      Class<String>[] classArray0 = (Class<String>[]) Array.newInstance(Class.class, 8);
      InvokerTransformer<String, String> invokerTransformer0 = new InvokerTransformer<String, String>("", (Class<?>[]) classArray0, (Object[]) classArray0);
      hashSet0.add((String) null);
      TransformedSet.transformedSet((Set<String>) hashSet0, (Transformer<? super String, ? extends String>) invokerTransformer0);
      assertEquals("[null]", hashSet0.toString());
      assertEquals(false, hashSet0.isEmpty());
  }
}
