/*
 * This file was automatically generated by EvoSuite
 */

package org.apache.commons.collections4.set;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.SortedSet;
import java.util.TreeSet;
import org.apache.commons.collections4.set.UnmodifiableSortedSet;
import org.junit.BeforeClass;

public class UnmodifiableSortedSetEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.utils.LoggingUtils.setLoggingForJUnit(); 
  } 


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.apache.commons.collections4.set.UnmodifiableSortedSet.unmodifiableSortedSet(Ljava/util/SortedSet;)Ljava/util/SortedSet;: I4 Branch 1 IFEQ L57 - false
   * 2 org.apache.commons.collections4.set.UnmodifiableSortedSet.unmodifiableSortedSet(Ljava/util/SortedSet;)Ljava/util/SortedSet;: I4 Branch 1 IFEQ L57 - true
   */

  @Test
  public void test0()  throws Throwable  {
		fr.inria.diversify.sosie.logger.LogWriter.writeTestStart(1206,"org.apache.commons.collections4.set.UnmodifiableSortedSetEvoSuiteTest.test0");
      TreeSet<Object> treeSet0 = new TreeSet<Object>();
      SortedSet<Object> sortedSet0 = UnmodifiableSortedSet.unmodifiableSortedSet((SortedSet<Object>) treeSet0);
      SortedSet<Object> sortedSet1 = UnmodifiableSortedSet.unmodifiableSortedSet(sortedSet0);
      assertSame(sortedSet1, sortedSet0);
  }
}
